// Generated by scripts/generate-docs-catalog.mjs — do not edit manually.

export interface DocsPackageEntry {
  id: string;
  name: string;
  tagline: string;
  example: string;
  features: string[];
  peer?: string;
}

export interface DocsComponentEntry {
  id: string;
  name: string;
  category: string;
}

export interface DocsGuideEntry {
  id: string;
  title: string;
  file: string;
}

export const docsPackages: DocsPackageEntry[] = [
  {
    "id": "accessibility",
    "name": "@larose-ui/accessibility",
    "tagline": "Accessibility utilities and component source scanners.",
    "example": "import { scanComponentSource } from '@larose-ui/accessibility';",
    "features": [
      "Static a11y heuristics",
      "Integrated with larose doctor"
    ]
  },
  {
    "id": "ai",
    "name": "@larose-ui/ai",
    "tagline": "Permission-bound AI for SmartTable and SmartForm.",
    "peer": "react >=18",
    "example": "import { SmartTable, AIProvider } from '@larose-ui/ai';",
    "features": [
      "Natural-language filtering",
      "Permission-gated AI actions"
    ]
  },
  {
    "id": "cli",
    "name": "@larose-ui/cli",
    "tagline": "CLI for quality gates, migration, and code generation.",
    "example": "larose doctor --ci",
    "features": [
      "larose doctor",
      "larose migrate",
      "larose generate"
    ]
  },
  {
    "id": "contracts",
    "name": "@larose-ui/contracts",
    "tagline": "Validate UI schemas against API contracts in CI.",
    "example": "import { validateContract } from '@larose-ui/contracts';\n\nvalidateContract(uiSchema, apiSchema);",
    "features": [
      "Field mismatch detection",
      "Used by larose doctor"
    ]
  },
  {
    "id": "core",
    "name": "@larose-ui/core",
    "tagline": "Framework-agnostic types, state machines, and runtime contracts.",
    "example": "import { createAsyncStateMachine, classifyHttpError } from '@larose-ui/core';\n\nconst machine = createAsyncStateMachine();\nmachine.send({ type: 'START' });",
    "features": [
      "Shared TypeScript types (`UIState`, `AsyncState`, `Environment`)",
      "Async state machine factory",
      "HTTP error classification",
      "Runtime event bus and session state machine"
    ]
  },
  {
    "id": "data",
    "name": "@larose-ui/data",
    "tagline": "Backend-aware data fetching with self-healing errors.",
    "peer": "react >=18",
    "example": "import { DataView } from '@larose-ui/data';\n\n<DataView url=\"/api/employees\">{(rows) => <Table data={rows} />}</DataView>",
    "features": [
      "useQuery, useMutation, DataView",
      "Self-healing errors",
      "useUndo"
    ]
  },
  {
    "id": "desktop-core",
    "name": "@larose-ui/desktop-core",
    "tagline": "Desktop host utilities — native menus, accelerators, window chrome.",
    "example": "import { registerHost, mapMenuBarToNative } from '@larose-ui/desktop-core';",
    "features": [
      "Electron/Tauri host registration",
      "Native menu mapping"
    ]
  },
  {
    "id": "devtools",
    "name": "@larose-ui/devtools",
    "tagline": "In-app runtime inspector for development.",
    "peer": "react >=18",
    "example": "import { DevToolsProvider } from '@larose-ui/devtools';",
    "features": [
      "Runtime context panel",
      "Event timeline",
      "Component inspector"
    ]
  },
  {
    "id": "electron",
    "name": "@larose-ui/electron",
    "tagline": "Electron adapter for laRose desktop apps.",
    "peer": "electron >=28, react >=18",
    "example": "import { LaRoseElectronRoot } from '@larose-ui/electron/client';",
    "features": [
      "Host bootstrap",
      "Native menu templates"
    ]
  },
  {
    "id": "enterprise",
    "name": "@larose-ui/enterprise",
    "tagline": "Enterprise patterns — audit trails, session guards, schema IaC.",
    "peer": "react >=18",
    "example": "import { SessionGuard, AuditedInput } from '@larose-ui/enterprise';",
    "features": [
      "Audit trails",
      "Session expiry",
      "UI schema renderer"
    ]
  },
  {
    "id": "forms",
    "name": "@larose-ui/forms",
    "tagline": "Schema-driven forms with validation and conditional fields.",
    "peer": "react >=18",
    "example": "import { Form } from '@larose-ui/forms';\n\n<Form schema={{ id: 'user', fields: [{ name: 'email', type: 'text', label: 'Email' }] }} />",
    "features": [
      "Declarative schemas",
      "Conditional visibility",
      "Observability integration"
    ]
  },
  {
    "id": "migration",
    "name": "@larose-ui/migration",
    "tagline": "Codemods, generators, and release intelligence.",
    "example": "larose migrate --to 1.0.0 --apply",
    "features": [
      "Safe codemods",
      "Scaffolds",
      "Release reports"
    ]
  },
  {
    "id": "network",
    "name": "@larose-ui/network",
    "tagline": "Network condition detection for adaptive UI.",
    "example": "import { createNetworkMonitor } from '@larose-ui/network';\n\nconst monitor = createNetworkMonitor();\nmonitor.subscribe((state) => console.log(state.condition));",
    "features": [
      "Online, offline, slow detection",
      "Skeleton vs spinner recommendations"
    ]
  },
  {
    "id": "next",
    "name": "@larose-ui/next",
    "tagline": "Next.js integration — SSR theme script and LaRoseRoot boundary.",
    "peer": "next >=14, react >=18",
    "example": "import { LaRoseRoot, createLaRoseThemeScriptContent } from '@larose-ui/next';",
    "features": [
      "SSR-safe providers",
      "Theme bootstrap script",
      "CSS path helpers"
    ]
  },
  {
    "id": "nuxt",
    "name": "@larose-ui/nuxt",
    "tagline": "Nuxt module for CSS injection, theme script, and Vue providers.",
    "peer": "nuxt >=3.10",
    "example": "export default defineNuxtConfig({ modules: ['@larose-ui/nuxt'] });",
    "features": [
      "Auto-imports",
      "SSR theme script",
      "LaRoseApp shell"
    ]
  },
  {
    "id": "observability",
    "name": "@larose-ui/observability",
    "tagline": "UX observability — journeys, funnels, and rage-click analysis.",
    "peer": "react >=18",
    "example": "import { useJourneyPage } from '@larose-ui/observability';\n\nuseJourneyPage('employees');",
    "features": [
      "Journey tracking",
      "Form funnel metrics",
      "Rage click analysis"
    ]
  },
  {
    "id": "offline",
    "name": "@larose-ui/offline",
    "tagline": "Offline request queue with sync and conflict handling.",
    "example": "import { createOfflineQueue } from '@larose-ui/offline';\n\nawait queue.enqueue({ url: '/api/items', method: 'POST', body: { name: 'Draft' } });",
    "features": [
      "Persistent queue",
      "Automatic sync when online",
      "Retry and conflict detection"
    ]
  },
  {
    "id": "permissions",
    "name": "@larose-ui/permissions",
    "tagline": "Authorization-aware UI with RBAC/ABAC patterns.",
    "peer": "react >=18",
    "example": "import { Can } from '@larose-ui/permissions';\n\n<Can permission=\"employees.delete\"><DeleteButton /></Can>",
    "features": [
      "Can and Permission components",
      "Explainable blocked actions"
    ]
  },
  {
    "id": "primitives",
    "name": "@larose-ui/primitives",
    "tagline": "Headless menu keyboard, type-ahead, and accelerator behavior.",
    "example": "import { handleMenuKeyboard } from '@larose-ui/primitives';",
    "features": [
      "Menu keyboard navigation",
      "Type-ahead",
      "Mnemonic bindings"
    ]
  },
  {
    "id": "react",
    "name": "@larose-ui/react",
    "tagline": "Production-ready React components with built-in UI states.",
    "peer": "react >=18",
    "example": "import { Button, Card, Input } from '@larose-ui/react';\nimport '@larose-ui/tokens/styles.css';\nimport '@larose-ui/styles/styles.css';\nimport '@larose-ui/react/styles.css';",
    "features": [
      "Form controls, overlays, navigation, data display",
      "Token-driven styling",
      "Customization hooks"
    ]
  },
  {
    "id": "runtime",
    "name": "@larose-ui/runtime",
    "tagline": "Unified runtime — theme, i18n, permissions, network, and session.",
    "peer": "react >=18",
    "example": "import { LaRoseProvider } from '@larose-ui/runtime';\n\n<LaRoseProvider theme=\"light\" locale=\"en\" permissions={['app.read']}>\n  <App />\n</LaRoseProvider>",
    "features": [
      "LaRoseProvider composes runtime contexts",
      "useRuntime, useSession, useTheme",
      "Toast subpath"
    ]
  },
  {
    "id": "runtime-core",
    "name": "@larose-ui/runtime-core",
    "tagline": "Framework-agnostic runtime store, host detection, and i18n.",
    "example": "import { createRuntimeStore, detectHostEnvironment } from '@larose-ui/runtime-core';",
    "features": [
      "Runtime store",
      "Host capabilities",
      "Tenant and session bridges"
    ]
  },
  {
    "id": "styles",
    "name": "@larose-ui/styles",
    "tagline": "Framework-agnostic component CSS from the design system.",
    "example": "import '@larose-ui/tokens/styles.css';\nimport '@larose-ui/styles/styles.css';",
    "features": [
      "CSS modules consumed by React, Vue, and Svelte",
      "Single visual language"
    ]
  },
  {
    "id": "svelte",
    "name": "@larose-ui/svelte",
    "tagline": "Svelte 5 components with runes and shared laRose styles.",
    "peer": "svelte >=5",
    "example": "import { LaRoseProvider, Button } from '@larose-ui/svelte';\nimport '@larose-ui/tokens/styles.css';\nimport '@larose-ui/styles/styles.css';",
    "features": [
      "Svelte 5 runes",
      "Shared design tokens",
      "Foundation parity components"
    ]
  },
  {
    "id": "tauri",
    "name": "@larose-ui/tauri",
    "tagline": "Tauri adapter for laRose desktop webviews.",
    "peer": "react >=18",
    "example": "import { LaRoseTauriRoot } from '@larose-ui/tauri/client';",
    "features": [
      "Host bootstrap",
      "Tauri menu helpers"
    ]
  },
  {
    "id": "testing",
    "name": "@larose-ui/testing",
    "tagline": "Test utilities with full laRose runtime context.",
    "peer": "react >=18",
    "example": "import { renderWithLaRose } from '@larose-ui/testing';\n\nrenderWithLaRose(<App />, { permissions: ['app.read'] });",
    "features": [
      "renderWithLaRose wrapper",
      "Test matrix scenarios"
    ]
  },
  {
    "id": "themes",
    "name": "@larose-ui/themes",
    "tagline": "Named theme presets and tenant branding helpers.",
    "example": "import { createTheme } from '@larose-ui/themes';\n\nconst theme = createTheme({ preset: 'refined', colors: { primary: '#6C5CE7' } });",
    "features": [
      "Built-in presets",
      "Runtime theme application",
      "Component token overrides"
    ]
  },
  {
    "id": "tokens",
    "name": "@larose-ui/tokens",
    "tagline": "Runtime design tokens as CSS custom properties.",
    "example": "import '@larose-ui/tokens/styles.css';\nimport { getTokens, tokensToCSSVariables } from '@larose-ui/tokens';\n\nconst vars = tokensToCSSVariables(getTokens('light'));",
    "features": [
      "Light and dark palettes",
      "Density scaling",
      "Runtime CSS variables",
      "Tenant brand overrides"
    ]
  },
  {
    "id": "vue",
    "name": "@larose-ui/vue",
    "tagline": "Vue 3 components — thin adapter over shared styles and runtime-core.",
    "peer": "vue >=3.5",
    "example": "import { LaRoseProvider, Button, Input } from '@larose-ui/vue';\nimport '@larose-ui/tokens/styles.css';\nimport '@larose-ui/styles/styles.css';",
    "features": [
      "Foundation parity set with React",
      "Composition API providers",
      "Shared CSS modules"
    ]
  }
];

export const docsComponents: DocsComponentEntry[] = [
  {
    "id": "activity-share-button",
    "name": "ActivityShareButton",
    "category": "Actions"
  },
  {
    "id": "activity-view",
    "name": "ActivityView",
    "category": "Sharing"
  },
  {
    "id": "alert",
    "name": "Alert",
    "category": "Feedback"
  },
  {
    "id": "alert-dialog",
    "name": "AlertDialog",
    "category": "Feedback"
  },
  {
    "id": "async-button",
    "name": "AsyncButton",
    "category": "Actions"
  },
  {
    "id": "badge",
    "name": "Badge",
    "category": "Feedback"
  },
  {
    "id": "box",
    "name": "Box",
    "category": "Layout"
  },
  {
    "id": "breadcrumb",
    "name": "Breadcrumb",
    "category": "Navigation"
  },
  {
    "id": "button",
    "name": "Button",
    "category": "Actions"
  },
  {
    "id": "button-group",
    "name": "ButtonGroup",
    "category": "Actions"
  },
  {
    "id": "card",
    "name": "Card",
    "category": "Layout"
  },
  {
    "id": "chart",
    "name": "Chart",
    "category": "Data"
  },
  {
    "id": "checkbox",
    "name": "Checkbox",
    "category": "Forms"
  },
  {
    "id": "collaboration-button",
    "name": "CollaborationButton",
    "category": "Actions"
  },
  {
    "id": "collaboration-popover",
    "name": "CollaborationPopover",
    "category": "Sharing"
  },
  {
    "id": "collection",
    "name": "Collection",
    "category": "Layout"
  },
  {
    "id": "column-view",
    "name": "ColumnView",
    "category": "Layout"
  },
  {
    "id": "command-palette",
    "name": "CommandPalette",
    "category": "Overlay"
  },
  {
    "id": "context-menu",
    "name": "ContextMenu",
    "category": "Overlay"
  },
  {
    "id": "data-table",
    "name": "DataTable",
    "category": "Data"
  },
  {
    "id": "date-picker",
    "name": "DatePicker",
    "category": "Forms"
  },
  {
    "id": "date-range-picker",
    "name": "DateRangePicker",
    "category": "Forms"
  },
  {
    "id": "dialog",
    "name": "Dialog",
    "category": "Overlay"
  },
  {
    "id": "disclosure-button",
    "name": "DisclosureButton",
    "category": "Content"
  },
  {
    "id": "disclosure-triangle",
    "name": "DisclosureTriangle",
    "category": "Content"
  },
  {
    "id": "dock-bar",
    "name": "DockBar",
    "category": "Navigation"
  },
  {
    "id": "dock-menu",
    "name": "DockMenu",
    "category": "Navigation"
  },
  {
    "id": "document-launcher",
    "name": "DocumentLauncher",
    "category": "Files"
  },
  {
    "id": "document-toolbar",
    "name": "DocumentToolbar",
    "category": "Files"
  },
  {
    "id": "drag-drop-list",
    "name": "DragDropList",
    "category": "DragDrop"
  },
  {
    "id": "draggable",
    "name": "Draggable",
    "category": "DragDrop"
  },
  {
    "id": "drawer",
    "name": "Drawer",
    "category": "Overlay"
  },
  {
    "id": "drop-zone",
    "name": "DropZone",
    "category": "DragDrop"
  },
  {
    "id": "edit-menu",
    "name": "EditMenu",
    "category": "Navigation"
  },
  {
    "id": "edit-menu-selection",
    "name": "EditMenuSelection",
    "category": "Other"
  },
  {
    "id": "empty-state",
    "name": "EmptyState",
    "category": "Feedback"
  },
  {
    "id": "file-browser",
    "name": "FileBrowser",
    "category": "Files"
  },
  {
    "id": "file-preview",
    "name": "FilePreview",
    "category": "Files"
  },
  {
    "id": "file-upload",
    "name": "FileUpload",
    "category": "Forms"
  },
  {
    "id": "form-continue",
    "name": "FormContinue",
    "category": "Forms"
  },
  {
    "id": "help-button",
    "name": "HelpButton",
    "category": "Actions"
  },
  {
    "id": "home-screen-quick-actions",
    "name": "HomeScreenQuickActions",
    "category": "Platform"
  },
  {
    "id": "image-button",
    "name": "ImageButton",
    "category": "Content"
  },
  {
    "id": "image-overlay",
    "name": "ImageOverlay",
    "category": "Content"
  },
  {
    "id": "image-view",
    "name": "ImageView",
    "category": "Content"
  },
  {
    "id": "image-well",
    "name": "ImageWell",
    "category": "Content"
  },
  {
    "id": "input",
    "name": "Input",
    "category": "Forms"
  },
  {
    "id": "label",
    "name": "Label",
    "category": "Content"
  },
  {
    "id": "la-rose-provider",
    "name": "LaRoseProvider",
    "category": "Other"
  },
  {
    "id": "list",
    "name": "List",
    "category": "Data"
  },
  {
    "id": "list-row",
    "name": "ListRow",
    "category": "Data"
  },
  {
    "id": "list-section",
    "name": "ListSection",
    "category": "Data"
  },
  {
    "id": "lockup",
    "name": "Lockup",
    "category": "Layout"
  },
  {
    "id": "menu",
    "name": "Menu",
    "category": "Navigation"
  },
  {
    "id": "menu-bar",
    "name": "MenuBar",
    "category": "Navigation"
  },
  {
    "id": "menu-bar-extra",
    "name": "MenuBarExtra",
    "category": "Navigation"
  },
  {
    "id": "modal",
    "name": "Modal",
    "category": "Overlay"
  },
  {
    "id": "more-pull-down-button",
    "name": "MorePullDownButton",
    "category": "Navigation"
  },
  {
    "id": "ornament",
    "name": "Ornament",
    "category": "Layout"
  },
  {
    "id": "ornament-button",
    "name": "OrnamentButton",
    "category": "Layout"
  },
  {
    "id": "ornament-window",
    "name": "OrnamentWindow",
    "category": "Layout"
  },
  {
    "id": "outline-view",
    "name": "OutlineView",
    "category": "Data"
  },
  {
    "id": "outline-view-toolbar",
    "name": "OutlineViewToolbar",
    "category": "Data"
  },
  {
    "id": "pagination",
    "name": "Pagination",
    "category": "Navigation"
  },
  {
    "id": "path-control",
    "name": "PathControl",
    "category": "Navigation"
  },
  {
    "id": "popover",
    "name": "Popover",
    "category": "Overlay"
  },
  {
    "id": "pop-up-button",
    "name": "PopUpButton",
    "category": "Navigation"
  },
  {
    "id": "progress",
    "name": "Progress",
    "category": "Feedback"
  },
  {
    "id": "pull-down-button",
    "name": "PullDownButton",
    "category": "Navigation"
  },
  {
    "id": "radio",
    "name": "Radio",
    "category": "Forms"
  },
  {
    "id": "secure-field",
    "name": "SecureField",
    "category": "Forms"
  },
  {
    "id": "select",
    "name": "Select",
    "category": "Forms"
  },
  {
    "id": "skeleton",
    "name": "Skeleton",
    "category": "Feedback"
  },
  {
    "id": "spinner",
    "name": "Spinner",
    "category": "Feedback"
  },
  {
    "id": "split-view-toolbar",
    "name": "SplitViewToolbar",
    "category": "Layout"
  },
  {
    "id": "square-button",
    "name": "SquareButton",
    "category": "Actions"
  },
  {
    "id": "switch",
    "name": "Switch",
    "category": "Forms"
  },
  {
    "id": "table",
    "name": "Table",
    "category": "Data"
  },
  {
    "id": "textarea",
    "name": "Textarea",
    "category": "Forms"
  },
  {
    "id": "text-view",
    "name": "TextView",
    "category": "Content"
  },
  {
    "id": "time-picker",
    "name": "TimePicker",
    "category": "Forms"
  },
  {
    "id": "toast-provider",
    "name": "ToastProvider",
    "category": "Feedback"
  },
  {
    "id": "token-field",
    "name": "TokenField",
    "category": "Forms"
  },
  {
    "id": "tooltip",
    "name": "Tooltip",
    "category": "Feedback"
  },
  {
    "id": "typography",
    "name": "Typography",
    "category": "Content"
  },
  {
    "id": "unsaved-indicator",
    "name": "UnsavedIndicator",
    "category": "Files"
  },
  {
    "id": "web-view",
    "name": "WebView",
    "category": "Content"
  },
  {
    "id": "web-view-navigation",
    "name": "WebViewNavigation",
    "category": "Content"
  },
  {
    "id": "web-view-shell",
    "name": "WebViewShell",
    "category": "Content"
  }
];

export const docsGuides: DocsGuideEntry[] = [
  {
    "id": "architecture",
    "title": "Architecture",
    "file": "docs/architecture/ARCHITECTURE.md"
  },
  {
    "id": "vue",
    "title": "Vue 3",
    "file": "docs/ecosystem/VUE.md"
  },
  {
    "id": "svelte",
    "title": "Svelte 5",
    "file": "docs/ecosystem/SVELTE.md"
  },
  {
    "id": "nextjs",
    "title": "Next.js",
    "file": "docs/ecosystem/NEXTJS.md"
  },
  {
    "id": "nuxt",
    "title": "Nuxt",
    "file": "docs/ecosystem/NUXT.md"
  },
  {
    "id": "desktop",
    "title": "Desktop integration",
    "file": "docs/ecosystem/DESKTOP.md"
  },
  {
    "id": "runtime",
    "title": "Runtime",
    "file": "docs/runtime/RUNTIME_2.md"
  },
  {
    "id": "customization",
    "title": "Customization",
    "file": "docs/design/CUSTOMIZATION.md"
  },
  {
    "id": "motion",
    "title": "Motion system",
    "file": "docs/design/MOTION_SYSTEM.md"
  },
  {
    "id": "design-language",
    "title": "Refined design language",
    "file": "docs/design/REFINED_DESIGN_LANGUAGE.md"
  },
  {
    "id": "observability",
    "title": "Observability",
    "file": "docs/observability/OBSERVABILITY_2.md"
  },
  {
    "id": "devtools",
    "title": "DevTools",
    "file": "docs/devtools/DEVTOOLS_2.md"
  },
  {
    "id": "ai",
    "title": "AI runtime",
    "file": "docs/ai/AI_RUNTIME.md"
  },
  {
    "id": "migration",
    "title": "Migration & CLI",
    "file": "docs/ecosystem/MIGRATION.md"
  },
  {
    "id": "roadmap",
    "title": "Roadmap",
    "file": "docs/ROADMAP.md"
  }
];

export const docsComponentCategories = [
  "Actions",
  "Content",
  "Data",
  "DragDrop",
  "Feedback",
  "Files",
  "Forms",
  "Layout",
  "Navigation",
  "Other",
  "Overlay",
  "Platform",
  "Sharing"
];

export function findPackage(id: string): DocsPackageEntry | undefined {
  return docsPackages.find((entry) => entry.id === id);
}

export function findComponent(id: string): DocsComponentEntry | undefined {
  return docsComponents.find((entry) => entry.id === id);
}

export function findGuide(id: string): DocsGuideEntry | undefined {
  return docsGuides.find((entry) => entry.id === id);
}
