// Generated by scripts/generate-docs-catalog.mjs — do not edit manually.

export interface DocsChangelogEntry {
  package: string;
  version: string;
  heading: string;
  body: string;
}

export const docsChangelog: DocsChangelogEntry[] = [
  {
    "package": "@larose-ui/cli",
    "version": "Unreleased",
    "heading": "Unreleased",
    "body": "### Minor Changes\n\n- Contribute CLI no longer lists electron/tauri host packages.\n\n- Add `larose contribute` to scaffold component/module stubs for monorepo contributors (package-aware paths, tests, shared styles, CHANGELOG Unreleased)."
  },
  {
    "package": "@larose-ui/migration",
    "version": "Unreleased",
    "heading": "Unreleased",
    "body": "### Minor Changes\n\n- Drop electron/tauri contribute profiles; keep generic module scaffolds.\n\n- Add smart component/module contribution scaffold plans used by `larose contribute`."
  },
  {
    "package": "@larose-ui/react",
    "version": "Unreleased",
    "heading": "Unreleased",
    "body": "### Minor Changes\n\n- Remove WebView components; laRose stays web-first without embedded browser chrome."
  },
  {
    "package": "@larose-ui/styles",
    "version": "Unreleased",
    "heading": "Unreleased",
    "body": "### Minor Changes\n\n- Remove WebView CSS modules."
  },
  {
    "package": "@larose-ui/svelte",
    "version": "Unreleased",
    "heading": "Unreleased",
    "body": "### Minor Changes\n\n- Remove WebView components to match React web-first surface."
  },
  {
    "package": "@larose-ui/tokens",
    "version": "Unreleased",
    "heading": "Unreleased",
    "body": "### Minor Changes\n\n- Remove WebView design tokens."
  },
  {
    "package": "@larose-ui/vue",
    "version": "Unreleased",
    "heading": "Unreleased",
    "body": "### Minor Changes\n\n- Remove WebView components to match React web-first surface."
  },
  {
    "package": "@larose-ui/ai-react",
    "version": "2.0.0",
    "heading": "2.0.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/ai-core@0.3.0\n  - @larose-ui/forms-react@0.3.0\n  - @larose-ui/permissions-react@0.3.0\n  - @larose-ui/react@0.3.0\n  - @larose-ui/runtime-react@2.0.0"
  },
  {
    "package": "@larose-ui/devtools-react",
    "version": "2.0.0",
    "heading": "2.0.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/devtools-core@0.3.0\n  - @larose-ui/observability-react@0.3.0\n  - @larose-ui/permissions-react@0.3.0\n  - @larose-ui/runtime-react@2.0.0"
  },
  {
    "package": "@larose-ui/runtime-react",
    "version": "2.0.0",
    "heading": "2.0.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/network@0.3.0\n  - @larose-ui/observability-react@0.3.0\n  - @larose-ui/offline@0.3.0\n  - @larose-ui/permissions-react@0.3.0\n  - @larose-ui/react@0.3.0\n  - @larose-ui/runtime-core@0.3.0\n  - @larose-ui/themes@0.3.0\n  - @larose-ui/tokens@0.3.0"
  },
  {
    "package": "@larose-ui/ai-react",
    "version": "1.0.0",
    "heading": "1.0.0",
    "body": "### Patch Changes\n\n- Updated dependencies [e989652]\n  - @larose-ui/react@0.2.0\n  - @larose-ui/runtime@1.0.0\n  - @larose-ui/permissions@0.2.0\n  - @larose-ui/forms@0.1.2"
  },
  {
    "package": "@larose-ui/devtools-react",
    "version": "1.0.0",
    "heading": "1.0.0",
    "body": "### Minor Changes\n\n- e989652: Evolve laRose into a framework-agnostic UI operating system: extract shared styles to `@larose-ui/styles`, add Vue 3 and Svelte 5 parity adapters, Next/Nuxt/Electron/Tauri/desktop-core integrations, runtime-core and contracts packages, cross-framework Storybook parity toolbar, AlertDialog focus-ring fix, docs site redesign with beginner-friendly onboarding, and CI/build fixes.\n\n### Patch Changes\n\n- Updated dependencies [e989652]\n  - @larose-ui/runtime@1.0.0\n  - @lar"
  },
  {
    "package": "@larose-ui/runtime-react",
    "version": "1.0.0",
    "heading": "1.0.0",
    "body": "### Minor Changes\n\n- e989652: Evolve laRose into a framework-agnostic UI operating system: extract shared styles to `@larose-ui/styles`, add Vue 3 and Svelte 5 parity adapters, Next/Nuxt/Electron/Tauri/desktop-core integrations, runtime-core and contracts packages, cross-framework Storybook parity toolbar, AlertDialog focus-ring fix, docs site redesign with beginner-friendly onboarding, and CI/build fixes.\n\n### Patch Changes\n\n- Updated dependencies [e989652]\n  - @larose-ui/react@0.2.0\n  - @laros"
  },
  {
    "package": "@larose-ui/runtime-svelte",
    "version": "1.0.0",
    "heading": "1.0.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/network@0.3.0\n  - @larose-ui/observability-svelte@0.3.0\n  - @larose-ui/offline@0.3.0\n  - @larose-ui/permissions-svelte@0.3.0\n  - @larose-ui/runtime-core@0.3.0\n  - @larose-ui/svelte@0.3.0\n  - @larose-ui/themes@0.3.0\n  - @larose-ui/tokens@0.3.0"
  },
  {
    "package": "@larose-ui/runtime-vue",
    "version": "1.0.0",
    "heading": "1.0.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/network@0.3.0\n  - @larose-ui/observability-vue@0.3.0\n  - @larose-ui/offline@0.3.0\n  - @larose-ui/permissions-vue@0.3.0\n  - @larose-ui/runtime-core@0.3.0\n  - @larose-ui/themes@0.3.0\n  - @larose-ui/tokens@0.3.0\n  - @larose-ui/vue@0.3.0"
  },
  {
    "package": "@larose-ui/accessibility",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0"
  },
  {
    "package": "@larose-ui/ai-core",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0"
  },
  {
    "package": "@larose-ui/ai-svelte",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/ai-core@0.3.0\n  - @larose-ui/forms-core@0.3.0\n  - @larose-ui/forms-svelte@0.3.0\n  - @larose-ui/permissions-svelte@0.3.0\n  - @larose-ui/runtime-svelte@1.0.0\n  - @larose-ui/svelte@0.3.0"
  },
  {
    "package": "@larose-ui/ai-vue",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/ai-core@0.3.0\n  - @larose-ui/forms-core@0.3.0\n  - @larose-ui/forms-vue@0.3.0\n  - @larose-ui/permissions-vue@0.3.0\n  - @larose-ui/runtime-vue@1.0.0\n  - @larose-ui/vue@0.3.0"
  },
  {
    "package": "@larose-ui/cli",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/accessibility@0.3.0\n  - @larose-ui/contracts@0.3.0\n  - @larose-ui/migration@0.3.0\n  - @larose-ui/quality-core@0.3.0"
  },
  {
    "package": "@larose-ui/component-logic",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/primitives@0.3.0\n  - @larose-ui/tokens@0.3.0"
  },
  {
    "package": "@larose-ui/contracts",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0"
  },
  {
    "package": "@larose-ui/core",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup."
  },
  {
    "package": "@larose-ui/data-core",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0"
  },
  {
    "package": "@larose-ui/data-react",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/data-core@0.3.0\n  - @larose-ui/permissions-react@0.3.0"
  },
  {
    "package": "@larose-ui/data-svelte",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/data-core@0.3.0"
  },
  {
    "package": "@larose-ui/data-vue",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/data-core@0.3.0"
  },
  {
    "package": "@larose-ui/devtools-core",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/observability-core@0.3.0"
  },
  {
    "package": "@larose-ui/devtools-svelte",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/devtools-core@0.3.0\n  - @larose-ui/observability-svelte@0.3.0\n  - @larose-ui/permissions-svelte@0.3.0\n  - @larose-ui/runtime-svelte@1.0.0"
  },
  {
    "package": "@larose-ui/devtools-vue",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/devtools-core@0.3.0\n  - @larose-ui/observability-vue@0.3.0\n  - @larose-ui/permissions-vue@0.3.0\n  - @larose-ui/runtime-vue@1.0.0"
  },
  {
    "package": "@larose-ui/enterprise-core",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/forms-core@0.3.0"
  },
  {
    "package": "@larose-ui/enterprise-react",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/enterprise-core@0.3.0\n  - @larose-ui/forms-react@0.3.0\n  - @larose-ui/observability-react@0.3.0\n  - @larose-ui/permissions-react@0.3.0\n  - @larose-ui/react@0.3.0\n  - @larose-ui/runtime-react@2.0.0"
  },
  {
    "package": "@larose-ui/enterprise-svelte",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/enterprise-core@0.3.0\n  - @larose-ui/forms-svelte@0.3.0\n  - @larose-ui/observability-svelte@0.3.0\n  - @larose-ui/permissions-svelte@0.3.0\n  - @larose-ui/runtime-svelte@1.0.0\n  - @larose-ui/svelte@0.3.0"
  },
  {
    "package": "@larose-ui/enterprise-vue",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/enterprise-core@0.3.0\n  - @larose-ui/forms-vue@0.3.0\n  - @larose-ui/observability-vue@0.3.0\n  - @larose-ui/permissions-vue@0.3.0\n  - @larose-ui/runtime-vue@1.0.0\n  - @larose-ui/vue@0.3.0"
  },
  {
    "package": "@larose-ui/forms-core",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup."
  },
  {
    "package": "@larose-ui/forms-react",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/data-react@0.3.0\n  - @larose-ui/forms-core@0.3.0\n  - @larose-ui/observability-react@0.3.0\n  - @larose-ui/react@0.3.0"
  },
  {
    "package": "@larose-ui/forms-svelte",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/data-core@0.3.0\n  - @larose-ui/forms-core@0.3.0\n  - @larose-ui/observability-svelte@0.3.0\n  - @larose-ui/svelte@0.3.0"
  },
  {
    "package": "@larose-ui/forms-vue",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup.\n\n### Patch Changes\n\n- Updated dependencies [b11853a]\n  - @larose-ui/core@0.3.0\n  - @larose-ui/data-core@0.3.0\n  - @larose-ui/forms-core@0.3.0\n  - @larose-ui/observability-vue@0.3.0\n  - @larose-ui/vue@0.3.0"
  },
  {
    "package": "@larose-ui/liquid-glass-core",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup."
  },
  {
    "package": "@larose-ui/migration",
    "version": "0.3.0",
    "heading": "0.3.0",
    "body": "### Minor Changes\n\n- b11853a: Cross-framework LiquidGlass parity, runtime providers, sandboxes, and platform adapter cleanup."
  }
];
