// Generated by scripts/generate-docs-catalog.mjs — do not edit manually.

export interface DocsExampleEntry {
  id: string;
  title: string;
  kind: string;
  props: Record<string, string | number | boolean>;
  code: string;
  composite?: boolean;
}

export const docsExamples: Record<string, DocsExampleEntry[]> = {
  "Button": [
    {
      "id": "Primary",
      "title": "Primary",
      "kind": "basic",
      "props": {
        "children": "Add to Cart', variant: 'primary"
      },
      "code": "<Button>Add to Cart', variant: 'primary</Button>"
    },
    {
      "id": "Secondary",
      "title": "Secondary",
      "kind": "advanced",
      "props": {
        "children": "Cancel', variant: 'secondary', buttonRole: 'cancel"
      },
      "code": "<Button>Cancel', variant: 'secondary', buttonRole: 'cancel</Button>"
    },
    {
      "id": "Loading",
      "title": "Loading",
      "kind": "loading",
      "props": {
        "children": "Checkout",
        "loadingLabel": "Checking out…",
        "loading": true
      },
      "code": "<Button\n  loadingLabel=\"Checking out…\"\n  loading\n>Checkout</Button>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "children": "'Unavailable', disabled: true"
      },
      "code": "<Button>'Unavailable', disabled: true</Button>"
    },
    {
      "id": "DestructiveFilled",
      "title": "Destructive Filled",
      "kind": "destructive",
      "props": {
        "children": "Delete Employee', variant: 'destructive"
      },
      "code": "<Button>Delete Employee', variant: 'destructive</Button>"
    },
    {
      "id": "DestructivePlain",
      "title": "Destructive Plain",
      "kind": "destructive",
      "props": {
        "children": "Delete Account",
        "variant": "ghost",
        "buttonRole": "destructive"
      },
      "code": "<Button\n  variant=\"ghost\"\n  buttonRole=\"destructive\"\n>Delete Account</Button>"
    },
    {
      "id": "OpensAnotherView",
      "title": "Opens another view (…)",
      "kind": "advanced",
      "props": {
        "children": "Edit",
        "variant": "secondary",
        "opensAnotherView": true,
        "tooltip": "Opens AutoFill settings"
      },
      "code": "<Button\n  variant=\"secondary\"\n  opensAnotherView\n  tooltip=\"Opens AutoFill settings\"\n>Edit</Button>"
    },
    {
      "id": "IconOnly",
      "title": "Icon Only",
      "kind": "with-icon",
      "props": {},
      "code": "// See Storybook story \"IconOnly\" for composite layout example.",
      "composite": true
    },
    {
      "id": "StyleNotSize",
      "title": "Style, not size",
      "kind": "sizes",
      "props": {},
      "code": "// See Storybook story \"StyleNotSize\" for composite layout example.",
      "composite": true
    },
    {
      "id": "AlertActions",
      "title": "Alert Actions",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"AlertActions\" for composite layout example.",
      "composite": true
    },
    {
      "id": "VisionOSStack",
      "title": "visionOS vertical stack",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"VisionOSStack\" for composite layout example.",
      "composite": true
    },
    {
      "id": "WatchFullWidth",
      "title": "watchOS full width",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"WatchFullWidth\" for composite layout example.",
      "composite": true
    }
  ],
  "Input": [],
  "Badge": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "advanced",
      "props": {
        "children": "Draft"
      },
      "code": "<Badge>Draft</Badge>"
    },
    {
      "id": "Info",
      "title": "Info",
      "kind": "advanced",
      "props": {
        "children": "Beta', variant: 'info"
      },
      "code": "<Badge>Beta', variant: 'info</Badge>"
    },
    {
      "id": "Success",
      "title": "Success",
      "kind": "advanced",
      "props": {
        "children": "Active', variant: 'success"
      },
      "code": "<Badge>Active', variant: 'success</Badge>"
    },
    {
      "id": "Warning",
      "title": "Warning",
      "kind": "advanced",
      "props": {
        "children": "Pending', variant: 'warning"
      },
      "code": "<Badge>Pending', variant: 'warning</Badge>"
    },
    {
      "id": "Error",
      "title": "Error",
      "kind": "advanced",
      "props": {
        "children": "Suspended', variant: 'error"
      },
      "code": "<Badge>Suspended', variant: 'error</Badge>"
    },
    {
      "id": "AllVariants",
      "title": "All Variants",
      "kind": "variants",
      "props": {},
      "code": "// See Storybook story \"AllVariants\" for composite layout example.",
      "composite": true
    }
  ],
  "Checkbox": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "advanced",
      "props": {
        "label": "I agree to the terms"
      },
      "code": "<Checkbox\n  label=\"I agree to the terms\"\n>Example</Checkbox>"
    },
    {
      "id": "Checked",
      "title": "Checked",
      "kind": "advanced",
      "props": {
        "label": "Subscribe to newsletter",
        "defaultChecked": true
      },
      "code": "<Checkbox\n  label=\"Subscribe to newsletter\"\n  defaultChecked\n>Example</Checkbox>"
    },
    {
      "id": "WithHint",
      "title": "With Hint",
      "kind": "advanced",
      "props": {
        "label": "Send me product updates",
        "hint": "You can unsubscribe at any time"
      },
      "code": "<Checkbox\n  label=\"Send me product updates\"\n  hint=\"You can unsubscribe at any time\"\n>Example</Checkbox>"
    },
    {
      "id": "WithError",
      "title": "With Error",
      "kind": "advanced",
      "props": {
        "label": "I agree to the terms",
        "error": "You must accept the terms to continue"
      },
      "code": "<Checkbox\n  label=\"I agree to the terms\"\n  error=\"You must accept the terms to continue\"\n>Example</Checkbox>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "label": "Legacy feature access",
        "disabled": true
      },
      "code": "<Checkbox\n  label=\"Legacy feature access\"\n  disabled\n>Example</Checkbox>"
    }
  ],
  "Switch": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "advanced",
      "props": {
        "label": "Email notifications"
      },
      "code": "<Switch\n  label=\"Email notifications\"\n>Example</Switch>"
    },
    {
      "id": "Checked",
      "title": "Checked",
      "kind": "advanced",
      "props": {
        "label": "Push notifications",
        "defaultChecked": true
      },
      "code": "<Switch\n  label=\"Push notifications\"\n  defaultChecked\n>Example</Switch>"
    },
    {
      "id": "WithHint",
      "title": "With Hint",
      "kind": "advanced",
      "props": {
        "label": "Marketing emails",
        "hint": "Receive occasional product announcements"
      },
      "code": "<Switch\n  label=\"Marketing emails\"\n  hint=\"Receive occasional product announcements\"\n>Example</Switch>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "label": "Beta features",
        "disabled": true
      },
      "code": "<Switch\n  label=\"Beta features\"\n  disabled\n>Example</Switch>"
    },
    {
      "id": "SettingsStyle",
      "title": "Settings Style",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SettingsStyle\" for composite layout example.",
      "composite": true
    }
  ],
  "Progress": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "advanced",
      "props": {
        "value": 65,
        "label": "Profile completion",
        "showValue": true
      },
      "code": "<Progress\n  value={65}\n  label=\"Profile completion\"\n  showValue\n>Example</Progress>"
    },
    {
      "id": "Success",
      "title": "Success",
      "kind": "advanced",
      "props": {
        "value": 100,
        "label": "Upload complete",
        "variant": "success",
        "showValue": true
      },
      "code": "<Progress\n  value={100}\n  label=\"Upload complete\"\n  variant=\"success\"\n  showValue\n>Example</Progress>"
    },
    {
      "id": "Error",
      "title": "Error",
      "kind": "advanced",
      "props": {
        "value": 35,
        "label": "Sync failed",
        "variant": "error",
        "showValue": true
      },
      "code": "<Progress\n  value={35}\n  label=\"Sync failed\"\n  variant=\"error\"\n  showValue\n>Example</Progress>"
    },
    {
      "id": "Loading",
      "title": "Loading",
      "kind": "loading",
      "props": {
        "value": 45,
        "label": "Importing employees",
        "showValue": true,
        "state": "loading"
      },
      "code": "<Progress\n  value={45}\n  label=\"Importing employees\"\n  showValue\n  state=\"loading\"\n>Example</Progress>"
    }
  ],
  "Alert": [],
  "Card": [],
  "Select": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "advanced",
      "props": {
        "label": "Department",
        "options": "departmentOptions",
        "placeholder": "Choose a department"
      },
      "code": "<Select\n  label=\"Department\"\n  options=\"departmentOptions\"\n  placeholder=\"Choose a department\"\n>Example</Select>"
    },
    {
      "id": "WithHint",
      "title": "With Hint",
      "kind": "advanced",
      "props": {
        "label": "Department",
        "options": "departmentOptions",
        "hint": "Used for org chart and permissions"
      },
      "code": "<Select\n  label=\"Department\"\n  options=\"departmentOptions\"\n  hint=\"Used for org chart and permissions\"\n>Example</Select>"
    },
    {
      "id": "Required",
      "title": "Required",
      "kind": "advanced",
      "props": {
        "label": "Department",
        "options": "departmentOptions",
        "required": true
      },
      "code": "<Select\n  label=\"Department\"\n  options=\"departmentOptions\"\n  required\n>Example</Select>"
    },
    {
      "id": "Loading",
      "title": "Loading",
      "kind": "loading",
      "props": {
        "label": "Department",
        "options": "departmentOptions",
        "loading": true
      },
      "code": "<Select\n  label=\"Department\"\n  options=\"departmentOptions\"\n  loading\n>Example</Select>"
    },
    {
      "id": "WithError",
      "title": "With Error",
      "kind": "advanced",
      "props": {
        "label": "Department",
        "options": "departmentOptions",
        "error": "Department is required"
      },
      "code": "<Select\n  label=\"Department\"\n  options=\"departmentOptions\"\n  error=\"Department is required\"\n>Example</Select>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "label": "Department",
        "options": "departmentOptions",
        "disabled": true,
        "defaultValue": "eng"
      },
      "code": "<Select\n  label=\"Department\"\n  options=\"departmentOptions\"\n  disabled\n  defaultValue=\"eng\"\n>Example</Select>"
    }
  ],
  "Typography": [],
  "Modal": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Default\" for composite layout example.",
      "composite": true
    },
    {
      "id": "WithoutDescription",
      "title": "Without Description",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"WithoutDescription\" for composite layout example.",
      "composite": true
    },
    {
      "id": "NoOverlayClose",
      "title": "No Overlay Close",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"NoOverlayClose\" for composite layout example.",
      "composite": true
    }
  ],
  "Drawer": [
    {
      "id": "Right",
      "title": "Right",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Right\" for composite layout example.",
      "composite": true
    },
    {
      "id": "Left",
      "title": "Left",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Left\" for composite layout example.",
      "composite": true
    }
  ],
  "Popover": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "advanced",
      "props": {
        "trigger": "<Button variant=\"outline\">Show info</Button>",
        "content": "("
      },
      "code": "<Popover\n  trigger=\"<Button variant=\"outline\">Show info</Button>\"\n  content=\"(\"\n>Example</Popover>"
    },
    {
      "id": "Top",
      "title": "Top",
      "kind": "advanced",
      "props": {
        "side": "top",
        "trigger": "<Button variant=\"secondary\">Top popover</Button>",
        "content": "<p style={{ margin: 0"
      },
      "code": "<Popover\n  side=\"top\"\n  trigger=\"<Button variant=\"secondary\">Top popover</Button>\"\n  content=\"<p style={{ margin: 0\"\n>Example</Popover>"
    },
    {
      "id": "WithActions",
      "title": "With Actions",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"WithActions\" for composite layout example.",
      "composite": true
    }
  ],
  "Tooltip": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "advanced",
      "props": {
        "content": "Export employees as CSV",
        "children": "<Button variant=\"outline\">Export</Button>"
      },
      "code": "<Tooltip\n  content=\"Export employees as CSV\"\n><Button variant=\"outline\">Export</Button></Tooltip>"
    },
    {
      "id": "OnText",
      "title": "On Text",
      "kind": "advanced",
      "props": {
        "content": "Last updated 2 hours ago",
        "children": "<span style={{ textDecoration: 'underline dotted'"
      },
      "code": "<Tooltip\n  content=\"Last updated 2 hours ago\"\n><span style={{ textDecoration: 'underline dotted'</Tooltip>"
    },
    {
      "id": "LongContent",
      "title": "Long Content",
      "kind": "advanced",
      "props": {
        "content": "Keyboard shortcut: ⌘ + Shift + E",
        "children": "<Button variant=\"secondary\">Quick export</Button>"
      },
      "code": "<Tooltip\n  content=\"Keyboard shortcut: ⌘ + Shift + E\"\n><Button variant=\"secondary\">Quick export</Button></Tooltip>"
    }
  ],
  "Textarea": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "advanced",
      "props": {
        "label": "Description",
        "placeholder": "Enter details..."
      },
      "code": "<Textarea\n  label=\"Description\"\n  placeholder=\"Enter details...\"\n>Example</Textarea>"
    },
    {
      "id": "WithHint",
      "title": "With Hint",
      "kind": "advanced",
      "props": {
        "label": "Notes",
        "placeholder": "Add internal notes",
        "hint": "Visible to admins only"
      },
      "code": "<Textarea\n  label=\"Notes\"\n  placeholder=\"Add internal notes\"\n  hint=\"Visible to admins only\"\n>Example</Textarea>"
    },
    {
      "id": "Required",
      "title": "Required",
      "kind": "advanced",
      "props": {
        "label": "Feedback",
        "placeholder": "Tell us what you think",
        "required": true
      },
      "code": "<Textarea\n  label=\"Feedback\"\n  placeholder=\"Tell us what you think\"\n  required\n>Example</Textarea>"
    },
    {
      "id": "WithError",
      "title": "With Error",
      "kind": "advanced",
      "props": {
        "label": "Description",
        "defaultValue": "Too short",
        "error": "Description must be at least 20 characters"
      },
      "code": "<Textarea\n  label=\"Description\"\n  defaultValue=\"Too short\"\n  error=\"Description must be at least 20 characters\"\n>Example</Textarea>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "label": "Archived notes",
        "defaultValue": "This record is read-only.",
        "disabled": true
      },
      "code": "<Textarea\n  label=\"Archived notes\"\n  defaultValue=\"This record is read-only.\"\n  disabled\n>Example</Textarea>"
    }
  ],
  "Radio": [
    {
      "id": "Default",
      "title": "plan",
      "kind": "advanced",
      "props": {
        "name": "plan",
        "label": "Starter plan",
        "value": "starter",
        "defaultChecked": true
      },
      "code": "<Radio\n  name=\"plan\"\n  label=\"Starter plan\"\n  value=\"starter\"\n  defaultChecked\n>Example</Radio>"
    },
    {
      "id": "WithHint",
      "title": "plan",
      "kind": "advanced",
      "props": {
        "name": "plan",
        "label": "Pro plan",
        "value": "pro",
        "hint": "Includes advanced analytics"
      },
      "code": "<Radio\n  name=\"plan\"\n  label=\"Pro plan\"\n  value=\"pro\"\n  hint=\"Includes advanced analytics\"\n>Example</Radio>"
    },
    {
      "id": "WithError",
      "title": "plan",
      "kind": "advanced",
      "props": {
        "name": "plan",
        "label": "Enterprise plan",
        "value": "enterprise",
        "error": "Select a plan to continue"
      },
      "code": "<Radio\n  name=\"plan\"\n  label=\"Enterprise plan\"\n  value=\"enterprise\"\n  error=\"Select a plan to continue\"\n>Example</Radio>"
    },
    {
      "id": "Disabled",
      "title": "plan",
      "kind": "disabled",
      "props": {
        "name": "plan",
        "label": "Legacy plan",
        "value": "legacy",
        "disabled": true
      },
      "code": "<Radio\n  name=\"plan\"\n  label=\"Legacy plan\"\n  value=\"legacy\"\n  disabled\n>Example</Radio>"
    },
    {
      "id": "Group",
      "title": "Group",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Group\" for composite layout example.",
      "composite": true
    }
  ]
};

export function getComponentExamples(name: string): DocsExampleEntry[] {
  return docsExamples[name] ?? [];
}
