// Generated by scripts/generate-docs-catalog.mjs — do not edit manually.

export interface DocsExampleEntry {
  id: string;
  title: string;
  kind: string;
  props: Record<string, string | number | boolean>;
  code: string;
  composite?: boolean;
  component?: string;
}

export const docsExamples: Record<string, DocsExampleEntry[]> = {
  "AcceleratorProvider": [],
  "Accordion": [
    {
      "id": "AccordionDefault",
      "title": "Accordion Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"AccordionDefault\" for full example.",
      "composite": true
    },
    {
      "id": "AccordionCollapse",
      "title": "Accordion Collapse",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"AccordionCollapse\" for full example.",
      "composite": true
    }
  ],
  "AccordionContent": [],
  "AccordionItem": [],
  "AccordionTrigger": [],
  "ActivityShareButton": [],
  "ActivityView": [
    {
      "id": "NotesShareSheet",
      "title": "Notes share sheet",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"NotesShareSheet\" for full example.",
      "composite": true
    },
    {
      "id": "PhotoAppActivities",
      "title": "App-specific activities",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"PhotoAppActivities\" for full example.",
      "composite": true
    },
    {
      "id": "CustomActionTitle",
      "title": "Custom action title",
      "kind": "advanced",
      "props": {},
      "code": "<ActivityView\n        open={open}\n        onClose={() => setOpen(false)}\n        activities={activities}\n        title=\"Share Statement\"\n      />",
      "composite": true
    },
    {
      "id": "SheetPresentation",
      "title": "Sheet Presentation",
      "kind": "advanced",
      "props": {},
      "code": "<ActivityView\n        open={open}\n        onClose={() => setOpen(false)}\n        activities={createDefaultActivities()}\n        presentation=\"sheet\"\n      />",
      "composite": true
    }
  ],
  "Alert": [
    {
      "id": "Info",
      "title": "Info",
      "kind": "advanced",
      "props": {
        "variant": "info",
        "title": "Information",
        "children": "Payroll period closes in 3 days."
      },
      "code": "import { Alert } from '@larose-ui/react';\n\n<Alert\n  variant=\"info\"\n  title=\"Information\"\n>Payroll period closes in 3 days.</Alert>"
    },
    {
      "id": "Success",
      "title": "Success",
      "kind": "advanced",
      "props": {
        "variant": "success",
        "title": "Saved",
        "children": "Employee record updated successfully."
      },
      "code": "import { Alert } from '@larose-ui/react';\n\n<Alert\n  variant=\"success\"\n  title=\"Saved\"\n>Employee record updated successfully.</Alert>"
    },
    {
      "id": "Warning",
      "title": "Warning",
      "kind": "advanced",
      "props": {
        "variant": "warning",
        "title": "Warning",
        "children": "This action affects 12 employees."
      },
      "code": "import { Alert } from '@larose-ui/react';\n\n<Alert\n  variant=\"warning\"\n  title=\"Warning\"\n>This action affects 12 employees.</Alert>"
    },
    {
      "id": "Error",
      "title": "Error",
      "kind": "error",
      "props": {
        "variant": "error",
        "title": "Error",
        "children": "Unable to connect to payroll service."
      },
      "code": "import { Alert } from '@larose-ui/react';\n\n<Alert\n  variant=\"error\"\n  title=\"Error\"\n>Unable to connect to payroll service.</Alert>"
    },
    {
      "id": "Dismissible",
      "title": "Dismissible",
      "kind": "advanced",
      "props": {
        "variant": "info",
        "children": "This notice can be dismissed."
      },
      "code": "import { Alert } from '@larose-ui/react';\n\n<Alert\n  variant=\"info\"\n>This notice can be dismissed.</Alert>"
    },
    {
      "id": "DeleteConfirmation",
      "title": "Destructive (compact)",
      "kind": "destructive",
      "props": {},
      "code": "// See Storybook story \"DeleteConfirmation\" for full example.",
      "composite": true
    },
    {
      "id": "ThreeButtonStack",
      "title": "Three actions (compact)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ThreeButtonStack\" for full example.",
      "composite": true
    },
    {
      "id": "DeliberateEmptyTrash",
      "title": "Deliberate destructive (desktop)",
      "kind": "destructive",
      "props": {},
      "code": "// See Storybook story \"DeliberateEmptyTrash\" for full example.",
      "composite": true
    },
    {
      "id": "InformationalDone",
      "title": "Informational (tablet)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"InformationalDone\" for full example.",
      "composite": true
    },
    {
      "id": "PasswordPrompt",
      "title": "Secure field (desktop)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"PasswordPrompt\" for full example.",
      "composite": true
    }
  ],
  "AlertDialog": [],
  "AsyncButton": [],
  "Badge": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "children": "Draft"
      },
      "code": "import { Badge } from '@larose-ui/react';\n\n<Badge>Draft</Badge>"
    },
    {
      "id": "Info",
      "title": "Info",
      "kind": "advanced",
      "props": {
        "children": "Beta",
        "variant": "info"
      },
      "code": "import { Badge } from '@larose-ui/react';\n\n<Badge\n  variant=\"info\"\n>Beta</Badge>"
    },
    {
      "id": "Success",
      "title": "Success",
      "kind": "advanced",
      "props": {
        "children": "Active",
        "variant": "success"
      },
      "code": "import { Badge } from '@larose-ui/react';\n\n<Badge\n  variant=\"success\"\n>Active</Badge>"
    },
    {
      "id": "Warning",
      "title": "Warning",
      "kind": "advanced",
      "props": {
        "children": "Pending",
        "variant": "warning"
      },
      "code": "import { Badge } from '@larose-ui/react';\n\n<Badge\n  variant=\"warning\"\n>Pending</Badge>"
    },
    {
      "id": "Error",
      "title": "Error",
      "kind": "error",
      "props": {
        "children": "Suspended",
        "variant": "error"
      },
      "code": "import { Badge } from '@larose-ui/react';\n\n<Badge\n  variant=\"error\"\n>Suspended</Badge>"
    },
    {
      "id": "AllVariants",
      "title": "All Variants",
      "kind": "variants",
      "props": {},
      "code": "// See Storybook story \"AllVariants\" for full example.",
      "composite": true
    }
  ],
  "Box": [
    {
      "id": "DisclosureTriangleStory",
      "title": "Disclosure triangle",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DisclosureTriangleStory\" for full example.",
      "composite": true
    },
    {
      "id": "BoxSecondary",
      "title": "Box Secondary",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"BoxSecondary\" for full example.",
      "composite": true
    },
    {
      "id": "BoxSettingsStyle",
      "title": "Box Settings Style",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"BoxSettingsStyle\" for full example.",
      "composite": true
    }
  ],
  "Breadcrumb": [],
  "Button": [
    {
      "id": "Primary",
      "title": "Primary",
      "kind": "basic",
      "props": {
        "children": "Add to Cart",
        "variant": "primary"
      },
      "code": "import { Button } from '@larose-ui/react';\n\n<Button\n  variant=\"primary\"\n>Add to Cart</Button>"
    },
    {
      "id": "Secondary",
      "title": "Secondary",
      "kind": "advanced",
      "props": {
        "children": "Cancel",
        "variant": "secondary",
        "buttonRole": "cancel"
      },
      "code": "import { Button } from '@larose-ui/react';\n\n<Button\n  variant=\"secondary\"\n  buttonRole=\"cancel\"\n>Cancel</Button>"
    },
    {
      "id": "Loading",
      "title": "Loading",
      "kind": "loading",
      "props": {
        "children": "Checkout",
        "loadingLabel": "Checking out…",
        "loading": true
      },
      "code": "import { Button } from '@larose-ui/react';\n\n<Button\n  loadingLabel=\"Checking out…\"\n  loading\n>Checkout</Button>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "children": "Unavailable",
        "disabled": true
      },
      "code": "import { Button } from '@larose-ui/react';\n\n<Button\n  disabled\n>Unavailable</Button>"
    },
    {
      "id": "DestructiveFilled",
      "title": "Destructive Filled",
      "kind": "destructive",
      "props": {
        "children": "Delete Employee",
        "variant": "destructive"
      },
      "code": "import { Button } from '@larose-ui/react';\n\n<Button\n  variant=\"destructive\"\n>Delete Employee</Button>"
    },
    {
      "id": "DestructivePlain",
      "title": "Destructive Plain",
      "kind": "destructive",
      "props": {
        "children": "Delete Account",
        "variant": "ghost",
        "buttonRole": "destructive"
      },
      "code": "import { Button } from '@larose-ui/react';\n\n<Button\n  variant=\"ghost\"\n  buttonRole=\"destructive\"\n>Delete Account</Button>"
    },
    {
      "id": "OpensAnotherView",
      "title": "Opens another view (…)",
      "kind": "advanced",
      "props": {
        "children": "Edit",
        "variant": "secondary",
        "opensAnotherView": true,
        "tooltip": "Opens AutoFill settings"
      },
      "code": "import { Button } from '@larose-ui/react';\n\n<Button\n  variant=\"secondary\"\n  opensAnotherView\n  tooltip=\"Opens AutoFill settings\"\n>Edit</Button>"
    },
    {
      "id": "IconOnly",
      "title": "Icon Only",
      "kind": "with-icon",
      "props": {},
      "code": "// See Storybook story \"IconOnly\" for full example.",
      "composite": true
    },
    {
      "id": "StyleNotSize",
      "title": "Style, not size",
      "kind": "sizes",
      "props": {},
      "code": "// See Storybook story \"StyleNotSize\" for full example.",
      "composite": true
    },
    {
      "id": "AlertActions",
      "title": "Alert Actions",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"AlertActions\" for full example.",
      "composite": true
    },
    {
      "id": "VisionOSStack",
      "title": "visionOS vertical stack",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"VisionOSStack\" for full example.",
      "composite": true
    },
    {
      "id": "WatchFullWidth",
      "title": "watchOS full width",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"WatchFullWidth\" for full example.",
      "composite": true
    },
    {
      "id": "SquareButtons",
      "title": "Square buttons (in-view)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SquareButtons\" for full example.",
      "composite": true
    },
    {
      "id": "AllVariants",
      "title": "All Variants",
      "kind": "variants",
      "props": {},
      "code": "// See Storybook story \"AllVariants\" for full example.",
      "composite": true
    },
    {
      "id": "Sizes",
      "title": "Sizes",
      "kind": "sizes",
      "props": {},
      "code": "// See Storybook story \"Sizes\" for full example.",
      "composite": true
    },
    {
      "id": "DialogMotion",
      "title": "Dialog Motion",
      "kind": "advanced",
      "props": {},
      "code": "<>\n        <Button onClick={() => setOpen(true)}>Open dialog</Button>\n        <Modal open={open} onClose={() => setOpen(false)} title=\"Motion dialog\">\n          <p style={{ margin: 0 }}>Subtle scale, fade, and vertical movement on enter and exit.</p>\n        </Modal>\n      </>",
      "composite": true
    }
  ],
  "ButtonGroup": [],
  "CalendarGrid": [],
  "CaptionButton": [],
  "Card": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "title": "Employee Profile",
        "description": "Manage employee information",
        "children": "Ahmed Mohamed — Software Engineer"
      },
      "code": "import { Card } from '@larose-ui/react';\n\n<Card\n  title=\"Employee Profile\"\n  description=\"Manage employee information\"\n>Ahmed Mohamed — Software Engineer</Card>"
    },
    {
      "id": "WithBadge",
      "title": "With Badge",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"WithBadge\" for full example.",
      "composite": true
    },
    {
      "id": "ClearPromptsAndDefaults",
      "title": "Clear Prompts And Defaults",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"ClearPromptsAndDefaults\" for full example.",
      "composite": true
    },
    {
      "id": "DynamicValidation",
      "title": "Dynamic Validation",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DynamicValidation\" for full example.",
      "composite": true
    },
    {
      "id": "NumericFormatting",
      "title": "Numeric Formatting",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"NumericFormatting\" for full example.",
      "composite": true
    },
    {
      "id": "SecurePasswordField",
      "title": "Secure Password Field",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SecurePasswordField\" for full example.",
      "composite": true
    },
    {
      "id": "PasteAndDrop",
      "title": "Paste And Drop",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"PasteAndDrop\" for full example.",
      "composite": true
    },
    {
      "id": "ContinueWhenComplete",
      "title": "Continue When Complete",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ContinueWhenComplete\" for full example.",
      "composite": true
    },
    {
      "id": "ExpansionTooltip",
      "title": "Expansion Tooltip",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ExpansionTooltip\" for full example.",
      "composite": true
    },
    {
      "id": "DisclosureButtonStory",
      "title": "Disclosure button",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DisclosureButtonStory\" for full example.",
      "composite": true
    },
    {
      "id": "LabelImportance",
      "title": "Label Importance",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"LabelImportance\" for full example.",
      "composite": true
    },
    {
      "id": "SelectableLabel",
      "title": "Selectable Label",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SelectableLabel\" for full example.",
      "composite": true
    },
    {
      "id": "UnsavedChanges",
      "title": "Unsaved Changes",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"UnsavedChanges\" for full example.",
      "composite": true
    },
    {
      "id": "ImportWithFileUpload",
      "title": "Import With File Upload",
      "kind": "loading",
      "props": {},
      "code": "// See Storybook story \"ImportWithFileUpload\" for full example.",
      "composite": true
    },
    {
      "id": "ListAccessories",
      "title": "List Accessories",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ListAccessories\" for full example.",
      "composite": true
    },
    {
      "id": "DocumentToolbar",
      "title": "Document Toolbar",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DocumentToolbar\" for full example.",
      "composite": true
    }
  ],
  "Chart": [
    {
      "id": "BarChart",
      "title": "Bar Chart",
      "kind": "advanced",
      "props": {
        "mark": "bar",
        "title": "Steps",
        "subtitle": "You averaged 8,102 steps per day this week.",
        "accessibilitySummary": "Bar chart showing daily steps for seven days. Highest on Thursday with 11,200 steps.",
        "min": 0,
        "tickCount": 4
      },
      "code": "import { Chart } from '@larose-ui/react';\n\n<Chart\n  mark=\"bar\"\n  title=\"Steps\"\n  subtitle=\"You averaged 8,102 steps per day this week.\"\n  accessibilitySummary=\"Bar chart showing daily steps for seven days. Highest on Thursday with 11,200 steps.\"\n  min={0}\n  tickCount={4}\n>Example</Chart>"
    },
    {
      "id": "LineChart",
      "title": "Line Chart",
      "kind": "advanced",
      "props": {
        "mark": "line",
        "title": "Stock performance",
        "subtitle": "Five-year trend for AAPL.",
        "showPoints": true,
        "interactive": true
      },
      "code": "import { Chart } from '@larose-ui/react';\n\n<Chart\n  mark=\"line\"\n  title=\"Stock performance\"\n  subtitle=\"Five-year trend for AAPL.\"\n  showPoints\n  interactive\n>Example</Chart>"
    },
    {
      "id": "PointChart",
      "title": "Point Chart",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"PointChart\" for full example.",
      "composite": true
    },
    {
      "id": "StackedBar",
      "title": "Stacked Bar",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"StackedBar\" for full example.",
      "composite": true
    },
    {
      "id": "FixedRange",
      "title": "Fixed Range",
      "kind": "advanced",
      "props": {
        "mark": "line",
        "title": "Battery",
        "subtitle": "Charge level over the last 24 hours.",
        "x": "12a",
        "y": 88
      },
      "code": "import { Chart } from '@larose-ui/react';\n\n<Chart\n  mark=\"line\"\n  title=\"Battery\"\n  subtitle=\"Charge level over the last 24 hours.\"\n  x=\"12a\"\n  y={88}\n>Example</Chart>"
    }
  ],
  "Checkbox": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "label": "I agree to the terms"
      },
      "code": "import { Checkbox } from '@larose-ui/react';\n\n<Checkbox\n  label=\"I agree to the terms\"\n>Example</Checkbox>"
    },
    {
      "id": "Checked",
      "title": "Checked",
      "kind": "advanced",
      "props": {
        "label": "Subscribe to newsletter",
        "defaultChecked": true
      },
      "code": "import { Checkbox } from '@larose-ui/react';\n\n<Checkbox\n  label=\"Subscribe to newsletter\"\n  defaultChecked\n>Example</Checkbox>"
    },
    {
      "id": "WithHint",
      "title": "With Hint",
      "kind": "advanced",
      "props": {
        "label": "Send me product updates",
        "hint": "You can unsubscribe at any time"
      },
      "code": "import { Checkbox } from '@larose-ui/react';\n\n<Checkbox\n  label=\"Send me product updates\"\n  hint=\"You can unsubscribe at any time\"\n>Example</Checkbox>"
    },
    {
      "id": "WithError",
      "title": "With Error",
      "kind": "error",
      "props": {
        "label": "I agree to the terms",
        "error": "You must accept the terms to continue"
      },
      "code": "import { Checkbox } from '@larose-ui/react';\n\n<Checkbox\n  label=\"I agree to the terms\"\n  error=\"You must accept the terms to continue\"\n>Example</Checkbox>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "label": "Legacy feature access",
        "disabled": true
      },
      "code": "import { Checkbox } from '@larose-ui/react';\n\n<Checkbox\n  label=\"Legacy feature access\"\n  disabled\n>Example</Checkbox>"
    },
    {
      "id": "CheckboxDefault",
      "title": "Checkbox Default",
      "kind": "basic",
      "props": {},
      "code": "<Checkbox label=\"I agree to the terms\" hint=\"Required before submitting\" />",
      "composite": true
    }
  ],
  "CollaborationButton": [
    {
      "id": "CollaborationButtonStory",
      "title": "Collaboration Button",
      "kind": "advanced",
      "props": {},
      "code": "<CollaborationButton collaborators={collaborators} />",
      "composite": true
    }
  ],
  "CollaborationPopover": [
    {
      "id": "CollaborationPopoverStory",
      "title": "Collaboration Popover",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"CollaborationPopoverStory\" for full example.",
      "composite": true
    }
  ],
  "Collection": [
    {
      "id": "CollectionGrid",
      "title": "Collection Grid",
      "kind": "advanced",
      "props": {},
      "code": "<Collection items={photos} layout=\"grid\" columns={4} selectedId={selectedId} onSelect={(item) => setSelectedId(item.id)} />",
      "composite": true
    },
    {
      "id": "CollectionRow",
      "title": "Collection Row",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"CollectionRow\" for full example.",
      "composite": true
    }
  ],
  "ColumnView": [
    {
      "id": "ColumnViewBrowser",
      "title": "Column View Browser",
      "kind": "advanced",
      "props": {},
      "code": "<ColumnView data={hierarchy} initialPath={['icloud', 'design']} />",
      "composite": true
    }
  ],
  "CommandPalette": [
    {
      "id": "CommandPaletteDefault",
      "title": "Command Palette Default",
      "kind": "basic",
      "props": {},
      "code": "<CommandPaletteDemo />",
      "composite": true
    },
    {
      "id": "Playground",
      "title": "Playground",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Playground\" for full example.",
      "composite": true
    },
    {
      "id": "Closed",
      "title": "Closed",
      "kind": "advanced",
      "props": {
        "open": false
      },
      "code": "import { CommandPalette } from '@larose-ui/react';\n\n<CommandPalette\n  open={false}\n>Example</CommandPalette>"
    }
  ],
  "ContextMenu": [
    {
      "id": "MailMessage",
      "title": "Mail message",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MailMessage\" for full example.",
      "composite": true
    },
    {
      "id": "MultiSelectTitle",
      "title": "Multi-select title",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MultiSelectTitle\" for full example.",
      "composite": true
    },
    {
      "id": "HiddenUnavailable",
      "title": "Hidden Unavailable",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"HiddenUnavailable\" for full example.",
      "composite": true
    }
  ],
  "DataTable": [
    {
      "id": "DataTableDefault",
      "title": "Data Table Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"DataTableDefault\" for full example.",
      "composite": true
    },
    {
      "id": "DataTableLoading",
      "title": "Data Table Loading",
      "kind": "loading",
      "props": {},
      "code": "// See Storybook story \"DataTableLoading\" for full example.",
      "composite": true
    },
    {
      "id": "DataTableEmpty",
      "title": "Data Table Empty",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DataTableEmpty\" for full example.",
      "composite": true
    }
  ],
  "DatePicker": [
    {
      "id": "DatePickerDefault",
      "title": "Date Picker Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"DatePickerDefault\" for full example.",
      "composite": true
    },
    {
      "id": "DatePickerError",
      "title": "Date Picker Error",
      "kind": "error",
      "props": {},
      "code": "// See Storybook story \"DatePickerError\" for full example.",
      "composite": true
    }
  ],
  "DateRangePicker": [],
  "DateTimePicker": [],
  "Dialog": [
    {
      "id": "ConfirmDelete",
      "title": "Confirm Delete",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ConfirmDelete\" for full example.",
      "composite": true
    },
    {
      "id": "Loading",
      "title": "Loading",
      "kind": "loading",
      "props": {},
      "code": "<Dialog\n        open\n        onClose={() => undefined}\n        title=\"Saving Changes\"\n        description=\"Please wait while we save your changes.\"\n        confirmLabel=\"Save\"\n        onConfirm={() => undefined}\n        loading\n      />",
      "composite": true
    }
  ],
  "DisclosureButton": [],
  "DisclosureGroup": [
    {
      "id": "DisclosureGroupStory",
      "title": "Disclosure group",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DisclosureGroupStory\" for full example.",
      "composite": true
    }
  ],
  "DisclosureList": [
    {
      "id": "FinderStyleList",
      "title": "Finder Style List",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"FinderStyleList\" for full example.",
      "composite": true
    }
  ],
  "DisclosureTriangle": [],
  "DockBar": [],
  "DockMenu": [
    {
      "id": "SafariRunning",
      "title": "Safari (running)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SafariRunning\" for full example.",
      "composite": true
    },
    {
      "id": "MailRunning",
      "title": "Mail (running)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MailRunning\" for full example.",
      "composite": true
    },
    {
      "id": "AppNotRunning",
      "title": "App not running",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"AppNotRunning\" for full example.",
      "composite": true
    },
    {
      "id": "HomeScreenQuickActionsStory",
      "title": "Home Screen quick actions",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"HomeScreenQuickActionsStory\" for full example.",
      "composite": true
    }
  ],
  "DocumentLauncher": [
    {
      "id": "DocumentLauncherStory",
      "title": "Document Launcher Story",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DocumentLauncherStory\" for full example.",
      "composite": true
    }
  ],
  "DocumentToolbar": [
    {
      "id": "DocumentToolbarStory",
      "title": "Create & Open",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DocumentToolbarStory\" for full example.",
      "composite": true
    }
  ],
  "DRAG_START_THRESHOLD_PX": [],
  "DragDropList": [],
  "Draggable": [],
  "Drawer": [
    {
      "id": "Right",
      "title": "Right",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Right\" for full example.",
      "composite": true
    },
    {
      "id": "Left",
      "title": "Left",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Left\" for full example.",
      "composite": true
    }
  ],
  "DropZone": [],
  "EditMenu": [
    {
      "id": "CompactSelectedText",
      "title": "Compact (touch and hold)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"CompactSelectedText\" for full example.",
      "composite": true
    },
    {
      "id": "ContextPointer",
      "title": "Context menu (pointer)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ContextPointer\" for full example.",
      "composite": true
    },
    {
      "id": "AddressSelection",
      "title": "Address (contextual actions)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"AddressSelection\" for full example.",
      "composite": true
    },
    {
      "id": "NoSelection",
      "title": "No selection",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"NoSelection\" for full example.",
      "composite": true
    },
    {
      "id": "CustomFormatCommands",
      "title": "Custom format commands",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"CustomFormatCommands\" for full example.",
      "composite": true
    },
    {
      "id": "CopyStaticText",
      "title": "Copy static text",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"CopyStaticText\" for full example.",
      "composite": true
    }
  ],
  "EditMenuSelection": [],
  "EmptyState": [
    {
      "id": "NoEmployees",
      "title": "No Employees",
      "kind": "advanced",
      "props": {
        "title": "No employees found",
        "description": "Get started by creating your first employee record.",
        "actionLabel": "Add Employee"
      },
      "code": "import { EmptyState } from '@larose-ui/react';\n\n<EmptyState\n  title=\"No employees found\"\n  description=\"Get started by creating your first employee record.\"\n  actionLabel=\"Add Employee\"\n>Example</EmptyState>"
    },
    {
      "id": "Offline",
      "title": "Offline",
      "kind": "advanced",
      "props": {
        "title": "You are offline",
        "description": "Changes will sync when you reconnect.",
        "state": "offline"
      },
      "code": "import { EmptyState } from '@larose-ui/react';\n\n<EmptyState\n  title=\"You are offline\"\n  description=\"Changes will sync when you reconnect.\"\n  state=\"offline\"\n>Example</EmptyState>"
    },
    {
      "id": "Unauthorized",
      "title": "Unauthorized",
      "kind": "advanced",
      "props": {
        "title": "Access denied",
        "description": "You don't have permission to view this resource.",
        "state": "unauthorized",
        "actionLabel": "Go back"
      },
      "code": "import { EmptyState } from '@larose-ui/react';\n\n<EmptyState\n  title=\"Access denied\"\n  description=\"You don't have permission to view this resource.\"\n  state=\"unauthorized\"\n  actionLabel=\"Go back\"\n>Example</EmptyState>"
    }
  ],
  "FileBrowser": [
    {
      "id": "FileBrowserStory",
      "title": "File Browser Story",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"FileBrowserStory\" for full example.",
      "composite": true
    }
  ],
  "FilePreview": [
    {
      "id": "QuickLookPreview",
      "title": "Release Notes.md",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"QuickLookPreview\" for full example.",
      "composite": true
    }
  ],
  "FileUpload": [
    {
      "id": "FileUploadDefault",
      "title": "File Upload Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"FileUploadDefault\" for full example.",
      "composite": true
    }
  ],
  "Header": [
    {
      "id": "HeaderDefault",
      "title": "Header Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"HeaderDefault\" for full example.",
      "composite": true
    },
    {
      "id": "HeaderWithTitle",
      "title": "Header With Title",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"HeaderWithTitle\" for full example.",
      "composite": true
    },
    {
      "id": "DocumentWorkspace",
      "title": "Document Workspace",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DocumentWorkspace\" for full example.",
      "composite": true
    }
  ],
  "HeaderActions": [],
  "HeaderBrand": [],
  "HeaderTitle": [],
  "HelpButton": [],
  "HomeScreenQuickActions": [
    {
      "id": "MailActions",
      "title": "Mail",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MailActions\" for full example.",
      "composite": true
    },
    {
      "id": "MapsActions",
      "title": "Maps",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MapsActions\" for full example.",
      "composite": true
    },
    {
      "id": "DynamicMessages",
      "title": "Dynamic (Messages)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DynamicMessages\" for full example.",
      "composite": true
    },
    {
      "id": "WithoutSystemActions",
      "title": "App actions only",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"WithoutSystemActions\" for full example.",
      "composite": true
    }
  ],
  "ImageButton": [],
  "ImageOverlay": [],
  "ImageView": [
    {
      "id": "FitModes",
      "title": "Fit Modes",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"FitModes\" for full example.",
      "composite": true
    },
    {
      "id": "TextOverlay",
      "title": "Text Overlay",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"TextOverlay\" for full example.",
      "composite": true
    },
    {
      "id": "AnimatedSequence",
      "title": "Animated Sequence",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"AnimatedSequence\" for full example.",
      "composite": true
    },
    {
      "id": "ImageWellStory",
      "title": "Image Well",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ImageWellStory\" for full example.",
      "composite": true
    },
    {
      "id": "ImageButtonStory",
      "title": "Image Button",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ImageButtonStory\" for full example.",
      "composite": true
    }
  ],
  "ImageWell": [],
  "Input": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "label": "Employee Name",
        "placeholder": "Enter name"
      },
      "code": "import { Input } from '@larose-ui/react';\n\n<Input\n  label=\"Employee Name\"\n  placeholder=\"Enter name\"\n>Example</Input>"
    },
    {
      "id": "WithHint",
      "title": "With Hint",
      "kind": "advanced",
      "props": {
        "label": "Email",
        "placeholder": "username@company.com",
        "hint": "Work email address"
      },
      "code": "import { Input } from '@larose-ui/react';\n\n<Input\n  label=\"Email\"\n  placeholder=\"username@company.com\"\n  hint=\"Work email address\"\n>Example</Input>"
    },
    {
      "id": "Required",
      "title": "Required",
      "kind": "advanced",
      "props": {
        "label": "Email",
        "placeholder": "username@company.com",
        "required": true
      },
      "code": "import { Input } from '@larose-ui/react';\n\n<Input\n  label=\"Email\"\n  placeholder=\"username@company.com\"\n  required\n>Example</Input>"
    },
    {
      "id": "Validated",
      "title": "Validated",
      "kind": "advanced",
      "props": {
        "label": "Email",
        "placeholder": "username@company.com",
        "required": true,
        "validateOn": "change"
      },
      "code": "import { Input } from '@larose-ui/react';\n\n<Input\n  label=\"Email\"\n  placeholder=\"username@company.com\"\n  required\n  validateOn=\"change\"\n>Example</Input>"
    },
    {
      "id": "CurrencyFormat",
      "title": "Currency Format",
      "kind": "advanced",
      "props": {
        "label": "Salary",
        "format": "currency",
        "defaultValue": "85000",
        "hint": "Formatted when the field loses focus"
      },
      "code": "import { Input } from '@larose-ui/react';\n\n<Input\n  label=\"Salary\"\n  format=\"currency\"\n  defaultValue=\"85000\"\n  hint=\"Formatted when the field loses focus\"\n>Example</Input>"
    },
    {
      "id": "Secure",
      "title": "Secure",
      "kind": "advanced",
      "props": {},
      "code": "<SecureField label=\"Password\" required hint=\"Never prepopulated\" />",
      "composite": true
    },
    {
      "id": "Loading",
      "title": "Loading",
      "kind": "loading",
      "props": {
        "label": "Department",
        "loading": true,
        "placeholder": "Loading..."
      },
      "code": "import { Input } from '@larose-ui/react';\n\n<Input\n  label=\"Department\"\n  loading\n  placeholder=\"Loading...\"\n>Example</Input>"
    },
    {
      "id": "Error",
      "title": "Error",
      "kind": "error",
      "props": {
        "label": "Salary",
        "error": "Must be a positive number",
        "defaultValue": "-100"
      },
      "code": "import { Input } from '@larose-ui/react';\n\n<Input\n  label=\"Salary\"\n  error=\"Must be a positive number\"\n  defaultValue=\"-100\"\n>Example</Input>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "label": "Employee ID",
        "disabled": true,
        "defaultValue": "EMP-001"
      },
      "code": "import { Input } from '@larose-ui/react';\n\n<Input\n  label=\"Employee ID\"\n  disabled\n  defaultValue=\"EMP-001\"\n>Example</Input>"
    },
    {
      "id": "ReadOnly",
      "title": "Read Only",
      "kind": "advanced",
      "props": {
        "label": "Created At",
        "readOnly": true,
        "defaultValue": "2026-08-29"
      },
      "code": "import { Input } from '@larose-ui/react';\n\n<Input\n  label=\"Created At\"\n  readOnly\n  defaultValue=\"2026-08-29\"\n>Example</Input>"
    }
  ],
  "Label": [],
  "LIQUID_GLASS_OPTICS_DEFAULTS": [],
  "LIQUID_GLASS_PRESETS": [],
  "LIQUID_GLASS_SWITCH_ACTIVE_GREEN": [],
  "LIQUID_GLASS_SWITCH_TRACK_GLASS": [],
  "LiquidGlass": [
    {
      "id": "NaturalLanguageFilter",
      "title": "Natural Language Filter",
      "kind": "variants",
      "props": {},
      "code": "// See Storybook story \"NaturalLanguageFilter\" for full example.",
      "composite": true
    },
    {
      "id": "NaturalLanguagePopulate",
      "title": "Natural Language Populate",
      "kind": "variants",
      "props": {},
      "code": "<SmartFormDemo />",
      "composite": true
    },
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {},
      "code": "<RuntimeDemo />",
      "composite": true
    },
    {
      "id": "Loading",
      "title": "Loading",
      "kind": "loading",
      "props": {},
      "code": "// See Storybook story \"Loading\" for full example.",
      "composite": true
    },
    {
      "id": "Empty",
      "title": "Empty",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Empty\" for full example.",
      "composite": true
    },
    {
      "id": "SidebarDefault",
      "title": "Sidebar Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"SidebarDefault\" for full example.",
      "composite": true
    },
    {
      "id": "AppShellLayout",
      "title": "App Shell Layout",
      "kind": "advanced",
      "props": {},
      "code": "<AppShellDemo />",
      "composite": true
    },
    {
      "id": "DefaultRefined",
      "title": "Default (Apple-inspired)",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"DefaultRefined\" for full example.",
      "composite": true
    },
    {
      "id": "SmallOverrides",
      "title": "10% customization",
      "kind": "variants",
      "props": {},
      "code": "// See Storybook story \"SmallOverrides\" for full example.",
      "composite": true
    },
    {
      "id": "FullCustomTheme",
      "title": "90% customization",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"FullCustomTheme\" for full example.",
      "composite": true
    },
    {
      "id": "PaginationDefault",
      "title": "Pagination Default",
      "kind": "basic",
      "props": {},
      "code": "<PaginationDemo />",
      "composite": true
    },
    {
      "id": "Overview",
      "title": "Overview",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Overview\" for full example.",
      "composite": true
    },
    {
      "id": "TypographyScale",
      "title": "Typography Scale",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"TypographyScale\" for full example.",
      "composite": true
    },
    {
      "id": "Surfaces",
      "title": "Surfaces",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Surfaces\" for full example.",
      "composite": true
    },
    {
      "id": "ThemeComparison",
      "title": "Theme Comparison",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ThemeComparison\" for full example.",
      "composite": true
    },
    {
      "id": "RTLArabic",
      "title": "R T L Arabic",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"RTLArabic\" for full example.",
      "composite": true
    }
  ],
  "LiquidGlassButton": [
    {
      "id": "Playground",
      "title": "Playground",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Playground\" for full example.",
      "composite": true
    },
    {
      "id": "Row",
      "title": "Row",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Row\" for full example.",
      "composite": true
    },
    {
      "id": "Gallery",
      "title": "Gallery / All components",
      "kind": "variants",
      "props": {},
      "code": "// See Storybook story \"Gallery\" for full example.",
      "composite": true
    },
    {
      "id": "ShareButtonOnly",
      "title": "Share Button Only",
      "kind": "advanced",
      "props": {},
      "code": "<ShareButton />",
      "composite": true
    }
  ],
  "LiquidGlassCheckbox": [
    {
      "id": "CheckboxDefault",
      "title": "Checkbox Default",
      "kind": "basic",
      "props": {},
      "code": "<Checkbox label=\"I agree to the terms\" hint=\"Required before submitting\" />",
      "composite": true
    }
  ],
  "LiquidGlassProgress": [
    {
      "id": "ProgressDefault",
      "title": "Progress Default",
      "kind": "basic",
      "props": {},
      "code": "<Progress value={65} label=\"Profile completion\" showValue />",
      "composite": true
    },
    {
      "id": "ProgressSuccess",
      "title": "Progress Success",
      "kind": "advanced",
      "props": {},
      "code": "<Progress value={100} label=\"Upload complete\" variant=\"success\" showValue />",
      "composite": true
    }
  ],
  "LiquidGlassRange": [
    {
      "id": "DateRangePickerDefault",
      "title": "Date Range Picker Default",
      "kind": "basic",
      "props": {},
      "code": "<DateRangeDemo />",
      "composite": true
    }
  ],
  "LiquidGlassSwitch": [
    {
      "id": "SwitchDefault",
      "title": "Switch Default",
      "kind": "basic",
      "props": {},
      "code": "<Switch label=\"Email notifications\" defaultChecked hint=\"Receive product updates\" />",
      "composite": true
    }
  ],
  "LiquidGlassTabBar": [
    {
      "id": "Playground",
      "title": "Playground",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Playground\" for full example.",
      "composite": true
    },
    {
      "id": "IconsOnly",
      "title": "Icons Only",
      "kind": "with-icon",
      "props": {
        "tabPreset": "iconsOnly",
        "height": 60,
        "maxWidth": 340
      },
      "code": "import { LiquidGlassTabBar } from '@larose-ui/react';\n\n<LiquidGlassTabBar\n  tabPreset=\"iconsOnly\"\n  height={60}\n  maxWidth={340}\n>Example</LiquidGlassTabBar>"
    },
    {
      "id": "WithBadges",
      "title": "With Badges",
      "kind": "advanced",
      "props": {
        "tabPreset": "badges",
        "defaultActiveKey": "notifs"
      },
      "code": "import { LiquidGlassTabBar } from '@larose-ui/react';\n\n<LiquidGlassTabBar\n  tabPreset=\"badges\"\n  defaultActiveKey=\"notifs\"\n>Example</LiquidGlassTabBar>"
    },
    {
      "id": "StrongRefraction",
      "title": "Strong Refraction",
      "kind": "advanced",
      "props": {
        "displacementScale": 60,
        "bezelWidth": 32,
        "refractionStrength": 1.4,
        "specularTopOpacity": 0.95,
        "blur": 22
      },
      "code": "import { LiquidGlassTabBar } from '@larose-ui/react';\n\n<LiquidGlassTabBar\n  displacementScale={60}\n  bezelWidth={32}\n  refractionStrength={1.4}\n  specularTopOpacity={0.95}\n  blur={22}\n>Example</LiquidGlassTabBar>"
    },
    {
      "id": "Subtle",
      "title": "Subtle",
      "kind": "advanced",
      "props": {
        "displacementScale": 18,
        "bezelWidth": 12,
        "refractionStrength": 0.6,
        "specularTopOpacity": 0.45,
        "specularEdgeOpacity": 0.25,
        "innerTopHighlight": 0.18,
        "innerBottomShadow": 0.1,
        "shadowIntensity": 0.6,
        "tint": "rgba(255,255,255,0.07)",
        "tintFallback": "rgba(255,255,255,0.10)"
      },
      "code": "import { LiquidGlassTabBar } from '@larose-ui/react';\n\n<LiquidGlassTabBar\n  displacementScale={18}\n  bezelWidth={12}\n  refractionStrength={0.6}\n  specularTopOpacity={0.45}\n  specularEdgeOpacity={0.25}\n  innerTopHighlight={0.18}\n  innerBottomShadow={0.1}\n  shadowIntensity={0.6}\n  tint=\"rgba(255,255,255,0.07)\"\n  tintFallback=\"rgba(255,255,255,0.10)\"\n>Example</LiquidGlassTabBar>"
    },
    {
      "id": "NoIndicator",
      "title": "No Indicator",
      "kind": "advanced",
      "props": {
        "showIndicator": false,
        "inactiveColor": "rgba(255,255,255,0.45)"
      },
      "code": "import { LiquidGlassTabBar } from '@larose-ui/react';\n\n<LiquidGlassTabBar\n  showIndicator={false}\n  inactiveColor=\"rgba(255,255,255,0.45)\"\n>Example</LiquidGlassTabBar>"
    }
  ],
  "LiquidGlassTopBar": [
    {
      "id": "Playground",
      "title": "Playground",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Playground\" for full example.",
      "composite": true
    },
    {
      "id": "Edge",
      "title": "Edge",
      "kind": "advanced",
      "props": {
        "variant": "edge",
        "insetX": 0,
        "top": 0,
        "borderRadius": 0
      },
      "code": "import { LiquidGlassTopBar } from '@larose-ui/react';\n\n<LiquidGlassTopBar\n  variant=\"edge\"\n  insetX={0}\n  top={0}\n  borderRadius={0}\n>Example</LiquidGlassTopBar>"
    },
    {
      "id": "NoTrailing",
      "title": "No Trailing",
      "kind": "advanced",
      "props": {
        "showTrailing": false
      },
      "code": "import { LiquidGlassTopBar } from '@larose-ui/react';\n\n<LiquidGlassTopBar\n  showTrailing={false}\n>Example</LiquidGlassTopBar>"
    },
    {
      "id": "StrongRefraction",
      "title": "Strong Refraction",
      "kind": "advanced",
      "props": {
        "displacementScale": 50,
        "bezelWidth": 28,
        "specularTopOpacity": 0.95,
        "refractionStrength": 1.2
      },
      "code": "import { LiquidGlassTopBar } from '@larose-ui/react';\n\n<LiquidGlassTopBar\n  displacementScale={50}\n  bezelWidth={28}\n  specularTopOpacity={0.95}\n  refractionStrength={1.2}\n>Example</LiquidGlassTopBar>"
    }
  ],
  "List": [
    {
      "id": "GroupedList",
      "title": "Grouped List",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"GroupedList\" for full example.",
      "composite": true
    },
    {
      "id": "MiddleTruncation",
      "title": "Middle Truncation",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MiddleTruncation\" for full example.",
      "composite": true
    }
  ],
  "ListRow": [],
  "ListSection": [],
  "Lockup": [
    {
      "id": "Overview",
      "title": "Overview",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Overview\" for full example.",
      "composite": true
    },
    {
      "id": "CaptionButtonGrid",
      "title": "Caption Button Grid",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"CaptionButtonGrid\" for full example.",
      "composite": true
    },
    {
      "id": "VerticalMonograms",
      "title": "Vertical Monograms",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"VerticalMonograms\" for full example.",
      "composite": true
    }
  ],
  "LockupCard": [],
  "LockupRow": [],
  "Menu": [
    {
      "id": "LargeLayout",
      "title": "Large (default)",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"LargeLayout\" for full example.",
      "composite": true
    },
    {
      "id": "MediumLayout",
      "title": "Medium layout",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MediumLayout\" for full example.",
      "composite": true
    },
    {
      "id": "SmallLayout",
      "title": "Small layout",
      "kind": "variants",
      "props": {},
      "code": "<Menu layout=\"small\" open onOpenChange={() => undefined} entries={formatEntries} />",
      "composite": true
    },
    {
      "id": "SubmenuAndToggles",
      "title": "Submenus and toggles",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SubmenuAndToggles\" for full example.",
      "composite": true
    },
    {
      "id": "UnavailableItems",
      "title": "Unavailable items",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"UnavailableItems\" for full example.",
      "composite": true
    }
  ],
  "MenuBar": [
    {
      "id": "MenuBarGlobalShortcuts",
      "title": "Menu bar (global shortcuts)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MenuBarGlobalShortcuts\" for full example.",
      "composite": true
    },
    {
      "id": "MacOSStandard",
      "title": "macOS standard menus",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MacOSStandard\" for full example.",
      "composite": true
    },
    {
      "id": "IPadOSHiddenUntilRevealed",
      "title": "iPadOS reveal at top edge",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"IPadOSHiddenUntilRevealed\" for full example.",
      "composite": true
    },
    {
      "id": "DisabledNotHidden",
      "title": "Unavailable items stay visible",
      "kind": "disabled",
      "props": {},
      "code": "// See Storybook story \"DisabledNotHidden\" for full example.",
      "composite": true
    }
  ],
  "MenuBarExtra": [],
  "MnemonicLabel": [],
  "Modal": [
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"Default\" for full example.",
      "composite": true
    },
    {
      "id": "WithoutDescription",
      "title": "Without Description",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"WithoutDescription\" for full example.",
      "composite": true
    },
    {
      "id": "NoOverlayClose",
      "title": "No Overlay Close",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"NoOverlayClose\" for full example.",
      "composite": true
    }
  ],
  "Monogram": [],
  "MorePullDownButton": [],
  "Ornament": [
    {
      "id": "NowPlaying",
      "title": "Now Playing (bottom)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"NowPlaying\" for full example.",
      "composite": true
    },
    {
      "id": "ImmersiveHidden",
      "title": "Hidden during immersive content",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ImmersiveHidden\" for full example.",
      "composite": true
    },
    {
      "id": "TopToolbar",
      "title": "Top toolbar ornament",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"TopToolbar\" for full example.",
      "composite": true
    }
  ],
  "OrnamentButton": [],
  "OrnamentWindow": [],
  "OutlineView": [
    {
      "id": "OutlineViewStory",
      "title": "Outline view (legacy)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"OutlineViewStory\" for full example.",
      "composite": true
    },
    {
      "id": "FinderStyle",
      "title": "Finder-style outline",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"FinderStyle\" for full example.",
      "composite": true
    },
    {
      "id": "SplitViewCompanion",
      "title": "Split view companion",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SplitViewCompanion\" for full example.",
      "composite": true
    },
    {
      "id": "BasicOutline",
      "title": "Basic Outline",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"BasicOutline\" for full example.",
      "composite": true
    }
  ],
  "OutlineViewToolbar": [],
  "Pagination": [],
  "PathControl": [
    {
      "id": "PathControlStandard",
      "title": "Path control (standard)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"PathControlStandard\" for full example.",
      "composite": true
    },
    {
      "id": "PathControlPopup",
      "title": "Path control (pop-up)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"PathControlPopup\" for full example.",
      "composite": true
    }
  ],
  "Picker": [
    {
      "id": "WheelStyle",
      "title": "Wheels (multipart)",
      "kind": "advanced",
      "props": {},
      "code": "<Picker\n        label=\"Country\"\n        style=\"wheels\"\n        columns={[{ id: 'country', label: 'Country', options: countries }]}\n        value={value}\n        onChange={setValue}\n      />",
      "composite": true
    },
    {
      "id": "CompactStyle",
      "title": "Compact (popover)",
      "kind": "advanced",
      "props": {},
      "code": "<Picker\n        label=\"Country\"\n        style=\"compact\"\n        columns={[{ id: 'country', label: 'Country', options: countries }]}\n        value={value}\n        onChange={setValue}\n      />",
      "composite": true
    },
    {
      "id": "DateWheels",
      "title": "Date (wheels)",
      "kind": "advanced",
      "props": {},
      "code": "<DateTimePicker\n        label=\"Due date\"\n        mode=\"date\"\n        style=\"wheels\"\n        value={value}\n        onChange={setValue}\n      />",
      "composite": true
    },
    {
      "id": "DateCompact",
      "title": "Date (compact calendar)",
      "kind": "advanced",
      "props": {},
      "code": "<DateTimePicker\n        label=\"Event date\"\n        mode=\"date\"\n        style=\"compact\"\n        value={value}\n        onChange={setValue}\n      />",
      "composite": true
    },
    {
      "id": "DateInline",
      "title": "Date (inline calendar)",
      "kind": "advanced",
      "props": {},
      "code": "<DateTimePicker\n        label=\"Trip date\"\n        mode=\"date\"\n        style=\"inline\"\n        value={value}\n        onChange={setValue}\n      />",
      "composite": true
    },
    {
      "id": "TimeWheels",
      "title": "Time (wheels)",
      "kind": "advanced",
      "props": {},
      "code": "<DateTimePicker\n        label=\"Meeting time\"\n        mode=\"time\"\n        style=\"wheels\"\n        minuteInterval={15}\n        value={value}\n        onChange={setValue}\n      />",
      "composite": true
    },
    {
      "id": "DateAndTimeCompact",
      "title": "Date and time (compact)",
      "kind": "advanced",
      "props": {},
      "code": "<DateTimePicker\n        label=\"Appointment\"\n        mode=\"datetime\"\n        style=\"compact\"\n        minuteInterval={5}\n        value={value}\n        onChange={setValue}\n      />",
      "composite": true
    },
    {
      "id": "CountdownTimer",
      "title": "Countdown timer",
      "kind": "advanced",
      "props": {},
      "code": "<DateTimePicker\n        label=\"Timer\"\n        mode=\"countdown\"\n        style=\"wheels\"\n        minuteInterval={1}\n        value={value}\n        onChange={setValue}\n      />",
      "composite": true
    },
    {
      "id": "LowLevelWheelPicker",
      "title": "WheelPicker (low-level)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"LowLevelWheelPicker\" for full example.",
      "composite": true
    }
  ],
  "Popover": [
    {
      "id": "PopoverAndTooltip",
      "title": "Popover And Tooltip",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"PopoverAndTooltip\" for full example.",
      "composite": true
    },
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "margin": 0,
        "maxWidth": 220
      },
      "code": "import { Popover } from '@larose-ui/react';\n\n<Popover\n  margin={0}\n  maxWidth={220}\n>Example</Popover>"
    },
    {
      "id": "Top",
      "title": "Top",
      "kind": "advanced",
      "props": {
        "side": "top",
        "margin": 0
      },
      "code": "import { Popover } from '@larose-ui/react';\n\n<Popover\n  side=\"top\"\n  margin={0}\n>Example</Popover>"
    },
    {
      "id": "WithActions",
      "title": "With Actions",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"WithActions\" for full example.",
      "composite": true
    }
  ],
  "PopUpButton": [
    {
      "id": "CalendarRepeat",
      "title": "Calendar repeat",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"CalendarRepeat\" for full example.",
      "composite": true
    },
    {
      "id": "WithDefault",
      "title": "Default selection",
      "kind": "basic",
      "props": {},
      "code": "<PopUpButton\n        label=\"Priority\"\n        options={[\n          { value: 'low', label: 'Low' },\n          { value: 'medium', label: 'Medium' },\n          { value: 'high', label: 'High' },\n        ]}\n        defaultValue=\"medium\"\n      />",
      "composite": true
    },
    {
      "id": "DisabledOption",
      "title": "Unavailable option",
      "kind": "disabled",
      "props": {},
      "code": "// See Storybook story \"DisabledOption\" for full example.",
      "composite": true
    }
  ],
  "Poster": [],
  "Progress": [
    {
      "id": "ProgressDefault",
      "title": "Progress Default",
      "kind": "basic",
      "props": {},
      "code": "<Progress value={65} label=\"Profile completion\" showValue />",
      "composite": true
    },
    {
      "id": "ProgressSuccess",
      "title": "Progress Success",
      "kind": "advanced",
      "props": {},
      "code": "<Progress value={100} label=\"Upload complete\" variant=\"success\" showValue />",
      "composite": true
    },
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "value": 65,
        "label": "Profile completion",
        "showValue": true
      },
      "code": "import { Progress } from '@larose-ui/react';\n\n<Progress\n  value={65}\n  label=\"Profile completion\"\n  showValue\n/>"
    },
    {
      "id": "Success",
      "title": "Success",
      "kind": "advanced",
      "props": {
        "value": 100,
        "label": "Upload complete",
        "variant": "success",
        "showValue": true
      },
      "code": "import { Progress } from '@larose-ui/react';\n\n<Progress\n  value={100}\n  label=\"Upload complete\"\n  variant=\"success\"\n  showValue\n/>"
    },
    {
      "id": "Error",
      "title": "Error",
      "kind": "error",
      "props": {
        "value": 35,
        "label": "Sync failed",
        "variant": "error",
        "showValue": true
      },
      "code": "import { Progress } from '@larose-ui/react';\n\n<Progress\n  value={35}\n  label=\"Sync failed\"\n  variant=\"error\"\n  showValue\n/>"
    },
    {
      "id": "Loading",
      "title": "Loading",
      "kind": "loading",
      "props": {
        "value": 45,
        "label": "Importing employees",
        "showValue": true,
        "state": "loading"
      },
      "code": "import { Progress } from '@larose-ui/react';\n\n<Progress\n  value={45}\n  label=\"Importing employees\"\n  showValue\n  state=\"loading\"\n/>"
    }
  ],
  "PullDownButton": [
    {
      "id": "AddMenu",
      "title": "Add",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"AddMenu\" for full example.",
      "composite": true
    },
    {
      "id": "SortMenu",
      "title": "Sort",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SortMenu\" for full example.",
      "composite": true
    },
    {
      "id": "MoreMenu",
      "title": "More (Notes)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MoreMenu\" for full example.",
      "composite": true
    },
    {
      "id": "DestructiveConfirmation",
      "title": "Destructive confirmation",
      "kind": "destructive",
      "props": {},
      "code": "// See Storybook story \"DestructiveConfirmation\" for full example.",
      "composite": true
    }
  ],
  "Radio": [
    {
      "id": "RadioGroup",
      "title": "Radio Group",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"RadioGroup\" for full example.",
      "composite": true
    },
    {
      "id": "Default",
      "title": "plan",
      "kind": "basic",
      "props": {
        "name": "plan",
        "label": "Starter plan",
        "value": "starter",
        "defaultChecked": true
      },
      "code": "import { Radio } from '@larose-ui/react';\n\n<Radio\n  name=\"plan\"\n  label=\"Starter plan\"\n  value=\"starter\"\n  defaultChecked\n>Example</Radio>"
    },
    {
      "id": "WithHint",
      "title": "plan",
      "kind": "advanced",
      "props": {
        "name": "plan",
        "label": "Pro plan",
        "value": "pro",
        "hint": "Includes advanced analytics"
      },
      "code": "import { Radio } from '@larose-ui/react';\n\n<Radio\n  name=\"plan\"\n  label=\"Pro plan\"\n  value=\"pro\"\n  hint=\"Includes advanced analytics\"\n>Example</Radio>"
    },
    {
      "id": "WithError",
      "title": "plan",
      "kind": "error",
      "props": {
        "name": "plan",
        "label": "Enterprise plan",
        "value": "enterprise",
        "error": "Select a plan to continue"
      },
      "code": "import { Radio } from '@larose-ui/react';\n\n<Radio\n  name=\"plan\"\n  label=\"Enterprise plan\"\n  value=\"enterprise\"\n  error=\"Select a plan to continue\"\n>Example</Radio>"
    },
    {
      "id": "Disabled",
      "title": "plan",
      "kind": "disabled",
      "props": {
        "name": "plan",
        "label": "Legacy plan",
        "value": "legacy",
        "disabled": true
      },
      "code": "import { Radio } from '@larose-ui/react';\n\n<Radio\n  name=\"plan\"\n  label=\"Legacy plan\"\n  value=\"legacy\"\n  disabled\n>Example</Radio>"
    },
    {
      "id": "Group",
      "title": "Group",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Group\" for full example.",
      "composite": true
    }
  ],
  "SecureField": [],
  "Select": [
    {
      "id": "SelectDefault",
      "title": "Select Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"SelectDefault\" for full example.",
      "composite": true
    },
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "label": "Department",
        "placeholder": "Choose a department"
      },
      "code": "import { Select } from '@larose-ui/react';\n\n<Select\n  label=\"Department\"\n  placeholder=\"Choose a department\"\n>Example</Select>"
    },
    {
      "id": "WithHint",
      "title": "With Hint",
      "kind": "advanced",
      "props": {
        "label": "Department",
        "hint": "Used for org chart and permissions"
      },
      "code": "import { Select } from '@larose-ui/react';\n\n<Select\n  label=\"Department\"\n  hint=\"Used for org chart and permissions\"\n>Example</Select>"
    },
    {
      "id": "Required",
      "title": "Required",
      "kind": "advanced",
      "props": {
        "label": "Department",
        "required": true
      },
      "code": "import { Select } from '@larose-ui/react';\n\n<Select\n  label=\"Department\"\n  required\n>Example</Select>"
    },
    {
      "id": "Loading",
      "title": "Loading",
      "kind": "loading",
      "props": {
        "label": "Department",
        "loading": true
      },
      "code": "import { Select } from '@larose-ui/react';\n\n<Select\n  label=\"Department\"\n  loading\n>Example</Select>"
    },
    {
      "id": "WithError",
      "title": "With Error",
      "kind": "error",
      "props": {
        "label": "Department",
        "error": "Department is required"
      },
      "code": "import { Select } from '@larose-ui/react';\n\n<Select\n  label=\"Department\"\n  error=\"Department is required\"\n>Example</Select>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "label": "Department",
        "disabled": true,
        "defaultValue": "eng"
      },
      "code": "import { Select } from '@larose-ui/react';\n\n<Select\n  label=\"Department\"\n  disabled\n  defaultValue=\"eng\"\n>Example</Select>"
    }
  ],
  "Skeleton": [
    {
      "id": "Text",
      "title": "Text",
      "kind": "advanced",
      "props": {
        "width": 200
      },
      "code": "import { Skeleton } from '@larose-ui/react';\n\n<Skeleton\n  width={200}\n/>"
    }
  ],
  "Spinner": [],
  "SplitView": [
    {
      "id": "SidebarDetailInspector",
      "title": "Sidebar · content · inspector",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SidebarDetailInspector\" for full example.",
      "composite": true
    },
    {
      "id": "VerticalSplit",
      "title": "Vertical Split",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"VerticalSplit\" for full example.",
      "composite": true
    },
    {
      "id": "DragBetweenPanes",
      "title": "Drag between panes",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"DragBetweenPanes\" for full example.",
      "composite": true
    },
    {
      "id": "CompactStack",
      "title": "Compact Stack",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"CompactStack\" for full example.",
      "composite": true
    }
  ],
  "SplitViewPane": [],
  "SplitViewToolbar": [],
  "SquareButton": [],
  "Switch": [
    {
      "id": "SwitchDefault",
      "title": "Switch Default",
      "kind": "basic",
      "props": {},
      "code": "<Switch label=\"Email notifications\" defaultChecked hint=\"Receive product updates\" />",
      "composite": true
    },
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "label": "Email notifications"
      },
      "code": "import { Switch } from '@larose-ui/react';\n\n<Switch\n  label=\"Email notifications\"\n>Example</Switch>"
    },
    {
      "id": "Checked",
      "title": "Checked",
      "kind": "advanced",
      "props": {
        "label": "Push notifications",
        "defaultChecked": true
      },
      "code": "import { Switch } from '@larose-ui/react';\n\n<Switch\n  label=\"Push notifications\"\n  defaultChecked\n>Example</Switch>"
    },
    {
      "id": "WithHint",
      "title": "With Hint",
      "kind": "advanced",
      "props": {
        "label": "Marketing emails",
        "hint": "Receive occasional product announcements"
      },
      "code": "import { Switch } from '@larose-ui/react';\n\n<Switch\n  label=\"Marketing emails\"\n  hint=\"Receive occasional product announcements\"\n>Example</Switch>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "label": "Beta features",
        "disabled": true
      },
      "code": "import { Switch } from '@larose-ui/react';\n\n<Switch\n  label=\"Beta features\"\n  disabled\n>Example</Switch>"
    },
    {
      "id": "SettingsStyle",
      "title": "Settings Style",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SettingsStyle\" for full example.",
      "composite": true
    }
  ],
  "SYSTEM_ACTIVITY_IDS": [],
  "Table": [
    {
      "id": "SortableTable",
      "title": "Sortable Table",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SortableTable\" for full example.",
      "composite": true
    }
  ],
  "Tabs": [
    {
      "id": "TabsDefault",
      "title": "Tabs Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"TabsDefault\" for full example.",
      "composite": true
    }
  ],
  "TabsList": [],
  "TabsPanel": [],
  "TabsTrigger": [],
  "TabView": [
    {
      "id": "Bordered",
      "title": "Bordered",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Bordered\" for full example.",
      "composite": true
    },
    {
      "id": "Bezeled",
      "title": "Bezeled",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"Bezeled\" for full example.",
      "composite": true
    },
    {
      "id": "BorderlessHiddenTabs",
      "title": "Borderless with hidden tabs",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"BorderlessHiddenTabs\" for full example.",
      "composite": true
    },
    {
      "id": "SixTabLimit",
      "title": "Six tab guidance",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SixTabLimit\" for full example.",
      "composite": true
    }
  ],
  "TabViewList": [],
  "TabViewPanel": [],
  "TabViewTab": [],
  "Textarea": [
    {
      "id": "TextareaDefault",
      "title": "Textarea Default",
      "kind": "basic",
      "props": {},
      "code": "<Textarea label=\"Description\" placeholder=\"Enter details...\" />",
      "composite": true
    },
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "label": "Description",
        "placeholder": "Enter details..."
      },
      "code": "import { Textarea } from '@larose-ui/react';\n\n<Textarea\n  label=\"Description\"\n  placeholder=\"Enter details...\"\n>Example</Textarea>"
    },
    {
      "id": "WithHint",
      "title": "With Hint",
      "kind": "advanced",
      "props": {
        "label": "Notes",
        "placeholder": "Add internal notes",
        "hint": "Visible to admins only"
      },
      "code": "import { Textarea } from '@larose-ui/react';\n\n<Textarea\n  label=\"Notes\"\n  placeholder=\"Add internal notes\"\n  hint=\"Visible to admins only\"\n>Example</Textarea>"
    },
    {
      "id": "Required",
      "title": "Required",
      "kind": "advanced",
      "props": {
        "label": "Feedback",
        "placeholder": "Tell us what you think",
        "required": true
      },
      "code": "import { Textarea } from '@larose-ui/react';\n\n<Textarea\n  label=\"Feedback\"\n  placeholder=\"Tell us what you think\"\n  required\n>Example</Textarea>"
    },
    {
      "id": "WithError",
      "title": "With Error",
      "kind": "error",
      "props": {
        "label": "Description",
        "defaultValue": "Too short",
        "error": "Description must be at least 20 characters"
      },
      "code": "import { Textarea } from '@larose-ui/react';\n\n<Textarea\n  label=\"Description\"\n  defaultValue=\"Too short\"\n  error=\"Description must be at least 20 characters\"\n>Example</Textarea>"
    },
    {
      "id": "Disabled",
      "title": "Disabled",
      "kind": "disabled",
      "props": {
        "label": "Archived notes",
        "defaultValue": "This record is read-only.",
        "disabled": true
      },
      "code": "import { Textarea } from '@larose-ui/react';\n\n<Textarea\n  label=\"Archived notes\"\n  defaultValue=\"This record is read-only.\"\n  disabled\n>Example</Textarea>"
    }
  ],
  "TextView": [
    {
      "id": "ReadOnlySelectable",
      "title": "Read Only Selectable",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ReadOnlySelectable\" for full example.",
      "composite": true
    },
    {
      "id": "Editable",
      "title": "Editable",
      "kind": "advanced",
      "props": {},
      "code": "<Card title=\"Editable text view\" padding=\"md\">\n        <TextView\n          editable\n          value={value}\n          onChange={(event) => setValue(event.target.value)}\n          maxHeight=\"14rem\"\n          inputMode=\"text\"\n        />\n      </Card>",
      "composite": true
    },
    {
      "id": "RichDisplay",
      "title": "Rich Display",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"RichDisplay\" for full example.",
      "composite": true
    }
  ],
  "ThemeCustomizationContext": [],
  "TimePicker": [
    {
      "id": "TimePickerDefault",
      "title": "Time Picker Default",
      "kind": "basic",
      "props": {},
      "code": "<TimePicker label=\"Meeting time\" value=\"09:30\" />",
      "composite": true
    }
  ],
  "TokenField": [
    {
      "id": "TokenFieldMail",
      "title": "Token field (macOS Mail)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"TokenFieldMail\" for full example.",
      "composite": true
    }
  ],
  "Toolbar": [
    {
      "id": "MacNotesStyle",
      "title": "macOS Notes (standard + More)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MacNotesStyle\" for full example.",
      "composite": true
    },
    {
      "id": "IOSMailNavigation",
      "title": "iOS navigation bar",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"IOSMailNavigation\" for full example.",
      "composite": true
    },
    {
      "id": "VisionOSBottomBar",
      "title": "visionOS bottom toolbar",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"VisionOSBottomBar\" for full example.",
      "composite": true
    },
    {
      "id": "TrailingProminentAction",
      "title": "Primary Done action",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"TrailingProminentAction\" for full example.",
      "composite": true
    },
    {
      "id": "SeparateTextAndSymbolGroups",
      "title": "Separate text and symbol buttons",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"SeparateTextAndSymbolGroups\" for full example.",
      "composite": true
    }
  ],
  "ToolbarBackButton": [],
  "ToolbarCloseButton": [],
  "ToolbarDocumentMenu": [],
  "ToolbarFixedSpace": [],
  "ToolbarGroup": [],
  "ToolbarItem": [],
  "ToolbarMoreButton": [],
  "ToolbarProminentButton": [],
  "ToolbarSearch": [],
  "ToolbarSection": [],
  "ToolbarTitle": [],
  "Tooltip": [
    {
      "id": "TooltipDefault",
      "title": "Tooltip Default",
      "kind": "basic",
      "props": {},
      "code": "// See Storybook story \"TooltipDefault\" for full example.",
      "composite": true
    },
    {
      "id": "Default",
      "title": "Default",
      "kind": "basic",
      "props": {
        "content": "Export employees as CSV"
      },
      "code": "import { Tooltip } from '@larose-ui/react';\n\n<Tooltip\n  content=\"Export employees as CSV\"\n>Example</Tooltip>"
    },
    {
      "id": "OnText",
      "title": "On Text",
      "kind": "advanced",
      "props": {
        "content": "Last updated 2 hours ago",
        "textDecoration": "underline dotted"
      },
      "code": "import { Tooltip } from '@larose-ui/react';\n\n<Tooltip\n  content=\"Last updated 2 hours ago\"\n  textDecoration=\"underline dotted\"\n>Example</Tooltip>"
    },
    {
      "id": "LongContent",
      "title": "Long Content",
      "kind": "advanced",
      "props": {
        "content": "Keyboard shortcut: ⌘ + Shift + E"
      },
      "code": "import { Tooltip } from '@larose-ui/react';\n\n<Tooltip\n  content=\"Keyboard shortcut: ⌘ + Shift + E\"\n>Example</Tooltip>"
    }
  ],
  "Typography": [
    {
      "id": "ShortcutLab",
      "title": "Shortcut lab",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"ShortcutLab\" for full example.",
      "composite": true
    },
    {
      "id": "MenuAlwaysOpen",
      "title": "Menu (always open)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"MenuAlwaysOpen\" for full example.",
      "composite": true
    }
  ],
  "UnsavedIndicator": [],
  "WebView": [
    {
      "id": "EmbeddedHtml",
      "title": "Embedded HTML (Mail-style)",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"EmbeddedHtml\" for full example.",
      "composite": true
    },
    {
      "id": "BriefWebsiteAccess",
      "title": "Brief Website Access",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"BriefWebsiteAccess\" for full example.",
      "composite": true
    },
    {
      "id": "WithNavigation",
      "title": "With Navigation",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"WithNavigation\" for full example.",
      "composite": true
    },
    {
      "id": "NavigationOnly",
      "title": "Navigation Only",
      "kind": "advanced",
      "props": {},
      "code": "// See Storybook story \"NavigationOnly\" for full example.",
      "composite": true
    }
  ],
  "WebViewNavigation": [],
  "WebViewShell": [],
  "WheelColumn": [],
  "WheelPicker": []
};

export function getComponentExamples(name: string): DocsExampleEntry[] {
  return docsExamples[name] ?? [];
}
