// Generated by scripts/generate-docs-catalog.mjs — do not edit manually.

export type PlaygroundControlType = 'boolean' | 'select' | 'text' | 'number';

export interface PlaygroundControl {
  control: PlaygroundControlType;
  default?: string | number | boolean;
  options?: string[];
  label?: string;
  min?: number;
  max?: number;
}

export const playgroundControls: Record<string, Record<string, PlaygroundControl>> = {
  "Button": {
    "children": {
      "control": "text",
      "default": "Save changes",
      "label": "Label"
    },
    "variant": {
      "control": "select",
      "options": [
        "primary",
        "secondary",
        "outline",
        "ghost",
        "destructive"
      ],
      "default": "primary"
    },
    "size": {
      "control": "select",
      "options": [
        "sm",
        "md",
        "lg"
      ],
      "default": "md"
    },
    "shape": {
      "control": "select",
      "options": [
        "capsule",
        "circle",
        "roundedRect"
      ],
      "default": "capsule"
    },
    "buttonRole": {
      "control": "select",
      "options": [
        "normal",
        "primary",
        "cancel",
        "destructive"
      ],
      "default": "normal"
    },
    "disabled": {
      "control": "boolean",
      "default": false
    },
    "loading": {
      "control": "boolean",
      "default": false
    },
    "fullWidth": {
      "control": "boolean",
      "default": false
    },
    "iconOnly": {
      "control": "boolean",
      "default": false
    }
  },
  "Input": {
    "label": {
      "control": "text",
      "default": "Email",
      "label": "Label"
    },
    "placeholder": {
      "control": "text",
      "default": "you@company.com"
    },
    "inputSize": {
      "control": "select",
      "options": [
        "sm",
        "md",
        "lg"
      ],
      "default": "md"
    },
    "required": {
      "control": "boolean",
      "default": false
    },
    "disabled": {
      "control": "boolean",
      "default": false
    },
    "error": {
      "control": "text",
      "default": ""
    }
  },
  "Badge": {
    "children": {
      "control": "text",
      "default": "Beta",
      "label": "Label"
    },
    "variant": {
      "control": "select",
      "options": [
        "default",
        "info",
        "success",
        "warning",
        "error"
      ],
      "default": "info"
    }
  },
  "Checkbox": {
    "label": {
      "control": "text",
      "default": "Accept terms"
    },
    "checked": {
      "control": "boolean",
      "default": false
    },
    "disabled": {
      "control": "boolean",
      "default": false
    }
  },
  "Switch": {
    "label": {
      "control": "text",
      "default": "Notifications"
    },
    "checked": {
      "control": "boolean",
      "default": true
    },
    "disabled": {
      "control": "boolean",
      "default": false
    }
  },
  "Progress": {
    "value": {
      "control": "number",
      "default": 65,
      "min": 0,
      "max": 100
    },
    "variant": {
      "control": "select",
      "options": [
        "default",
        "success",
        "warning",
        "error"
      ],
      "default": "default"
    }
  },
  "Alert": {
    "children": {
      "control": "text",
      "default": "Your changes were saved.",
      "label": "Message"
    },
    "variant": {
      "control": "select",
      "options": [
        "info",
        "success",
        "warning",
        "error"
      ],
      "default": "info"
    }
  },
  "Card": {
    "title": {
      "control": "text",
      "default": "Employee profile"
    },
    "padding": {
      "control": "select",
      "options": [
        "none",
        "sm",
        "md",
        "lg"
      ],
      "default": "md"
    }
  },
  "Select": {
    "label": {
      "control": "text",
      "default": "Department"
    },
    "placeholder": {
      "control": "text",
      "default": "Choose department"
    },
    "disabled": {
      "control": "boolean",
      "default": false
    }
  },
  "Typography": {
    "children": {
      "control": "text",
      "default": "Refined typography",
      "label": "Text"
    },
    "role": {
      "control": "select",
      "options": [
        "body",
        "headline",
        "title",
        "subheadline",
        "footnote",
        "caption"
      ],
      "default": "body"
    },
    "muted": {
      "control": "boolean",
      "default": false
    }
  },
  "Textarea": {
    "label": {
      "control": "text",
      "default": "Description"
    },
    "placeholder": {
      "control": "text",
      "default": "Enter details..."
    },
    "disabled": {
      "control": "boolean",
      "default": false
    }
  },
  "Radio": {
    "label": {
      "control": "text",
      "default": "Starter plan"
    },
    "checked": {
      "control": "boolean",
      "default": true
    },
    "disabled": {
      "control": "boolean",
      "default": false
    }
  },
  "LiquidGlassButton": {
    "children": {
      "control": "text",
      "default": "Continue",
      "label": "Label"
    },
    "disabled": {
      "control": "boolean",
      "default": false
    }
  },
  "LiquidGlassSwitch": {
    "defaultChecked": {
      "control": "boolean",
      "default": false
    },
    "disabled": {
      "control": "boolean",
      "default": false
    }
  },
  "LiquidGlassProgress": {
    "value": {
      "control": "number",
      "default": 62,
      "min": 0,
      "max": 100
    },
    "indeterminate": {
      "control": "boolean",
      "default": false
    }
  },
  "LiquidGlassRange": {
    "defaultValue": {
      "control": "number",
      "default": 50,
      "min": 0,
      "max": 100
    },
    "disabled": {
      "control": "boolean",
      "default": false
    }
  },
  "LiquidGlassCheckbox": {
    "label": {
      "control": "text",
      "default": "Enable liquid glass"
    },
    "defaultChecked": {
      "control": "boolean",
      "default": true
    },
    "disabled": {
      "control": "boolean",
      "default": false
    }
  },
  "Spinner": {
    "label": {
      "control": "text",
      "default": "Loading"
    },
    "size": {
      "control": "select",
      "options": [
        "sm",
        "md",
        "lg"
      ],
      "default": "md"
    }
  }
};

export interface ComponentAnatomy {
  summary: string;
  structure: string[];
  composition: string;
  slots: string[];
  states: string[];
}

export const componentAnatomy: Record<string, ComponentAnatomy> = {
  "Modal": {
    "summary": "Modal renders a portal overlay with focus trap and optional title/description.",
    "structure": [
      "Modal (root portal)",
      "Overlay",
      "Content",
      "Title",
      "Description",
      "Body (children)"
    ],
    "composition": "Control open state externally. Provide title and description for accessible naming.",
    "slots": [
      "children",
      "overlay",
      "content"
    ],
    "states": [
      "closed",
      "open",
      "entering",
      "leaving"
    ]
  },
  "Drawer": {
    "summary": "Drawer slides in from the left or right edge with overlay dismissal.",
    "structure": [
      "Drawer (root)",
      "Overlay",
      "Panel",
      "Header",
      "Body (children)"
    ],
    "composition": "Pair with Button triggers. Configure side via defaultProps or prop.",
    "slots": [
      "children"
    ],
    "states": [
      "closed",
      "open"
    ]
  },
  "Dialog": {
    "summary": "Dialog is a lightweight modal surface for confirmations and forms.",
    "structure": [
      "Dialog",
      "Header",
      "Title",
      "Description",
      "Actions"
    ],
    "composition": "Use for focused tasks smaller than full Modal layouts.",
    "slots": [
      "children"
    ],
    "states": [
      "closed",
      "open"
    ]
  },
  "Popover": {
    "summary": "Popover anchors floating content to a trigger with collision handling.",
    "structure": [
      "Popover",
      "Trigger",
      "Content"
    ],
    "composition": "Keep content concise; prefer Tooltip for single-line hints.",
    "slots": [
      "trigger",
      "children"
    ],
    "states": [
      "closed",
      "open"
    ]
  },
  "Card": {
    "summary": "Card groups related content with optional title and padding tokens.",
    "structure": [
      "Card",
      "Header/Title",
      "Body",
      "Footer actions"
    ],
    "composition": "Use padding tokens or Card defaultProps for density consistency.",
    "slots": [
      "children",
      "title"
    ],
    "states": [
      "default"
    ]
  },
  "Select": {
    "summary": "Select provides a styled native-like picker with validation states.",
    "structure": [
      "Select",
      "Label",
      "Trigger",
      "Options list"
    ],
    "composition": "Pass options array; pair with forms and validation messages.",
    "slots": [
      "label"
    ],
    "states": [
      "default",
      "disabled",
      "error"
    ]
  },
  "CommandPalette": {
    "summary": "CommandPalette offers searchable command discovery with keyboard navigation.",
    "structure": [
      "CommandPalette",
      "Search input",
      "Results groups",
      "Items"
    ],
    "composition": "Register commands with labels and onSelect handlers.",
    "slots": [
      "commands"
    ],
    "states": [
      "closed",
      "open"
    ]
  },
  "Picker": {
    "summary": "Picker covers date/time selection with wheel and calendar variants.",
    "structure": [
      "Picker",
      "Trigger",
      "Panel",
      "CalendarGrid / WheelColumn"
    ],
    "composition": "Choose the picker variant matching platform expectations.",
    "slots": [
      "label",
      "value"
    ],
    "states": [
      "closed",
      "open"
    ]
  },
  "LiquidGlass": {
    "summary": "Base liquid glass surface with SVG displacement refraction on Chromium and frosted blur elsewhere.",
    "structure": [
      "LiquidGlass shell",
      "Specular rim",
      "Inner highlight",
      "Content wrapper"
    ],
    "composition": "Use as a layout primitive or compose higher-level LiquidGlass* components.",
    "slots": [
      "children"
    ],
    "states": [
      "default"
    ]
  },
  "LiquidGlassTabBar": {
    "summary": "iOS-style floating tab bar with morphing selection indicator on a shared LiquidGlass track.",
    "structure": [
      "LiquidGlass nav shell",
      "Selection indicator",
      "Tab buttons"
    ],
    "composition": "Pass items with icons and optional labels; control activeKey for routing.",
    "slots": [
      "items"
    ],
    "states": [
      "default",
      "disabled tab"
    ]
  },
  "LiquidGlassButton": {
    "summary": "Pill button with full liquid glass optics exposed for tuning.",
    "structure": [
      "LiquidGlass button shell",
      "Label / icon children"
    ],
    "composition": "Use for primary actions on colorful or photographic backgrounds.",
    "slots": [
      "children"
    ],
    "states": [
      "default",
      "disabled",
      "hover",
      "active"
    ]
  },
  "LiquidGlassTopBar": {
    "summary": "Floating or edge-aligned top navigation with segmented control and trailing actions.",
    "structure": [
      "LiquidGlass header",
      "Title",
      "Segmented nav",
      "Trailing slot"
    ],
    "composition": "Pair title with nav items; use variant floating for iOS-style inset bars.",
    "slots": [
      "title",
      "trailing",
      "logo"
    ],
    "states": [
      "default"
    ]
  },
  "LiquidGlassSwitch": {
    "summary": "Toggle switch with glass track and sliding glass thumb.",
    "structure": [
      "Glass track",
      "Glass thumb",
      "Switch button semantics"
    ],
    "composition": "Controlled or uncontrolled; always provide aria-label when no visible label.",
    "slots": [],
    "states": [
      "off",
      "on",
      "disabled"
    ]
  },
  "LiquidGlassRange": {
    "summary": "Range slider with glass track, fill, and draggable glass thumb.",
    "structure": [
      "Glass track",
      "Fill",
      "Glass thumb",
      "Native range input (a11y)"
    ],
    "composition": "Use for volume, brightness, or any scalar control over a colorful backdrop.",
    "slots": [],
    "states": [
      "default",
      "disabled"
    ]
  },
  "LiquidGlassProgress": {
    "summary": "Horizontal progress bar with glass track and luminous fill.",
    "structure": [
      "Glass track",
      "Fill bar"
    ],
    "composition": "Set value/max for determinate progress; use indeterminate for loading.",
    "slots": [],
    "states": [
      "determinate",
      "indeterminate"
    ]
  },
  "LiquidGlassCheckbox": {
    "summary": "Checkbox with glass box, animated checkmark, and optional label.",
    "structure": [
      "Glass box",
      "Check icon",
      "Label"
    ],
    "composition": "Use in settings panels on glass or aurora backgrounds.",
    "slots": [
      "label"
    ],
    "states": [
      "unchecked",
      "checked",
      "disabled"
    ]
  },
  "Tabs": {
    "summary": "Accessible tab list with keyboard navigation and optional lazy panels.",
    "structure": [
      "Tabs",
      "TabsList",
      "TabsTrigger",
      "TabsPanel"
    ],
    "composition": "Compose triggers and panels with matching value keys.",
    "slots": [
      "children"
    ],
    "states": [
      "default",
      "disabled"
    ]
  },
  "TabView": {
    "summary": "macOS-style tab view with closable tabs and overflow handling.",
    "structure": [
      "TabView",
      "TabViewList",
      "TabViewTab",
      "TabViewPanel"
    ],
    "composition": "Use for document-style interfaces with multiple open views.",
    "slots": [
      "children"
    ],
    "states": [
      "default",
      "active tab"
    ]
  },
  "Accordion": {
    "summary": "Expandable sections with single or multiple open items.",
    "structure": [
      "Accordion",
      "AccordionItem",
      "AccordionTrigger",
      "AccordionContent"
    ],
    "composition": "Wrap each section in AccordionItem; use type multiple for FAQ layouts.",
    "slots": [
      "children"
    ],
    "states": [
      "collapsed",
      "expanded"
    ]
  }
};
