// Generated by scripts/generate-docs-catalog.mjs — do not edit manually.

export type DocsFrameworkSeed = 'react' | 'vue' | 'svelte';

export interface PlaygroundSeedEntry {
  react: string;
  vue?: string;
  svelte?: string;
}

export const playgroundSeeds: Record<string, PlaygroundSeedEntry> = {
  "AcceleratorProvider": {
    "react": "import { AcceleratorProvider } from '@larose-ui/react';\n\nexport default function App() {\n  return <AcceleratorProvider\n  platform=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { AcceleratorProvider } from '@larose-ui/vue';\n</script>\n\n<template>\n  <AcceleratorProvider\n  platform=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { AcceleratorProvider } from '@larose-ui/svelte';\n</script>\n\n<AcceleratorProvider\n  platform=\"example\"\n/>\n"
  },
  "Accordion": {
    "react": "import { Accordion } from '@larose-ui/react';\n\nexport default function App() {\n  return <Accordion\n  collapsible={false}\n  defaultValue={[]}\n  type={== 'single') {}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Accordion } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Accordion\n  :collapsible=\"false\"\n  :defaultValue=\"[]\"\n  :type=\"== 'single') {\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Accordion } from '@larose-ui/svelte';\n</script>\n\n<Accordion\n  collapsible={false}\n  defaultValue={[]}\n  type={== 'single') {}\n/>\n"
  },
  "AccordionContent": {
    "react": "import { AccordionContent } from '@larose-ui/react';\n\nexport default function App() {\n  return <AccordionContent />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { AccordionContent } from '@larose-ui/vue';\n</script>\n\n<template>\n  <AccordionContent />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { AccordionContent } from '@larose-ui/svelte';\n</script>\n\n<AccordionContent />\n"
  },
  "AccordionItem": {
    "react": "import { AccordionItem } from '@larose-ui/react';\n\nexport default function App() {\n  return <AccordionItem\n  disabled\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { AccordionItem } from '@larose-ui/vue';\n</script>\n\n<template>\n  <AccordionItem\n  disabled\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { AccordionItem } from '@larose-ui/svelte';\n</script>\n\n<AccordionItem\n  disabled\n  value=\"example\"\n/>\n"
  },
  "AccordionTrigger": {
    "react": "import { AccordionTrigger } from '@larose-ui/react';\n\nexport default function App() {\n  return <AccordionTrigger />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { AccordionTrigger } from '@larose-ui/vue';\n</script>\n\n<template>\n  <AccordionTrigger />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { AccordionTrigger } from '@larose-ui/svelte';\n</script>\n\n<AccordionTrigger />\n"
  },
  "ActivityShareButton": {
    "react": "import { ActivityShareButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <ActivityShareButton\n  label=\"example\"\n  presentation=\"sheet\"\n>\n      Example\n    </ActivityShareButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ActivityShareButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ActivityShareButton\n  label=\"example\"\n  presentation=\"sheet\"\n>\n    Example\n  </ActivityShareButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ActivityShareButton } from '@larose-ui/svelte';\n</script>\n\n<ActivityShareButton\n  label=\"example\"\n  presentation=\"sheet\"\n>\n  Example\n</ActivityShareButton>\n"
  },
  "ActivityView": {
    "react": "import { ActivityView } from '@larose-ui/react';\n\nexport default function App() {\n  return <ActivityView\n  open\n  presentation=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ActivityView } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ActivityView\n  open\n  presentation=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ActivityView } from '@larose-ui/svelte';\n</script>\n\n<ActivityView\n  open\n  presentation=\"example\"\n/>\n"
  },
  "Alert": {
    "react": "import { Alert } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <Alert\n  variant=\"info\"\n>\n      Your changes were saved.\n    </Alert>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Alert } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Alert\n  variant=\"info\"\n>\n    Your changes were saved.\n  </Alert>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Alert } from '@larose-ui/svelte';\n</script>\n\n<Alert\n  variant=\"info\"\n>\n  Your changes were saved.\n</Alert>\n"
  },
  "AlertDialog": {
    "react": "import { AlertDialog } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <AlertDialog\n  defaultActionId=\"example\"\n  helpUrl=\"example\"\n  message=\"example\"\n  open\n>\n      Example\n    </AlertDialog>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { AlertDialog } from '@larose-ui/vue';\n</script>\n\n<template>\n  <AlertDialog\n  defaultActionId=\"example\"\n  helpUrl=\"example\"\n  message=\"example\"\n  open\n>\n    Example\n  </AlertDialog>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { AlertDialog } from '@larose-ui/svelte';\n</script>\n\n<AlertDialog\n  defaultActionId=\"example\"\n  helpUrl=\"example\"\n  message=\"example\"\n  open\n>\n  Example\n</AlertDialog>\n"
  },
  "AsyncButton": {
    "react": "import { AsyncButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <AsyncButton\n  size=\"md\"\n  variant=\"primary\"\n>\n      Example\n    </AsyncButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { AsyncButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <AsyncButton\n  size=\"md\"\n  variant=\"primary\"\n>\n    Example\n  </AsyncButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { AsyncButton } from '@larose-ui/svelte';\n</script>\n\n<AsyncButton\n  size=\"md\"\n  variant=\"primary\"\n>\n  Example\n</AsyncButton>\n"
  },
  "Badge": {
    "react": "import { Badge } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <Badge\n  variant=\"info\"\n>\n      Beta\n    </Badge>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Badge } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Badge\n  variant=\"info\"\n>\n    Beta\n  </Badge>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Badge } from '@larose-ui/svelte';\n</script>\n\n<Badge\n  variant=\"info\"\n>\n  Beta\n</Badge>\n"
  },
  "Box": {
    "react": "import { Box } from '@larose-ui/react';\n\nexport default function App() {\n  return <Box\n  aria-label=\"example\"\n  padding=\"sm\"\n  settingsStyle\n  titlePosition=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Box } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Box\n  aria-label=\"example\"\n  padding=\"sm\"\n  settingsStyle\n  titlePosition=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Box } from '@larose-ui/svelte';\n</script>\n\n<Box\n  aria-label=\"example\"\n  padding=\"sm\"\n  settingsStyle\n  titlePosition=\"example\"\n/>\n"
  },
  "Breadcrumb": {
    "react": "import { Breadcrumb } from '@larose-ui/react';\n\nexport default function App() {\n  return <Breadcrumb\n  aria-label=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Breadcrumb } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Breadcrumb\n  aria-label=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Breadcrumb } from '@larose-ui/svelte';\n</script>\n\n<Breadcrumb\n  aria-label=\"example\"\n/>\n"
  },
  "Button": {
    "react": "import { Button } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <Button\n  variant=\"primary\"\n  size=\"md\"\n  shape=\"capsule\"\n  buttonRole=\"normal\"\n  disabled={false}\n  loading={false}\n>\n      Save changes\n    </Button>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Button } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Button\n  variant=\"primary\"\n  size=\"md\"\n  shape=\"capsule\"\n  buttonRole=\"normal\"\n  :disabled=\"false\"\n  :loading=\"false\"\n>\n    Save changes\n  </Button>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Button } from '@larose-ui/svelte';\n</script>\n\n<Button\n  variant=\"primary\"\n  size=\"md\"\n  shape=\"capsule\"\n  buttonRole=\"normal\"\n  disabled={false}\n  loading={false}\n>\n  Save changes\n</Button>\n"
  },
  "ButtonGroup": {
    "react": "import { ButtonGroup } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <ButtonGroup\n  aria-label=\"example\"\n  fullWidth\n  orientation=\"horizontal\"\n>\n      Example\n    </ButtonGroup>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ButtonGroup } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ButtonGroup\n  aria-label=\"example\"\n  fullWidth\n  orientation=\"horizontal\"\n>\n    Example\n  </ButtonGroup>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ButtonGroup } from '@larose-ui/svelte';\n</script>\n\n<ButtonGroup\n  aria-label=\"example\"\n  fullWidth\n  orientation=\"horizontal\"\n>\n  Example\n</ButtonGroup>\n"
  },
  "CalendarGrid": {
    "react": "import { CalendarGrid } from '@larose-ui/react';\n\nexport default function App() {\n  return <CalendarGrid\n  locale=\"en\"\n  maxDate=\"example\"\n  minDate=\"example\"\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { CalendarGrid } from '@larose-ui/vue';\n</script>\n\n<template>\n  <CalendarGrid\n  locale=\"en\"\n  maxDate=\"example\"\n  minDate=\"example\"\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { CalendarGrid } from '@larose-ui/svelte';\n</script>\n\n<CalendarGrid\n  locale=\"en\"\n  maxDate=\"example\"\n  minDate=\"example\"\n  value=\"example\"\n/>\n"
  },
  "CaptionButton": {
    "react": "import { CaptionButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <CaptionButton\n  imageUrl=\"example\"\n  label=\"example\"\n  subtitle=\"example\"\n>\n      Example\n    </CaptionButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { CaptionButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <CaptionButton\n  imageUrl=\"example\"\n  label=\"example\"\n  subtitle=\"example\"\n>\n    Example\n  </CaptionButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { CaptionButton } from '@larose-ui/svelte';\n</script>\n\n<CaptionButton\n  imageUrl=\"example\"\n  label=\"example\"\n  subtitle=\"example\"\n>\n  Example\n</CaptionButton>\n"
  },
  "Card": {
    "react": "import { Card } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <Card title=\"Employee profile\" description=\"Interactive docs demo\" padding=\"md\">\n      Card body content\n    </Card>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Card } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Card title=\"Employee profile\" description=\"Interactive docs demo\" padding=\"md\">\n    Card body content\n  </Card>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Card } from '@larose-ui/svelte';\n</script>\n\n<Card title=\"Employee profile\" description=\"Interactive docs demo\" padding=\"md\">\n  Card body content\n</Card>\n"
  },
  "Chart": {
    "react": "import { Chart } from '@larose-ui/react';\n\nexport default function App() {\n  return <Chart\n  accessibilitySummary=\"example\"\n  annotation=\"example\"\n  height={220}\n  interactive={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Chart } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Chart\n  accessibilitySummary=\"example\"\n  annotation=\"example\"\n  :height=\"220\"\n  :interactive=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Chart } from '@larose-ui/svelte';\n</script>\n\n<Chart\n  accessibilitySummary=\"example\"\n  annotation=\"example\"\n  height={220}\n  interactive={false}\n/>\n"
  },
  "Checkbox": {
    "react": "import { Checkbox } from '@larose-ui/react';\n\nexport default function App() {\n  return <Checkbox\n  label=\"Accept terms\"\n  checked={false}\n  disabled={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Checkbox } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Checkbox\n  label=\"Accept terms\"\n  :checked=\"false\"\n  :disabled=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Checkbox } from '@larose-ui/svelte';\n</script>\n\n<Checkbox\n  label=\"Accept terms\"\n  checked={false}\n  disabled={false}\n/>\n"
  },
  "CollaborationButton": {
    "react": "import { CollaborationButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <CollaborationButton\n  label=\"Collaboration\"\n  maxVisible={3}\n>\n      Example\n    </CollaborationButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { CollaborationButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <CollaborationButton\n  label=\"Collaboration\"\n  :maxVisible=\"3\"\n>\n    Example\n  </CollaborationButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { CollaborationButton } from '@larose-ui/svelte';\n</script>\n\n<CollaborationButton\n  label=\"Collaboration\"\n  maxVisible={3}\n>\n  Example\n</CollaborationButton>\n"
  },
  "CollaborationPopover": {
    "react": "import { CollaborationPopover } from '@larose-ui/react';\n\nexport default function App() {\n  return <CollaborationPopover\n  defaultOpen={false}\n  manageLabel=\"Manage Shared File\"\n  open\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { CollaborationPopover } from '@larose-ui/vue';\n</script>\n\n<template>\n  <CollaborationPopover\n  :defaultOpen=\"false\"\n  manageLabel=\"Manage Shared File\"\n  open\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { CollaborationPopover } from '@larose-ui/svelte';\n</script>\n\n<CollaborationPopover\n  defaultOpen={false}\n  manageLabel=\"Manage Shared File\"\n  open\n/>\n"
  },
  "Collection": {
    "react": "import { Collection } from '@larose-ui/react';\n\nexport default function App() {\n  return <Collection\n  ariaLabel=\"example\"\n  columns={0}\n  layout=\"example\"\n  selectedId=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Collection } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Collection\n  ariaLabel=\"example\"\n  :columns=\"0\"\n  layout=\"example\"\n  selectedId=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Collection } from '@larose-ui/svelte';\n</script>\n\n<Collection\n  ariaLabel=\"example\"\n  columns={0}\n  layout=\"example\"\n  selectedId=\"example\"\n/>\n"
  },
  "ColumnView": {
    "react": "import { ColumnView } from '@larose-ui/react';\n\nexport default function App() {\n  return <ColumnView\n  ariaLabel=\"Column view\"\n  initialPath={[]}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ColumnView } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ColumnView\n  ariaLabel=\"Column view\"\n  :initialPath=\"[]\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ColumnView } from '@larose-ui/svelte';\n</script>\n\n<ColumnView\n  ariaLabel=\"Column view\"\n  initialPath={[]}\n/>\n"
  },
  "CommandPalette": {
    "react": "import { useState } from 'react';\nimport { Button, CommandPalette } from '@larose-ui/react';\n\nexport default function App() {\n  const [open, setOpen] = useState(true);\n  return (\n    <>\n      <Button onClick={() => setOpen(true)}>Open commands</Button>\n      <CommandPalette\n        open={open}\n        onOpenChange={setOpen}\n        items={[\n          { id: 'new', label: 'New file', group: 'File', onSelect: () => setOpen(false) },\n          { id: 'save', label: 'Save', group: 'File', onSelect: () => setOpen(false) },\n        ]}\n      />\n    </>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ref } from 'vue';\nimport { Button, CommandPalette } from '@larose-ui/vue';\nconst open = ref(true);\nconst items = [\n  { id: 'new', label: 'New file', group: 'File', onSelect: () => (open.value = false) },\n  { id: 'save', label: 'Save', group: 'File', onSelect: () => (open.value = false) },\n];\n</script>\n\n<template>\n  <Button @click=\"open = true\">Open commands</Button>\n  <CommandPalette :open=\"open\" :items=\"items\" @open-change=\"open = $event\" />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Button, CommandPalette } from '@larose-ui/svelte';\n  let open = $state(true);\n  const items = [\n    { id: 'new', label: 'New file', group: 'File', onSelect: () => (open = false) },\n    { id: 'save', label: 'Save', group: 'File', onSelect: () => (open = false) },\n  ];\n</script>\n\n<Button onclick={() => (open = true)}>Open commands</Button>\n<CommandPalette {open} {items} onOpenChange={(v) => (open = v)} />\n"
  },
  "ContextMenu": {
    "react": "import { ContextMenu } from '@larose-ui/react';\n\nexport default function App() {\n  return <ContextMenu\n  dimBackground\n  longPress\n  open\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ContextMenu } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ContextMenu\n  dimBackground\n  longPress\n  open\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ContextMenu } from '@larose-ui/svelte';\n</script>\n\n<ContextMenu\n  dimBackground\n  longPress\n  open\n/>\n"
  },
  "DataTable": {
    "react": "import { DataTable } from '@larose-ui/react';\n\nexport default function App() {\n  return <DataTable\n  aria-label=\"example\"\n  caption=\"example\"\n  emptyDescription=\"example\"\n  emptyMessage=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DataTable } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DataTable\n  aria-label=\"example\"\n  caption=\"example\"\n  emptyDescription=\"example\"\n  emptyMessage=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DataTable } from '@larose-ui/svelte';\n</script>\n\n<DataTable\n  aria-label=\"example\"\n  caption=\"example\"\n  emptyDescription=\"example\"\n  emptyMessage=\"example\"\n/>\n"
  },
  "DatePicker": {
    "react": "import { DatePicker } from '@larose-ui/react';\n\nexport default function App() {\n  return <DatePicker\n  error={null}\n  hint=\"example\"\n  inputSize=\"md\"\n  label=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DatePicker } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DatePicker\n  :error=\"null\"\n  hint=\"example\"\n  inputSize=\"md\"\n  label=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DatePicker } from '@larose-ui/svelte';\n</script>\n\n<DatePicker\n  error={null}\n  hint=\"example\"\n  inputSize=\"md\"\n  label=\"example\"\n/>\n"
  },
  "DateRangePicker": {
    "react": "import { DateRangePicker } from '@larose-ui/react';\n\nexport default function App() {\n  return <DateRangePicker\n  disabled\n  endLabel=\"End date\"\n  error={null}\n  hint=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DateRangePicker } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DateRangePicker\n  disabled\n  endLabel=\"End date\"\n  :error=\"null\"\n  hint=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DateRangePicker } from '@larose-ui/svelte';\n</script>\n\n<DateRangePicker\n  disabled\n  endLabel=\"End date\"\n  error={null}\n  hint=\"example\"\n/>\n"
  },
  "DateTimePicker": {
    "react": "import { DateTimePicker } from '@larose-ui/react';\n\nexport default function App() {\n  return <DateTimePicker\n  appearance=\"example\"\n  disabled\n  error=\"example\"\n  hint=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DateTimePicker } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DateTimePicker\n  appearance=\"example\"\n  disabled\n  error=\"example\"\n  hint=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DateTimePicker } from '@larose-ui/svelte';\n</script>\n\n<DateTimePicker\n  appearance=\"example\"\n  disabled\n  error=\"example\"\n  hint=\"example\"\n/>\n"
  },
  "Dialog": {
    "react": "import { useState } from 'react';\nimport { Button, Dialog } from '@larose-ui/react';\n\nexport default function App() {\n  const [open, setOpen] = useState(true);\n  return (\n    <>\n      <Button onClick={() => setOpen(true)}>Open dialog</Button>\n      <Dialog open={open} onClose={() => setOpen(false)} title=\"Dialog\">\n        <p>Live editable dialog example.</p>\n      </Dialog>\n    </>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ref } from 'vue';\nimport { Button, Dialog } from '@larose-ui/vue';\nconst open = ref(true);\n</script>\n\n<template>\n  <Button @click=\"open = true\">Open dialog</Button>\n  <Dialog :open=\"open\" title=\"Dialog\" @close=\"open = false\">\n    <p>Live editable dialog example.</p>\n  </Dialog>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Button, Dialog } from '@larose-ui/svelte';\n  let open = $state(true);\n</script>\n\n<Button onclick={() => (open = true)}>Open dialog</Button>\n<Dialog {open} title=\"Dialog\" onclose={() => (open = false)}>\n  <p>Live editable dialog example.</p>\n</Dialog>\n"
  },
  "DisclosureButton": {
    "react": "import { DisclosureButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <DisclosureButton\n  aria-label=\"example\"\n  defaultExpanded={false}\n  disabled={false}\n  expanded\n>\n      Example\n    </DisclosureButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DisclosureButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DisclosureButton\n  aria-label=\"example\"\n  :defaultExpanded=\"false\"\n  :disabled=\"false\"\n  expanded\n>\n    Example\n  </DisclosureButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DisclosureButton } from '@larose-ui/svelte';\n</script>\n\n<DisclosureButton\n  aria-label=\"example\"\n  defaultExpanded={false}\n  disabled={false}\n  expanded\n>\n  Example\n</DisclosureButton>\n"
  },
  "DisclosureGroup": {
    "react": "import { DisclosureGroup } from '@larose-ui/react';\n\nexport default function App() {\n  return <DisclosureGroup\n  defaultExpanded\n  disabled\n  expanded\n  label=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DisclosureGroup } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DisclosureGroup\n  defaultExpanded\n  disabled\n  expanded\n  label=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DisclosureGroup } from '@larose-ui/svelte';\n</script>\n\n<DisclosureGroup\n  defaultExpanded\n  disabled\n  expanded\n  label=\"example\"\n/>\n"
  },
  "DisclosureList": {
    "react": "import { DisclosureList } from '@larose-ui/react';\n\nexport default function App() {\n  return <DisclosureList />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DisclosureList } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DisclosureList />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DisclosureList } from '@larose-ui/svelte';\n</script>\n\n<DisclosureList />\n"
  },
  "DisclosureTriangle": {
    "react": "import { DisclosureTriangle } from '@larose-ui/react';\n\nexport default function App() {\n  return <DisclosureTriangle\n  defaultExpanded={false}\n  disabled={false}\n  expanded\n  label=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DisclosureTriangle } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DisclosureTriangle\n  :defaultExpanded=\"false\"\n  :disabled=\"false\"\n  expanded\n  label=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DisclosureTriangle } from '@larose-ui/svelte';\n</script>\n\n<DisclosureTriangle\n  defaultExpanded={false}\n  disabled={false}\n  expanded\n  label=\"example\"\n/>\n"
  },
  "DockBar": {
    "react": "import { DockBar } from '@larose-ui/react';\n\nexport default function App() {\n  return <DockBar\n  aria-label=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DockBar } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DockBar\n  aria-label=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DockBar } from '@larose-ui/svelte';\n</script>\n\n<DockBar\n  aria-label=\"example\"\n/>\n"
  },
  "DockMenu": {
    "react": "import { DockMenu } from '@larose-ui/react';\n\nexport default function App() {\n  return <DockMenu\n  appName=\"example\"\n  isRunning\n  open\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DockMenu } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DockMenu\n  appName=\"example\"\n  isRunning\n  open\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DockMenu } from '@larose-ui/svelte';\n</script>\n\n<DockMenu\n  appName=\"example\"\n  isRunning\n  open\n/>\n"
  },
  "DocumentLauncher": {
    "react": "import { DocumentLauncher } from '@larose-ui/react';\n\nexport default function App() {\n  return <DocumentLauncher\n  appTitle=\"example\"\n  primaryActionLabel=\"example\"\n  secondaryActionLabel=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DocumentLauncher } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DocumentLauncher\n  appTitle=\"example\"\n  primaryActionLabel=\"example\"\n  secondaryActionLabel=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DocumentLauncher } from '@larose-ui/svelte';\n</script>\n\n<DocumentLauncher\n  appTitle=\"example\"\n  primaryActionLabel=\"example\"\n  secondaryActionLabel=\"example\"\n/>\n"
  },
  "DocumentToolbar": {
    "react": "import { DocumentToolbar } from '@larose-ui/react';\n\nexport default function App() {\n  return <DocumentToolbar\n  canSave\n  newLabel=\"example\"\n  openLabel=\"example\"\n  saveLabel=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DocumentToolbar } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DocumentToolbar\n  canSave\n  newLabel=\"example\"\n  openLabel=\"example\"\n  saveLabel=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DocumentToolbar } from '@larose-ui/svelte';\n</script>\n\n<DocumentToolbar\n  canSave\n  newLabel=\"example\"\n  openLabel=\"example\"\n  saveLabel=\"example\"\n/>\n"
  },
  "DragDropList": {
    "react": "import { DragDropList } from '@larose-ui/react';\n\nexport default function App() {\n  return <DragDropList\n  zoneId=\"list\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DragDropList } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DragDropList\n  zoneId=\"list\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DragDropList } from '@larose-ui/svelte';\n</script>\n\n<DragDropList\n  zoneId=\"list\"\n/>\n"
  },
  "Draggable": {
    "react": "import { Draggable } from '@larose-ui/react';\n\nexport default function App() {\n  return <Draggable\n  disabled={false}\n  label=\"example\"\n  sourceId=\"example\"\n  type=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Draggable } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Draggable\n  :disabled=\"false\"\n  label=\"example\"\n  sourceId=\"example\"\n  type=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Draggable } from '@larose-ui/svelte';\n</script>\n\n<Draggable\n  disabled={false}\n  label=\"example\"\n  sourceId=\"example\"\n  type=\"example\"\n/>\n"
  },
  "Drawer": {
    "react": "import { Drawer } from '@larose-ui/react';\n\nexport default function App() {\n  return <Drawer\n  closeOnOverlay\n  description=\"example\"\n  open\n  overlayStyle=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Drawer } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Drawer\n  closeOnOverlay\n  description=\"example\"\n  open\n  overlayStyle=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Drawer } from '@larose-ui/svelte';\n</script>\n\n<Drawer\n  closeOnOverlay\n  description=\"example\"\n  open\n  overlayStyle=\"example\"\n/>\n"
  },
  "DropZone": {
    "react": "import { DropZone } from '@larose-ui/react';\n\nexport default function App() {\n  return <DropZone\n  disabled={false}\n  showInvalidIndicator={true}\n  transferring={false}\n  transferringLabel=\"Transferring…\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { DropZone } from '@larose-ui/vue';\n</script>\n\n<template>\n  <DropZone\n  :disabled=\"false\"\n  :showInvalidIndicator=\"true\"\n  :transferring=\"false\"\n  transferringLabel=\"Transferring…\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { DropZone } from '@larose-ui/svelte';\n</script>\n\n<DropZone\n  disabled={false}\n  showInvalidIndicator={true}\n  transferring={false}\n  transferringLabel=\"Transferring…\"\n/>\n"
  },
  "EditMenu": {
    "react": "import { EditMenu } from '@larose-ui/react';\n\nexport default function App() {\n  return <EditMenu\n  context=\"example\"\n  dimBackground\n  includeStandardActions\n  inputMode=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { EditMenu } from '@larose-ui/vue';\n</script>\n\n<template>\n  <EditMenu\n  context=\"example\"\n  dimBackground\n  includeStandardActions\n  inputMode=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { EditMenu } from '@larose-ui/svelte';\n</script>\n\n<EditMenu\n  context=\"example\"\n  dimBackground\n  includeStandardActions\n  inputMode=\"example\"\n/>\n"
  },
  "EditMenuSelection": {
    "react": "import { EditMenuSelection } from '@larose-ui/react';\n\nexport default function App() {\n  return <EditMenuSelection />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { EditMenuSelection } from '@larose-ui/vue';\n</script>\n\n<template>\n  <EditMenuSelection />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { EditMenuSelection } from '@larose-ui/svelte';\n</script>\n\n<EditMenuSelection />\n"
  },
  "EmptyState": {
    "react": "import { EmptyState } from '@larose-ui/react';\n\nexport default function App() {\n  return <EmptyState\n  actionLabel=\"example\"\n  description=\"example\"\n  state=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { EmptyState } from '@larose-ui/vue';\n</script>\n\n<template>\n  <EmptyState\n  actionLabel=\"example\"\n  description=\"example\"\n  state=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { EmptyState } from '@larose-ui/svelte';\n</script>\n\n<EmptyState\n  actionLabel=\"example\"\n  description=\"example\"\n  state=\"example\"\n/>\n"
  },
  "FileBrowser": {
    "react": "import { FileBrowser } from '@larose-ui/react';\n\nexport default function App() {\n  return <FileBrowser\n  activeTab=\"recents\"\n  emptyLabel=\"No documents in this location.\"\n  selectedId=\"example\"\n  showExtensions={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { FileBrowser } from '@larose-ui/vue';\n</script>\n\n<template>\n  <FileBrowser\n  activeTab=\"recents\"\n  emptyLabel=\"No documents in this location.\"\n  selectedId=\"example\"\n  :showExtensions=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { FileBrowser } from '@larose-ui/svelte';\n</script>\n\n<FileBrowser\n  activeTab=\"recents\"\n  emptyLabel=\"No documents in this location.\"\n  selectedId=\"example\"\n  showExtensions={false}\n/>\n"
  },
  "FilePreview": {
    "react": "import { FilePreview } from '@larose-ui/react';\n\nexport default function App() {\n  return <FilePreview\n  closeLabel=\"example\"\n  source=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { FilePreview } from '@larose-ui/vue';\n</script>\n\n<template>\n  <FilePreview\n  closeLabel=\"example\"\n  source=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { FilePreview } from '@larose-ui/svelte';\n</script>\n\n<FilePreview\n  closeLabel=\"example\"\n  source=\"example\"\n/>\n"
  },
  "FileUpload": {
    "react": "import { FileUpload } from '@larose-ui/react';\n\nexport default function App() {\n  return <FileUpload\n  accept=\"example\"\n  buttonLabel=\"Choose files or drag here\"\n  disabled={false}\n  error={null}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { FileUpload } from '@larose-ui/vue';\n</script>\n\n<template>\n  <FileUpload\n  accept=\"example\"\n  buttonLabel=\"Choose files or drag here\"\n  :disabled=\"false\"\n  :error=\"null\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { FileUpload } from '@larose-ui/svelte';\n</script>\n\n<FileUpload\n  accept=\"example\"\n  buttonLabel=\"Choose files or drag here\"\n  disabled={false}\n  error={null}\n/>\n"
  },
  "Header": {
    "react": "import { Header } from '@larose-ui/react';\n\nexport default function App() {\n  return <Header />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Header } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Header />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Header } from '@larose-ui/svelte';\n</script>\n\n<Header />\n"
  },
  "HeaderActions": {
    "react": "import { HeaderActions } from '@larose-ui/react';\n\nexport default function App() {\n  return <HeaderActions />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { HeaderActions } from '@larose-ui/vue';\n</script>\n\n<template>\n  <HeaderActions />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { HeaderActions } from '@larose-ui/svelte';\n</script>\n\n<HeaderActions />\n"
  },
  "HeaderBrand": {
    "react": "import { HeaderBrand } from '@larose-ui/react';\n\nexport default function App() {\n  return <HeaderBrand />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { HeaderBrand } from '@larose-ui/vue';\n</script>\n\n<template>\n  <HeaderBrand />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { HeaderBrand } from '@larose-ui/svelte';\n</script>\n\n<HeaderBrand />\n"
  },
  "HeaderTitle": {
    "react": "import { HeaderTitle } from '@larose-ui/react';\n\nexport default function App() {\n  return <HeaderTitle />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { HeaderTitle } from '@larose-ui/vue';\n</script>\n\n<template>\n  <HeaderTitle />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { HeaderTitle } from '@larose-ui/svelte';\n</script>\n\n<HeaderTitle />\n"
  },
  "HelpButton": {
    "react": "import { HelpButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <HelpButton\n  helpTopic=\"example\"\n>\n      Example\n    </HelpButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { HelpButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <HelpButton\n  helpTopic=\"example\"\n>\n    Example\n  </HelpButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { HelpButton } from '@larose-ui/svelte';\n</script>\n\n<HelpButton\n  helpTopic=\"example\"\n>\n  Example\n</HelpButton>\n"
  },
  "HomeScreenQuickActions": {
    "react": "import { HomeScreenQuickActions } from '@larose-ui/react';\n\nexport default function App() {\n  return <HomeScreenQuickActions\n  appName=\"example\"\n  iconPlacement=\"md\"\n  includeSystemActions\n  open\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { HomeScreenQuickActions } from '@larose-ui/vue';\n</script>\n\n<template>\n  <HomeScreenQuickActions\n  appName=\"example\"\n  iconPlacement=\"md\"\n  includeSystemActions\n  open\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { HomeScreenQuickActions } from '@larose-ui/svelte';\n</script>\n\n<HomeScreenQuickActions\n  appName=\"example\"\n  iconPlacement=\"md\"\n  includeSystemActions\n  open\n/>\n"
  },
  "ImageButton": {
    "react": "import { ImageButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <ImageButton\n  alt=\"example\"\n  src=\"example\"\n>\n      Example\n    </ImageButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ImageButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ImageButton\n  alt=\"example\"\n  src=\"example\"\n>\n    Example\n  </ImageButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ImageButton } from '@larose-ui/svelte';\n</script>\n\n<ImageButton\n  alt=\"example\"\n  src=\"example\"\n>\n  Example\n</ImageButton>\n"
  },
  "ImageOverlay": {
    "react": "import { ImageOverlay } from '@larose-ui/react';\n\nexport default function App() {\n  return <ImageOverlay />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ImageOverlay } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ImageOverlay />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ImageOverlay } from '@larose-ui/svelte';\n</script>\n\n<ImageOverlay />\n"
  },
  "ImageView": {
    "react": "import { ImageView } from '@larose-ui/react';\n\nexport default function App() {\n  return <ImageView\n  alt=\"example\"\n  background=\"opaque\"\n  fit=\"contain\"\n  frameClassName=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ImageView } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ImageView\n  alt=\"example\"\n  background=\"opaque\"\n  fit=\"contain\"\n  frameClassName=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ImageView } from '@larose-ui/svelte';\n</script>\n\n<ImageView\n  alt=\"example\"\n  background=\"opaque\"\n  fit=\"contain\"\n  frameClassName=\"example\"\n/>\n"
  },
  "ImageWell": {
    "react": "import { ImageWell } from '@larose-ui/react';\n\nexport default function App() {\n  return <ImageWell\n  accept=\"image/*\"\n  disabled={false}\n  label=\"Image\"\n  placeholder={'Drop an image}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ImageWell } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ImageWell\n  accept=\"image/*\"\n  :disabled=\"false\"\n  label=\"Image\"\n  :placeholder=\"'Drop an image\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ImageWell } from '@larose-ui/svelte';\n</script>\n\n<ImageWell\n  accept=\"image/*\"\n  disabled={false}\n  label=\"Image\"\n  placeholder={'Drop an image}\n/>\n"
  },
  "Input": {
    "react": "import { Input } from '@larose-ui/react';\n\nexport default function App() {\n  return <Input\n  label=\"Email\"\n  placeholder=\"you@company.com\"\n  inputSize=\"md\"\n  required={false}\n  disabled={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Input } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Input\n  label=\"Email\"\n  placeholder=\"you@company.com\"\n  inputSize=\"md\"\n  :required=\"false\"\n  :disabled=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Input } from '@larose-ui/svelte';\n</script>\n\n<Input\n  label=\"Email\"\n  placeholder=\"you@company.com\"\n  inputSize=\"md\"\n  required={false}\n  disabled={false}\n/>\n"
  },
  "Label": {
    "react": "import { Label } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <Label\n  importance=\"example\"\n  mono\n  selectable\n>\n      Example\n    </Label>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Label } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Label\n  importance=\"example\"\n  mono\n  selectable\n>\n    Example\n  </Label>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Label } from '@larose-ui/svelte';\n</script>\n\n<Label\n  importance=\"example\"\n  mono\n  selectable\n>\n  Example\n</Label>\n"
  },
  "LiquidGlass": {
    "react": "import { LiquidGlass } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <LiquidGlass\n      width={332}\n      height={200}\n      borderRadius={34}\n      blur={18}\n      saturation={1.5}\n      style={{\n        display: 'flex',\n        alignItems: 'flex-end',\n        padding: 20,\n      }}\n    >\n      <div>\n        <strong style={{ color: 'white' }}>Glass card</strong>\n        <p style={{ color: 'rgba(255,255,255,0.8)', margin: '4px 0 0' }}>\n          Edit optics props live.\n        </p>\n      </div>\n    </LiquidGlass>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LiquidGlass } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LiquidGlass\n    :width=\"332\"\n    :height=\"200\"\n    :border-radius=\"34\"\n    :blur=\"18\"\n    :saturation=\"1.5\"\n    :style=\"{ display: 'flex', alignItems: 'flex-end', padding: '20px' }\"\n  >\n    <div>\n      <strong style=\"color: white\">Glass card</strong>\n      <p style=\"color: rgba(255,255,255,0.8); margin: 4px 0 0\">\n        Edit optics props live.\n      </p>\n    </div>\n  </LiquidGlass>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LiquidGlass } from '@larose-ui/svelte';\n</script>\n\n<LiquidGlass\n  width={332}\n  height={200}\n  borderRadius={34}\n  blur={18}\n  saturation={1.5}\n  style=\"display:flex;align-items:flex-end;padding:20px\"\n>\n  <div>\n    <strong style=\"color: white\">Glass card</strong>\n    <p style=\"color: rgba(255,255,255,0.8); margin: 4px 0 0\">\n      Edit optics props live.\n    </p>\n  </div>\n</LiquidGlass>\n"
  },
  "LiquidGlassButton": {
    "react": "import { LiquidGlassButton } from '@larose-ui/react';\n\nexport default function App() {\n  return <LiquidGlassButton>Continue</LiquidGlassButton>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LiquidGlassButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LiquidGlassButton>Continue</LiquidGlassButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LiquidGlassButton } from '@larose-ui/svelte';\n</script>\n\n<LiquidGlassButton>Continue</LiquidGlassButton>\n"
  },
  "LiquidGlassCheckbox": {
    "react": "import { LiquidGlassCheckbox } from '@larose-ui/react';\n\nexport default function App() {\n  return <LiquidGlassCheckbox\n  label=\"Enable liquid glass\"\n  defaultChecked\n  disabled={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LiquidGlassCheckbox } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LiquidGlassCheckbox\n  label=\"Enable liquid glass\"\n  defaultChecked\n  :disabled=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LiquidGlassCheckbox } from '@larose-ui/svelte';\n</script>\n\n<LiquidGlassCheckbox\n  label=\"Enable liquid glass\"\n  defaultChecked\n  disabled={false}\n/>\n"
  },
  "LiquidGlassProgress": {
    "react": "import { LiquidGlassProgress } from '@larose-ui/react';\n\nexport default function App() {\n  return <LiquidGlassProgress\n  value={62}\n  indeterminate={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LiquidGlassProgress } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LiquidGlassProgress\n  :value=\"62\"\n  :indeterminate=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LiquidGlassProgress } from '@larose-ui/svelte';\n</script>\n\n<LiquidGlassProgress\n  value={62}\n  indeterminate={false}\n/>\n"
  },
  "LiquidGlassRange": {
    "react": "import { LiquidGlassRange } from '@larose-ui/react';\n\nexport default function App() {\n  return <LiquidGlassRange\n  defaultValue={50}\n  disabled={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LiquidGlassRange } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LiquidGlassRange\n  :defaultValue=\"50\"\n  :disabled=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LiquidGlassRange } from '@larose-ui/svelte';\n</script>\n\n<LiquidGlassRange\n  defaultValue={50}\n  disabled={false}\n/>\n"
  },
  "LiquidGlassSwitch": {
    "react": "import { LiquidGlassSwitch } from '@larose-ui/react';\n\nexport default function App() {\n  return <LiquidGlassSwitch\n  defaultChecked={false}\n  disabled={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LiquidGlassSwitch } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LiquidGlassSwitch\n  :defaultChecked=\"false\"\n  :disabled=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LiquidGlassSwitch } from '@larose-ui/svelte';\n</script>\n\n<LiquidGlassSwitch\n  defaultChecked={false}\n  disabled={false}\n/>\n"
  },
  "LiquidGlassTabBar": {
    "react": "import { LiquidGlassTabBar } from '@larose-ui/react';\n\nexport default function App() {\n  return <LiquidGlassTabBar\n  activeColor=\"#ffffff\"\n  activeKey={controlledActiveKey ?? internalActiveKey;}\n  borderRadius={LIQUID_GLASS_PRESETS.tabBar.borderRadius}\n  bottom={22}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LiquidGlassTabBar } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LiquidGlassTabBar\n  activeColor=\"#ffffff\"\n  :activeKey=\"controlledActiveKey ?? internalActiveKey;\"\n  :borderRadius=\"LIQUID_GLASS_PRESETS.tabBar.borderRadius\"\n  :bottom=\"22\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LiquidGlassTabBar } from '@larose-ui/svelte';\n</script>\n\n<LiquidGlassTabBar\n  activeColor=\"#ffffff\"\n  activeKey={controlledActiveKey ?? internalActiveKey;}\n  borderRadius={LIQUID_GLASS_PRESETS.tabBar.borderRadius}\n  bottom={22}\n/>\n"
  },
  "LiquidGlassTopBar": {
    "react": "import { LiquidGlassTopBar } from '@larose-ui/react';\n\nexport default function App() {\n  return <LiquidGlassTopBar\n  activeColor=\"#ffffff\"\n  activeKey={controlledActiveKey ?? internalActiveKey;}\n  borderRadius={borderRadiusProp ?? (isFloating ? LIQUID_GLASS_PRESETS.topBar.borderRadius : 0);}\n  defaultActiveKey=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LiquidGlassTopBar } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LiquidGlassTopBar\n  activeColor=\"#ffffff\"\n  :activeKey=\"controlledActiveKey ?? internalActiveKey;\"\n  :borderRadius=\"borderRadiusProp ?? (isFloating ? LIQUID_GLASS_PRESETS.topBar.borderRadius : 0);\"\n  defaultActiveKey=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LiquidGlassTopBar } from '@larose-ui/svelte';\n</script>\n\n<LiquidGlassTopBar\n  activeColor=\"#ffffff\"\n  activeKey={controlledActiveKey ?? internalActiveKey;}\n  borderRadius={borderRadiusProp ?? (isFloating ? LIQUID_GLASS_PRESETS.topBar.borderRadius : 0);}\n  defaultActiveKey=\"example\"\n/>\n"
  },
  "List": {
    "react": "import { List } from '@larose-ui/react';\n\nexport default function App() {\n  return <List\n  aria-label=\"example\"\n  variant=\"md\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { List } from '@larose-ui/vue';\n</script>\n\n<template>\n  <List\n  aria-label=\"example\"\n  variant=\"md\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { List } from '@larose-ui/svelte';\n</script>\n\n<List\n  aria-label=\"example\"\n  variant=\"md\"\n/>\n"
  },
  "ListRow": {
    "react": "import { ListRow } from '@larose-ui/react';\n\nexport default function App() {\n  return <ListRow\n  accessory=\"example\"\n  disabled\n  selected\n  subtitle=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ListRow } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ListRow\n  accessory=\"example\"\n  disabled\n  selected\n  subtitle=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ListRow } from '@larose-ui/svelte';\n</script>\n\n<ListRow\n  accessory=\"example\"\n  disabled\n  selected\n  subtitle=\"example\"\n/>\n"
  },
  "ListSection": {
    "react": "import { ListSection } from '@larose-ui/react';\n\nexport default function App() {\n  return <ListSection\n  header=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ListSection } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ListSection\n  header=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ListSection } from '@larose-ui/svelte';\n</script>\n\n<ListSection\n  header=\"example\"\n/>\n"
  },
  "Lockup": {
    "react": "import { Lockup } from '@larose-ui/react';\n\nexport default function App() {\n  return <Lockup\n  aria-label=\"example\"\n  axis=\"example\"\n  focused\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Lockup } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Lockup\n  aria-label=\"example\"\n  axis=\"example\"\n  focused\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Lockup } from '@larose-ui/svelte';\n</script>\n\n<Lockup\n  aria-label=\"example\"\n  axis=\"example\"\n  focused\n/>\n"
  },
  "LockupCard": {
    "react": "import { LockupCard } from '@larose-ui/react';\n\nexport default function App() {\n  return <LockupCard\n  rating={0}\n  review=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LockupCard } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LockupCard\n  :rating=\"0\"\n  review=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LockupCard } from '@larose-ui/svelte';\n</script>\n\n<LockupCard\n  rating={0}\n  review=\"example\"\n/>\n"
  },
  "LockupRow": {
    "react": "import { LockupRow } from '@larose-ui/react';\n\nexport default function App() {\n  return <LockupRow\n  axis=\"example\"\n  itemWidth=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { LockupRow } from '@larose-ui/vue';\n</script>\n\n<template>\n  <LockupRow\n  axis=\"example\"\n  itemWidth=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { LockupRow } from '@larose-ui/svelte';\n</script>\n\n<LockupRow\n  axis=\"example\"\n  itemWidth=\"example\"\n/>\n"
  },
  "Menu": {
    "react": "import { Menu } from '@larose-ui/react';\n\nexport default function App() {\n  return <Menu\n  dimBackground\n  enableMnemonics\n  enableShortcuts\n  enableTypeAhead\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Menu } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Menu\n  dimBackground\n  enableMnemonics\n  enableShortcuts\n  enableTypeAhead\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Menu } from '@larose-ui/svelte';\n</script>\n\n<Menu\n  dimBackground\n  enableMnemonics\n  enableShortcuts\n  enableTypeAhead\n/>\n"
  },
  "MenuBar": {
    "react": "import { MenuBar } from '@larose-ui/react';\n\nexport default function App() {\n  return <MenuBar\n  appName=\"example\"\n  enableGlobalShortcuts\n  enableMnemonics\n  enableTypeAhead\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { MenuBar } from '@larose-ui/vue';\n</script>\n\n<template>\n  <MenuBar\n  appName=\"example\"\n  enableGlobalShortcuts\n  enableMnemonics\n  enableTypeAhead\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { MenuBar } from '@larose-ui/svelte';\n</script>\n\n<MenuBar\n  appName=\"example\"\n  enableGlobalShortcuts\n  enableMnemonics\n  enableTypeAhead\n/>\n"
  },
  "MenuBarExtra": {
    "react": "import { MenuBarExtra } from '@larose-ui/react';\n\nexport default function App() {\n  return <MenuBarExtra\n  enableMnemonics={true}\n  enableTypeAhead={true}\n  isOpen\n  mnemonicVisible={false}\n  optionKey\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { MenuBarExtra } from '@larose-ui/vue';\n</script>\n\n<template>\n  <MenuBarExtra\n  :enableMnemonics=\"true\"\n  :enableTypeAhead=\"true\"\n  isOpen\n  :mnemonicVisible=\"false\"\n  optionKey\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { MenuBarExtra } from '@larose-ui/svelte';\n</script>\n\n<MenuBarExtra\n  enableMnemonics={true}\n  enableTypeAhead={true}\n  isOpen\n  mnemonicVisible={false}\n  optionKey\n/>\n"
  },
  "MnemonicLabel": {
    "react": "import { MnemonicLabel } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <MnemonicLabel\n  label=\"example\"\n  mnemonic=\"example\"\n  showAccessKey\n>\n      Example\n    </MnemonicLabel>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { MnemonicLabel } from '@larose-ui/vue';\n</script>\n\n<template>\n  <MnemonicLabel\n  label=\"example\"\n  mnemonic=\"example\"\n  showAccessKey\n>\n    Example\n  </MnemonicLabel>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { MnemonicLabel } from '@larose-ui/svelte';\n</script>\n\n<MnemonicLabel\n  label=\"example\"\n  mnemonic=\"example\"\n  showAccessKey\n>\n  Example\n</MnemonicLabel>\n"
  },
  "Modal": {
    "react": "import { useState } from 'react';\nimport { Button, Modal } from '@larose-ui/react';\n\nexport default function App() {\n  const [open, setOpen] = useState(true);\n  return (\n    <>\n      <Button variant=\"primary\" onClick={() => setOpen(true)}>\n        Open modal\n      </Button>\n      <Modal open={open} onClose={() => setOpen(false)} title=\"Confirm\">\n        <p>Edit this demo to try Modal props.</p>\n        <Button variant=\"primary\" onClick={() => setOpen(false)}>\n          Done\n        </Button>\n      </Modal>\n    </>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ref } from 'vue';\nimport { Button, Modal } from '@larose-ui/vue';\n\nconst open = ref(true);\n</script>\n\n<template>\n  <Button variant=\"primary\" @click=\"open = true\">Open modal</Button>\n  <Modal :open=\"open\" title=\"Confirm\" @close=\"open = false\">\n    <p>Edit this demo to try Modal props.</p>\n    <Button variant=\"primary\" @click=\"open = false\">Done</Button>\n  </Modal>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Button, Modal } from '@larose-ui/svelte';\n  let open = $state(true);\n</script>\n\n<Button variant=\"primary\" onclick={() => (open = true)}>Open modal</Button>\n<Modal {open} title=\"Confirm\" onclose={() => (open = false)}>\n  <p>Edit this demo to try Modal props.</p>\n  <Button variant=\"primary\" onclick={() => (open = false)}>Done</Button>\n</Modal>\n"
  },
  "Monogram": {
    "react": "import { Monogram } from '@larose-ui/react';\n\nexport default function App() {\n  return <Monogram\n  imageUrl=\"example\"\n  name=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Monogram } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Monogram\n  imageUrl=\"example\"\n  name=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Monogram } from '@larose-ui/svelte';\n</script>\n\n<Monogram\n  imageUrl=\"example\"\n  name=\"example\"\n/>\n"
  },
  "MorePullDownButton": {
    "react": "import { MorePullDownButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <MorePullDownButton >\n      Example\n    </MorePullDownButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { MorePullDownButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <MorePullDownButton >\n    Example\n  </MorePullDownButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { MorePullDownButton } from '@larose-ui/svelte';\n</script>\n\n<MorePullDownButton >\n  Example\n</MorePullDownButton>\n"
  },
  "Ornament": {
    "react": "import { Ornament } from '@larose-ui/react';\n\nexport default function App() {\n  return <Ornament />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Ornament } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Ornament />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Ornament } from '@larose-ui/svelte';\n</script>\n\n<Ornament />\n"
  },
  "OrnamentButton": {
    "react": "import { OrnamentButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <OrnamentButton\n  active\n>\n      Example\n    </OrnamentButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { OrnamentButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <OrnamentButton\n  active\n>\n    Example\n  </OrnamentButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { OrnamentButton } from '@larose-ui/svelte';\n</script>\n\n<OrnamentButton\n  active\n>\n  Example\n</OrnamentButton>\n"
  },
  "OrnamentWindow": {
    "react": "import { OrnamentWindow } from '@larose-ui/react';\n\nexport default function App() {\n  return <OrnamentWindow\n  aria-label=\"example\"\n  alignment=\"center\"\n  edge=\"bottom\"\n  immersive={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { OrnamentWindow } from '@larose-ui/vue';\n</script>\n\n<template>\n  <OrnamentWindow\n  aria-label=\"example\"\n  alignment=\"center\"\n  edge=\"bottom\"\n  :immersive=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { OrnamentWindow } from '@larose-ui/svelte';\n</script>\n\n<OrnamentWindow\n  aria-label=\"example\"\n  alignment=\"center\"\n  edge=\"bottom\"\n  immersive={false}\n/>\n"
  },
  "OutlineView": {
    "react": "import { OutlineView } from '@larose-ui/react';\n\nexport default function App() {\n  return <OutlineView\n  aria-label=\"example\"\n  alternatingRows={true}\n  defaultExpandedIds={[]}\n  defaultSortDirection=\"asc\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { OutlineView } from '@larose-ui/vue';\n</script>\n\n<template>\n  <OutlineView\n  aria-label=\"example\"\n  :alternatingRows=\"true\"\n  :defaultExpandedIds=\"[]\"\n  defaultSortDirection=\"asc\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { OutlineView } from '@larose-ui/svelte';\n</script>\n\n<OutlineView\n  aria-label=\"example\"\n  alternatingRows={true}\n  defaultExpandedIds={[]}\n  defaultSortDirection=\"asc\"\n/>\n"
  },
  "OutlineViewToolbar": {
    "react": "import { OutlineViewToolbar } from '@larose-ui/react';\n\nexport default function App() {\n  return <OutlineViewToolbar\n  aria-label=\"example\"\n  placeholder=\"example\"\n  searchQuery=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { OutlineViewToolbar } from '@larose-ui/vue';\n</script>\n\n<template>\n  <OutlineViewToolbar\n  aria-label=\"example\"\n  placeholder=\"example\"\n  searchQuery=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { OutlineViewToolbar } from '@larose-ui/svelte';\n</script>\n\n<OutlineViewToolbar\n  aria-label=\"example\"\n  placeholder=\"example\"\n  searchQuery=\"example\"\n/>\n"
  },
  "Pagination": {
    "react": "import { Pagination } from '@larose-ui/react';\n\nexport default function App() {\n  return <Pagination\n  aria-label=\"example\"\n  nextLabel=\"example\"\n  page={0}\n  previousLabel=\"example\"\n  totalPages={0}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Pagination } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Pagination\n  aria-label=\"example\"\n  nextLabel=\"example\"\n  :page=\"0\"\n  previousLabel=\"example\"\n  :totalPages=\"0\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Pagination } from '@larose-ui/svelte';\n</script>\n\n<Pagination\n  aria-label=\"example\"\n  nextLabel=\"example\"\n  page={0}\n  previousLabel=\"example\"\n  totalPages={0}\n/>\n"
  },
  "PathControl": {
    "react": "import { PathControl } from '@larose-ui/react';\n\nexport default function App() {\n  return <PathControl\n  aria-label=\"example\"\n  editable\n  selectedId=\"example\"\n  variant=\"md\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { PathControl } from '@larose-ui/vue';\n</script>\n\n<template>\n  <PathControl\n  aria-label=\"example\"\n  editable\n  selectedId=\"example\"\n  variant=\"md\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { PathControl } from '@larose-ui/svelte';\n</script>\n\n<PathControl\n  aria-label=\"example\"\n  editable\n  selectedId=\"example\"\n  variant=\"md\"\n/>\n"
  },
  "Picker": {
    "react": "import { Picker } from '@larose-ui/react';\n\nexport default function App() {\n  return <Picker\n  aria-label=\"example\"\n  appearance=\"example\"\n  disabled={false}\n  error={null}\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Picker } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Picker\n  aria-label=\"example\"\n  appearance=\"example\"\n  :disabled=\"false\"\n  :error=\"null\"\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Picker } from '@larose-ui/svelte';\n</script>\n\n<Picker\n  aria-label=\"example\"\n  appearance=\"example\"\n  disabled={false}\n  error={null}\n  value=\"example\"\n/>\n"
  },
  "Popover": {
    "react": "import { Popover } from '@larose-ui/react';\n\nexport default function App() {\n  return <Popover\n  aria-label=\"example\"\n  defaultOpen={false}\n  open\n  panelClassName=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Popover } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Popover\n  aria-label=\"example\"\n  :defaultOpen=\"false\"\n  open\n  panelClassName=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Popover } from '@larose-ui/svelte';\n</script>\n\n<Popover\n  aria-label=\"example\"\n  defaultOpen={false}\n  open\n  panelClassName=\"example\"\n/>\n"
  },
  "PopUpButton": {
    "react": "import { PopUpButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <PopUpButton\n  customOption=\"example\"\n  defaultValue=\"example\"\n  disabled={false}\n  explanatoryText=\"example\"\n>\n      Example\n    </PopUpButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { PopUpButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <PopUpButton\n  customOption=\"example\"\n  defaultValue=\"example\"\n  :disabled=\"false\"\n  explanatoryText=\"example\"\n>\n    Example\n  </PopUpButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { PopUpButton } from '@larose-ui/svelte';\n</script>\n\n<PopUpButton\n  customOption=\"example\"\n  defaultValue=\"example\"\n  disabled={false}\n  explanatoryText=\"example\"\n>\n  Example\n</PopUpButton>\n"
  },
  "Poster": {
    "react": "import { Poster } from '@larose-ui/react';\n\nexport default function App() {\n  return <Poster\n  imageUrl=\"example\"\n  subtitle=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Poster } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Poster\n  imageUrl=\"example\"\n  subtitle=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Poster } from '@larose-ui/svelte';\n</script>\n\n<Poster\n  imageUrl=\"example\"\n  subtitle=\"example\"\n/>\n"
  },
  "Progress": {
    "react": "import { Progress } from '@larose-ui/react';\n\nexport default function App() {\n  return <Progress\n  value={65}\n  variant=\"default\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Progress } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Progress\n  :value=\"65\"\n  variant=\"default\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Progress } from '@larose-ui/svelte';\n</script>\n\n<Progress\n  value={65}\n  variant=\"default\"\n/>\n"
  },
  "PullDownButton": {
    "react": "import { PullDownButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <PullDownButton\n  destructiveConfirmation=\"example\"\n  disabled={false}\n  label=\"example\"\n  longPress={false}\n>\n      Example\n    </PullDownButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { PullDownButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <PullDownButton\n  destructiveConfirmation=\"example\"\n  :disabled=\"false\"\n  label=\"example\"\n  :longPress=\"false\"\n>\n    Example\n  </PullDownButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { PullDownButton } from '@larose-ui/svelte';\n</script>\n\n<PullDownButton\n  destructiveConfirmation=\"example\"\n  disabled={false}\n  label=\"example\"\n  longPress={false}\n>\n  Example\n</PullDownButton>\n"
  },
  "Radio": {
    "react": "import { Radio } from '@larose-ui/react';\n\nexport default function App() {\n  return <Radio\n  label=\"Starter plan\"\n  checked\n  disabled={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Radio } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Radio\n  label=\"Starter plan\"\n  checked\n  :disabled=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Radio } from '@larose-ui/svelte';\n</script>\n\n<Radio\n  label=\"Starter plan\"\n  checked\n  disabled={false}\n/>\n"
  },
  "SecureField": {
    "react": "import { SecureField } from '@larose-ui/react';\n\nexport default function App() {\n  return <SecureField />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { SecureField } from '@larose-ui/vue';\n</script>\n\n<template>\n  <SecureField />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { SecureField } from '@larose-ui/svelte';\n</script>\n\n<SecureField />\n"
  },
  "Select": {
    "react": "import { Select } from '@larose-ui/react';\n\nexport default function App() {\n  return <Select\n  label=\"Department\"\n  placeholder=\"Choose department\"\n  disabled={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Select } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Select\n  label=\"Department\"\n  placeholder=\"Choose department\"\n  :disabled=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Select } from '@larose-ui/svelte';\n</script>\n\n<Select\n  label=\"Department\"\n  placeholder=\"Choose department\"\n  disabled={false}\n/>\n"
  },
  "Skeleton": {
    "react": "import { Skeleton } from '@larose-ui/react';\n\nexport default function App() {\n  return <Skeleton\n  height=\"1rem\"\n  lines={1}\n  variant=\"text\"\n  width=\"100%\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Skeleton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Skeleton\n  height=\"1rem\"\n  :lines=\"1\"\n  variant=\"text\"\n  width=\"100%\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Skeleton } from '@larose-ui/svelte';\n</script>\n\n<Skeleton\n  height=\"1rem\"\n  lines={1}\n  variant=\"text\"\n  width=\"100%\"\n/>\n"
  },
  "Spinner": {
    "react": "import { Spinner } from '@larose-ui/react';\n\nexport default function App() {\n  return <Spinner\n  label=\"Loading\"\n  size=\"md\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Spinner } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Spinner\n  label=\"Loading\"\n  size=\"md\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Spinner } from '@larose-ui/svelte';\n</script>\n\n<Spinner\n  label=\"Loading\"\n  size=\"md\"\n/>\n"
  },
  "SplitView": {
    "react": "import { SplitView } from '@larose-ui/react';\n\nexport default function App() {\n  return <SplitView\n  aria-label=\"example\"\n  compactMode=\"side-by-side\"\n  orientation=\"horizontal\"\n  storageKey=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { SplitView } from '@larose-ui/vue';\n</script>\n\n<template>\n  <SplitView\n  aria-label=\"example\"\n  compactMode=\"side-by-side\"\n  orientation=\"horizontal\"\n  storageKey=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { SplitView } from '@larose-ui/svelte';\n</script>\n\n<SplitView\n  aria-label=\"example\"\n  compactMode=\"side-by-side\"\n  orientation=\"horizontal\"\n  storageKey=\"example\"\n/>\n"
  },
  "SplitViewPane": {
    "react": "import { SplitViewPane } from '@larose-ui/react';\n\nexport default function App() {\n  return <SplitViewPane\n  aria-label=\"example\"\n  collapsible\n  defaultSize={0}\n  defaultVisible\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { SplitViewPane } from '@larose-ui/vue';\n</script>\n\n<template>\n  <SplitViewPane\n  aria-label=\"example\"\n  collapsible\n  :defaultSize=\"0\"\n  defaultVisible\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { SplitViewPane } from '@larose-ui/svelte';\n</script>\n\n<SplitViewPane\n  aria-label=\"example\"\n  collapsible\n  defaultSize={0}\n  defaultVisible\n/>\n"
  },
  "SplitViewToolbar": {
    "react": "import { SplitViewToolbar } from '@larose-ui/react';\n\nexport default function App() {\n  return <SplitViewToolbar />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { SplitViewToolbar } from '@larose-ui/vue';\n</script>\n\n<template>\n  <SplitViewToolbar />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { SplitViewToolbar } from '@larose-ui/svelte';\n</script>\n\n<SplitViewToolbar />\n"
  },
  "SquareButton": {
    "react": "import { SquareButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <SquareButton\n  pressed={false}\n  tooltip=\"example\"\n>\n      Example\n    </SquareButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { SquareButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <SquareButton\n  :pressed=\"false\"\n  tooltip=\"example\"\n>\n    Example\n  </SquareButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { SquareButton } from '@larose-ui/svelte';\n</script>\n\n<SquareButton\n  pressed={false}\n  tooltip=\"example\"\n>\n  Example\n</SquareButton>\n"
  },
  "Switch": {
    "react": "import { Switch } from '@larose-ui/react';\n\nexport default function App() {\n  return <Switch\n  label=\"Notifications\"\n  checked\n  disabled={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Switch } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Switch\n  label=\"Notifications\"\n  checked\n  :disabled=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Switch } from '@larose-ui/svelte';\n</script>\n\n<Switch\n  label=\"Notifications\"\n  checked\n  disabled={false}\n/>\n"
  },
  "Table": {
    "react": "import { Table } from '@larose-ui/react';\n\nexport default function App() {\n  return <Table\n  aria-label=\"example\"\n  alternatingRows={true}\n  caption=\"example\"\n  defaultSortDirection=\"asc\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Table } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Table\n  aria-label=\"example\"\n  :alternatingRows=\"true\"\n  caption=\"example\"\n  defaultSortDirection=\"asc\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Table } from '@larose-ui/svelte';\n</script>\n\n<Table\n  aria-label=\"example\"\n  alternatingRows={true}\n  caption=\"example\"\n  defaultSortDirection=\"asc\"\n/>\n"
  },
  "Tabs": {
    "react": "import { Tabs } from '@larose-ui/react';\n\nexport default function App() {\n  return <Tabs\n  defaultValue=\"\"\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Tabs } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Tabs\n  defaultValue=\"\"\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Tabs } from '@larose-ui/svelte';\n</script>\n\n<Tabs\n  defaultValue=\"\"\n  value=\"example\"\n/>\n"
  },
  "TabsList": {
    "react": "import { TabsList } from '@larose-ui/react';\n\nexport default function App() {\n  return <TabsList\n  aria-label=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TabsList } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TabsList\n  aria-label=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TabsList } from '@larose-ui/svelte';\n</script>\n\n<TabsList\n  aria-label=\"example\"\n/>\n"
  },
  "TabsPanel": {
    "react": "import { TabsPanel } from '@larose-ui/react';\n\nexport default function App() {\n  return <TabsPanel\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TabsPanel } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TabsPanel\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TabsPanel } from '@larose-ui/svelte';\n</script>\n\n<TabsPanel\n  value=\"example\"\n/>\n"
  },
  "TabsTrigger": {
    "react": "import { TabsTrigger } from '@larose-ui/react';\n\nexport default function App() {\n  return <TabsTrigger\n  disabled\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TabsTrigger } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TabsTrigger\n  disabled\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TabsTrigger } from '@larose-ui/svelte';\n</script>\n\n<TabsTrigger\n  disabled\n  value=\"example\"\n/>\n"
  },
  "TabView": {
    "react": "import { TabView } from '@larose-ui/react';\n\nexport default function App() {\n  return <TabView\n  aria-label=\"example\"\n  defaultValue=\"\"\n  inset={true}\n  showTabs={true}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TabView } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TabView\n  aria-label=\"example\"\n  defaultValue=\"\"\n  :inset=\"true\"\n  :showTabs=\"true\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TabView } from '@larose-ui/svelte';\n</script>\n\n<TabView\n  aria-label=\"example\"\n  defaultValue=\"\"\n  inset={true}\n  showTabs={true}\n/>\n"
  },
  "TabViewList": {
    "react": "import { TabViewList } from '@larose-ui/react';\n\nexport default function App() {\n  return <TabViewList\n  aria-label=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TabViewList } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TabViewList\n  aria-label=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TabViewList } from '@larose-ui/svelte';\n</script>\n\n<TabViewList\n  aria-label=\"example\"\n/>\n"
  },
  "TabViewPanel": {
    "react": "import { TabViewPanel } from '@larose-ui/react';\n\nexport default function App() {\n  return <TabViewPanel\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TabViewPanel } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TabViewPanel\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TabViewPanel } from '@larose-ui/svelte';\n</script>\n\n<TabViewPanel\n  value=\"example\"\n/>\n"
  },
  "TabViewTab": {
    "react": "import { TabViewTab } from '@larose-ui/react';\n\nexport default function App() {\n  return <TabViewTab\n  disabled\n  label=\"example\"\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TabViewTab } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TabViewTab\n  disabled\n  label=\"example\"\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TabViewTab } from '@larose-ui/svelte';\n</script>\n\n<TabViewTab\n  disabled\n  label=\"example\"\n  value=\"example\"\n/>\n"
  },
  "Textarea": {
    "react": "import { Textarea } from '@larose-ui/react';\n\nexport default function App() {\n  return <Textarea\n  label=\"Description\"\n  placeholder=\"Enter details...\"\n  disabled={false}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Textarea } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Textarea\n  label=\"Description\"\n  placeholder=\"Enter details...\"\n  :disabled=\"false\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Textarea } from '@larose-ui/svelte';\n</script>\n\n<Textarea\n  label=\"Description\"\n  placeholder=\"Enter details...\"\n  disabled={false}\n/>\n"
  },
  "TextView": {
    "react": "import { TextView } from '@larose-ui/react';\n\nexport default function App() {\n  return <TextView\n  editable={false}\n  maxHeight=\"example\"\n  selectable={true}\n  typographyRole=\"body\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TextView } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TextView\n  :editable=\"false\"\n  maxHeight=\"example\"\n  :selectable=\"true\"\n  typographyRole=\"body\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TextView } from '@larose-ui/svelte';\n</script>\n\n<TextView\n  editable={false}\n  maxHeight=\"example\"\n  selectable={true}\n  typographyRole=\"body\"\n/>\n"
  },
  "ThemeCustomizationContext": {
    "react": "import { ThemeCustomizationContext } from '@larose-ui/react';\n\nexport default function App() {\n  return <ThemeCustomizationContext />;\n}\n"
  },
  "TimePicker": {
    "react": "import { TimePicker } from '@larose-ui/react';\n\nexport default function App() {\n  return <TimePicker\n  error={null}\n  hint=\"example\"\n  inputSize=\"md\"\n  label=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TimePicker } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TimePicker\n  :error=\"null\"\n  hint=\"example\"\n  inputSize=\"md\"\n  label=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TimePicker } from '@larose-ui/svelte';\n</script>\n\n<TimePicker\n  error={null}\n  hint=\"example\"\n  inputSize=\"md\"\n  label=\"example\"\n/>\n"
  },
  "TokenField": {
    "react": "import { TokenField } from '@larose-ui/react';\n\nexport default function App() {\n  return <TokenField\n  aria-label=\"example\"\n  placeholder=\"example\"\n  suggestionDelayMs={0}\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { TokenField } from '@larose-ui/vue';\n</script>\n\n<template>\n  <TokenField\n  aria-label=\"example\"\n  placeholder=\"example\"\n  :suggestionDelayMs=\"0\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { TokenField } from '@larose-ui/svelte';\n</script>\n\n<TokenField\n  aria-label=\"example\"\n  placeholder=\"example\"\n  suggestionDelayMs={0}\n/>\n"
  },
  "Toolbar": {
    "react": "import { Toolbar } from '@larose-ui/react';\n\nexport default function App() {\n  return <Toolbar\n  aria-label=\"example\"\n  largeTitle\n  placement=\"md\"\n  platform=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Toolbar } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Toolbar\n  aria-label=\"example\"\n  largeTitle\n  placement=\"md\"\n  platform=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Toolbar } from '@larose-ui/svelte';\n</script>\n\n<Toolbar\n  aria-label=\"example\"\n  largeTitle\n  placement=\"md\"\n  platform=\"example\"\n/>\n"
  },
  "ToolbarBackButton": {
    "react": "import { ToolbarBackButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <ToolbarBackButton\n  companionLabel=\"example\"\n  disabled\n>\n      Example\n    </ToolbarBackButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarBackButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarBackButton\n  companionLabel=\"example\"\n  disabled\n>\n    Example\n  </ToolbarBackButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarBackButton } from '@larose-ui/svelte';\n</script>\n\n<ToolbarBackButton\n  companionLabel=\"example\"\n  disabled\n>\n  Example\n</ToolbarBackButton>\n"
  },
  "ToolbarCloseButton": {
    "react": "import { ToolbarCloseButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <ToolbarCloseButton\n  disabled\n>\n      Example\n    </ToolbarCloseButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarCloseButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarCloseButton\n  disabled\n>\n    Example\n  </ToolbarCloseButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarCloseButton } from '@larose-ui/svelte';\n</script>\n\n<ToolbarCloseButton\n  disabled\n>\n  Example\n</ToolbarCloseButton>\n"
  },
  "ToolbarDocumentMenu": {
    "react": "import { ToolbarDocumentMenu } from '@larose-ui/react';\n\nexport default function App() {\n  return <ToolbarDocumentMenu\n  disabled\n  label=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarDocumentMenu } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarDocumentMenu\n  disabled\n  label=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarDocumentMenu } from '@larose-ui/svelte';\n</script>\n\n<ToolbarDocumentMenu\n  disabled\n  label=\"example\"\n/>\n"
  },
  "ToolbarFixedSpace": {
    "react": "import { ToolbarFixedSpace } from '@larose-ui/react';\n\nexport default function App() {\n  return <ToolbarFixedSpace />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarFixedSpace } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarFixedSpace />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarFixedSpace } from '@larose-ui/svelte';\n</script>\n\n<ToolbarFixedSpace />\n"
  },
  "ToolbarGroup": {
    "react": "import { ToolbarGroup } from '@larose-ui/react';\n\nexport default function App() {\n  return <ToolbarGroup />;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarGroup } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarGroup />\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarGroup } from '@larose-ui/svelte';\n</script>\n\n<ToolbarGroup />\n"
  },
  "ToolbarItem": {
    "react": "import { ToolbarItem } from '@larose-ui/react';\n\nexport default function App() {\n  return <ToolbarItem\n  collapsible\n  disabled\n  label=\"example\"\n  prominent\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarItem } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarItem\n  collapsible\n  disabled\n  label=\"example\"\n  prominent\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarItem } from '@larose-ui/svelte';\n</script>\n\n<ToolbarItem\n  collapsible\n  disabled\n  label=\"example\"\n  prominent\n/>\n"
  },
  "ToolbarMoreButton": {
    "react": "import { ToolbarMoreButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <ToolbarMoreButton\n  aria-label=\"example\"\n  disabled\n>\n      Example\n    </ToolbarMoreButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarMoreButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarMoreButton\n  aria-label=\"example\"\n  disabled\n>\n    Example\n  </ToolbarMoreButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarMoreButton } from '@larose-ui/svelte';\n</script>\n\n<ToolbarMoreButton\n  aria-label=\"example\"\n  disabled\n>\n  Example\n</ToolbarMoreButton>\n"
  },
  "ToolbarProminentButton": {
    "react": "import { ToolbarProminentButton } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <ToolbarProminentButton\n  disabled\n>\n      Example\n    </ToolbarProminentButton>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarProminentButton } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarProminentButton\n  disabled\n>\n    Example\n  </ToolbarProminentButton>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarProminentButton } from '@larose-ui/svelte';\n</script>\n\n<ToolbarProminentButton\n  disabled\n>\n  Example\n</ToolbarProminentButton>\n"
  },
  "ToolbarSearch": {
    "react": "import { ToolbarSearch } from '@larose-ui/react';\n\nexport default function App() {\n  return <ToolbarSearch\n  aria-label=\"example\"\n  placeholder=\"example\"\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarSearch } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarSearch\n  aria-label=\"example\"\n  placeholder=\"example\"\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarSearch } from '@larose-ui/svelte';\n</script>\n\n<ToolbarSearch\n  aria-label=\"example\"\n  placeholder=\"example\"\n  value=\"example\"\n/>\n"
  },
  "ToolbarSection": {
    "react": "import { ToolbarSection } from '@larose-ui/react';\n\nexport default function App() {\n  return <ToolbarSection\n  collapsible\n  placement=\"md\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarSection } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarSection\n  collapsible\n  placement=\"md\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarSection } from '@larose-ui/svelte';\n</script>\n\n<ToolbarSection\n  collapsible\n  placement=\"md\"\n/>\n"
  },
  "ToolbarTitle": {
    "react": "import { ToolbarTitle } from '@larose-ui/react';\n\nexport default function App() {\n  return <ToolbarTitle\n  large\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { ToolbarTitle } from '@larose-ui/vue';\n</script>\n\n<template>\n  <ToolbarTitle\n  large\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { ToolbarTitle } from '@larose-ui/svelte';\n</script>\n\n<ToolbarTitle\n  large\n/>\n"
  },
  "Tooltip": {
    "react": "import { Tooltip } from '@larose-ui/react';\n\nexport default function App() {\n  return <Tooltip\n  side=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Tooltip } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Tooltip\n  side=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Tooltip } from '@larose-ui/svelte';\n</script>\n\n<Tooltip\n  side=\"example\"\n/>\n"
  },
  "Typography": {
    "react": "import { Typography } from '@larose-ui/react';\n\nexport default function App() {\n  return (\n    <Typography\n  role=\"body\"\n  muted={false}\n>\n      Refined typography\n    </Typography>\n  );\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { Typography } from '@larose-ui/vue';\n</script>\n\n<template>\n  <Typography\n  role=\"body\"\n  :muted=\"false\"\n>\n    Refined typography\n  </Typography>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { Typography } from '@larose-ui/svelte';\n</script>\n\n<Typography\n  role=\"body\"\n  muted={false}\n>\n  Refined typography\n</Typography>\n"
  },
  "UnsavedIndicator": {
    "react": "import { UnsavedIndicator } from '@larose-ui/react';\n\nexport default function App() {\n  return <UnsavedIndicator\n  autosaveEnabled\n  edited\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { UnsavedIndicator } from '@larose-ui/vue';\n</script>\n\n<template>\n  <UnsavedIndicator\n  autosaveEnabled\n  edited\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { UnsavedIndicator } from '@larose-ui/svelte';\n</script>\n\n<UnsavedIndicator\n  autosaveEnabled\n  edited\n/>\n"
  },
  "WheelColumn": {
    "react": "import { WheelColumn } from '@larose-ui/react';\n\nexport default function App() {\n  return <WheelColumn\n  columnFlex={0}\n  disabled={false}\n  label=\"example\"\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { WheelColumn } from '@larose-ui/vue';\n</script>\n\n<template>\n  <WheelColumn\n  :columnFlex=\"0\"\n  :disabled=\"false\"\n  label=\"example\"\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { WheelColumn } from '@larose-ui/svelte';\n</script>\n\n<WheelColumn\n  columnFlex={0}\n  disabled={false}\n  label=\"example\"\n  value=\"example\"\n/>\n"
  },
  "WheelPicker": {
    "react": "import { WheelPicker } from '@larose-ui/react';\n\nexport default function App() {\n  return <WheelPicker\n  aria-label=\"example\"\n  compact={false}\n  disabled={false}\n  inline={false}\n  value=\"example\"\n/>;\n}\n",
    "vue": "<script setup lang=\"ts\">\nimport { WheelPicker } from '@larose-ui/vue';\n</script>\n\n<template>\n  <WheelPicker\n  aria-label=\"example\"\n  :compact=\"false\"\n  :disabled=\"false\"\n  :inline=\"false\"\n  value=\"example\"\n/>\n</template>\n",
    "svelte": "<script lang=\"ts\">\n  import { WheelPicker } from '@larose-ui/svelte';\n</script>\n\n<WheelPicker\n  aria-label=\"example\"\n  compact={false}\n  disabled={false}\n  inline={false}\n  value=\"example\"\n/>\n"
  }
};

export function getPlaygroundSeed(name: string): PlaygroundSeedEntry | undefined {
  return playgroundSeeds[name];
}
