/* eslint-disable */
// AUTO-GENERATED by scripts/generate-storybook-parity.mjs — do not edit.

export const GENERATED_STORY_TITLE_CROSS_FRAMEWORK: Record<string, string> = {
  'Auto/MnemonicLabel': 'mnemonicLabel',
  'Auto/OrnamentButton': 'ornamentButton',
};
