/* eslint-disable */
// AUTO-GENERATED by scripts/generate-storybook-parity.mjs — do not edit.

export const GENERATED_STORY_TITLE_CROSS_FRAMEWORK: Record<string, string> = {
  'Auto/MnemonicLabel': 'mnemonicLabel',
  'Auto/OrnamentButton': 'ornamentButton',
  // Curated Foundation stories auto-detected via parity-sync:
  'Foundation/Home Screen Quick Actions': 'homeScreenQuickActions',
  'Foundation/Menu Bar': 'menuBar',
  'Foundation/Popover': 'popover',
};
