/* eslint-disable */
// AUTO-GENERATED by scripts/generate-storybook-parity.mjs — do not edit.
import type { CrossFrameworkComponentDefinition } from '../types';
import { defineSlotParity, definePropsParity } from '../defineParity';
import {
  MnemonicLabel,
  OrnamentButton,
} from '@larose-ui/react';

export const generatedRegistry: Record<string, CrossFrameworkComponentDefinition> = {
  mnemonicLabel: defineSlotParity({
    id: 'mnemonicLabel',
    displayName: 'MnemonicLabel',
    defaultSlot: "MnemonicLabel",
    propKeys: ["label","mnemonic","showAccessKey"],
    defaultProps: {"label":"MnemonicLabel","mnemonic":"MnemonicLabel","showAccessKey":false},
    Component: MnemonicLabel,
  }),

  ornamentButton: defineSlotParity({
    id: 'ornamentButton',
    displayName: 'OrnamentButton',
    defaultSlot: "OrnamentButton",
    propKeys: ["active"],
    defaultProps: {"active":false},
    Component: OrnamentButton,
  }),

};
